# YouTube News Feed Configuration
# Channel whitelist and company keyword mappings

# Channels to fetch videos from
# Format: { 'channel_id': { 'name': 'Channel Name' } }
# To find channel ID: go to YouTube channel > View Page Source > search "channelId"
YOUTUBE_CHANNELS = {
    # US Finance
    'UCfCT7SSFEWyG4th9ZmaGYqQ': {
        'name': 'Joseph Carlson After Hours',
    },
    'UCbta0n8i6Rljh0obO7HzG9A': {
        'name': 'Joseph Carlson',
    },
    'UCrp_UI8XtuYfpiqluWLD7Lw': {
        'name': 'CNBC Television',
    },
    'UCvJJ_dzjViJCoLf5uKUTwoA': {
        'name': 'CNBC',
    },
    'UCF_5sDcM03RZMNqCI_Pi0FA': {
        'name': 'Intelligent Investor',
    },
    'UCEAZeUIeJs0IjQiqTCdVSIg': {
        'name': 'Yahoo Finance',
    },
    'UCzQ2FFVe7m8yIgzXMZtlSjg': {
        'name': 'Steve Eisman',
    },
    'UCRhQsN8AVIfZuBNeRV1A37w': {
        'name': 'Norges Bank Investment Management',
    },
    # Global / European Finance
    'UCIALMKvObZNtJ6AmdCLP7Lg': {
        'name': 'Bloomberg Television',
    },
    'UCxtq4_KPQJTH7cHbnGKpOqQ': {
        'name': 'Financial Times',
    },
    'UCVHFbqXqoYvEWM1Ddxl0QKg': {
        'name': 'Bloomberg Originals',
    },
    'UC3I2GFN_F8WudD_2jUZbojA': {
        'name': 'CNBC International',
    },
    'UCpvvJ2XU0zJjjuQFMpH9c_Q': {
        'name': 'Euronews Business',
    },
}

# Additional keywords for specific companies (optional)
# If a ticker is not in this dict, matching uses the company_name passed from frontend
# Format: { 'TICKER': ['extra_keyword1', 'extra_keyword2', ...] }
EXTRA_KEYWORDS = {
    # ==================== US TECH ====================
    'AAPL': ['Apple', 'iPhone', 'iPad', 'Mac', 'Tim Cook'],
    'MSFT': ['Microsoft', 'Azure', 'Windows', 'Satya Nadella', 'Xbox', 'Copilot'],
    'GOOGL': ['Google', 'Alphabet', 'YouTube', 'Android', 'Sundar Pichai', 'Gemini'],
    'GOOG': ['Google', 'Alphabet', 'YouTube', 'Android', 'Sundar Pichai', 'Gemini'],
    'AMZN': ['Amazon', 'AWS', 'Jeff Bezos', 'Andy Jassy', 'Prime'],
    'META': ['Meta', 'Facebook', 'Instagram', 'WhatsApp', 'Zuckerberg'],
    'NVDA': ['Nvidia', 'Jensen Huang', 'GPU', 'CUDA'],
    'TSLA': ['Tesla', 'Elon Musk', 'Cybertruck', 'Model 3', 'Model Y'],
    'NFLX': ['Netflix'],
    'CRM': ['Salesforce'],
    'ORCL': ['Oracle'],
    'ADBE': ['Adobe', 'Photoshop', 'Creative Cloud'],
    'CSCO': ['Cisco'],
    'INTC': ['Intel', 'Pat Gelsinger'],
    'AMD': ['AMD', 'Lisa Su', 'Ryzen', 'Radeon'],
    'AVGO': ['Broadcom'],
    'QCOM': ['Qualcomm', 'Snapdragon'],
    'TXN': ['Texas Instruments'],
    'MU': ['Micron'],
    'AMAT': ['Applied Materials'],
    'LRCX': ['Lam Research'],
    'KLAC': ['KLA'],
    'ADI': ['Analog Devices'],
    'NOW': ['ServiceNow'],
    'SNOW': ['Snowflake'],
    'PLTR': ['Palantir'],
    'UBER': ['Uber'],
    'LYFT': ['Lyft'],
    'ABNB': ['Airbnb'],
    'SQ': ['Square', 'Block'],
    'PYPL': ['PayPal'],
    'SHOP': ['Shopify'],
    'SPOT': ['Spotify'],
    'ZM': ['Zoom'],
    'DOCU': ['DocuSign'],
    'TWLO': ['Twilio'],
    'NET': ['Cloudflare'],
    'DDOG': ['Datadog'],
    'ZS': ['Zscaler'],
    'CRWD': ['CrowdStrike'],
    'PANW': ['Palo Alto Networks'],
    'FTNT': ['Fortinet'],
    'IBM': ['IBM'],
    'HPQ': ['HP', 'Hewlett-Packard'],
    'HPE': ['Hewlett Packard Enterprise'],
    'DELL': ['Dell'],

    # ==================== US FINANCE ====================
    'JPM': ['JPMorgan', 'JP Morgan', 'Jamie Dimon'],
    'BAC': ['Bank of America', 'BofA'],
    'WFC': ['Wells Fargo'],
    'C': ['Citigroup', 'Citi'],
    'GS': ['Goldman Sachs', 'Goldman'],
    'MS': ['Morgan Stanley'],
    'BLK': ['BlackRock', 'Larry Fink'],
    'SCHW': ['Charles Schwab', 'Schwab'],
    'BX': ['Blackstone'],
    'KKR': ['KKR'],
    'APO': ['Apollo'],
    'V': ['Visa'],
    'MA': ['Mastercard'],
    'AXP': ['American Express', 'Amex'],
    'COF': ['Capital One'],
    'DFS': ['Discover'],
    'USB': ['US Bancorp', 'US Bank'],
    'PNC': ['PNC'],
    'TFC': ['Truist'],
    'BK': ['Bank of New York', 'BNY Mellon'],
    'STT': ['State Street'],
    'AIG': ['AIG'],
    'MET': ['MetLife'],
    'PRU': ['Prudential'],
    'ALL': ['Allstate'],
    'TRV': ['Travelers'],
    'CB': ['Chubb'],
    'AFL': ['Aflac'],
    'PGR': ['Progressive'],
    'CME': ['CME Group'],
    'ICE': ['Intercontinental Exchange'],
    'SPGI': ['S&P Global'],
    'MCO': ['Moody\'s'],
    'MSCI': ['MSCI'],
    'FIS': ['FIS', 'Fidelity National'],
    'FISV': ['Fiserv'],
    'GPN': ['Global Payments'],

    # ==================== US HEALTHCARE ====================
    'JNJ': ['Johnson & Johnson', 'J&J'],
    'UNH': ['UnitedHealth', 'United Health'],
    'PFE': ['Pfizer'],
    'MRK': ['Merck'],
    'ABBV': ['AbbVie'],
    'LLY': ['Eli Lilly', 'Lilly'],
    'TMO': ['Thermo Fisher'],
    'ABT': ['Abbott'],
    'DHR': ['Danaher'],
    'BMY': ['Bristol-Myers', 'Bristol Myers Squibb'],
    'AMGN': ['Amgen'],
    'GILD': ['Gilead'],
    'VRTX': ['Vertex'],
    'REGN': ['Regeneron'],
    'BIIB': ['Biogen'],
    'MRNA': ['Moderna'],
    'CVS': ['CVS'],
    'CI': ['Cigna'],
    'ELV': ['Elevance', 'Anthem'],
    'HUM': ['Humana'],
    'CNC': ['Centene'],
    'MCK': ['McKesson'],
    'CAH': ['Cardinal Health'],
    'ABC': ['AmerisourceBergen', 'Cencora'],
    'SYK': ['Stryker'],
    'BSX': ['Boston Scientific'],
    'MDT': ['Medtronic'],
    'ISRG': ['Intuitive Surgical'],
    'EW': ['Edwards Lifesciences'],
    'ZBH': ['Zimmer Biomet'],
    'DXCM': ['DexCom'],
    'IDXX': ['IDEXX'],
    'IQV': ['IQVIA'],
    'A': ['Agilent'],
    'BIO': ['Bio-Rad'],
    'MTD': ['Mettler-Toledo'],
    'WAT': ['Waters'],

    # ==================== US CONSUMER ====================
    'WMT': ['Walmart'],
    'COST': ['Costco'],
    'HD': ['Home Depot'],
    'LOW': ['Lowe\'s', 'Lowes'],
    'TGT': ['Target'],
    'AMZN': ['Amazon', 'AWS', 'Prime'],
    'MCD': ['McDonald\'s', 'McDonalds'],
    'SBUX': ['Starbucks'],
    'NKE': ['Nike'],
    'KO': ['Coca-Cola', 'Coke'],
    'PEP': ['Pepsi', 'PepsiCo'],
    'PG': ['Procter & Gamble', 'P&G'],
    'CL': ['Colgate', 'Colgate-Palmolive'],
    'KMB': ['Kimberly-Clark', 'Kimberly Clark'],
    'EL': ['Estee Lauder', 'Estée Lauder'],
    'PM': ['Philip Morris'],
    'MO': ['Altria'],
    'BTI': ['British American Tobacco'],
    'KHC': ['Kraft Heinz'],
    'MDLZ': ['Mondelez'],
    'GIS': ['General Mills'],
    'K': ['Kellogg', 'Kellanova'],
    'CAG': ['Conagra'],
    'SJM': ['Smucker', 'J.M. Smucker'],
    'HSY': ['Hershey'],
    'CPB': ['Campbell', 'Campbell Soup'],
    'HRL': ['Hormel'],
    'TSN': ['Tyson'],
    'ADM': ['Archer-Daniels-Midland', 'ADM'],
    'BG': ['Bunge'],
    'CMG': ['Chipotle'],
    'DPZ': ['Domino\'s', 'Dominos'],
    'YUM': ['Yum Brands', 'KFC', 'Taco Bell', 'Pizza Hut'],
    'QSR': ['Restaurant Brands', 'Burger King', 'Tim Hortons'],
    'DRI': ['Darden', 'Olive Garden'],
    'MAR': ['Marriott'],
    'HLT': ['Hilton'],
    'H': ['Hyatt'],
    'WH': ['Wyndham'],
    'LVS': ['Las Vegas Sands'],
    'MGM': ['MGM'],
    'WYNN': ['Wynn'],
    'RCL': ['Royal Caribbean'],
    'CCL': ['Carnival'],
    'NCLH': ['Norwegian Cruise'],
    'EXPE': ['Expedia'],
    'BKNG': ['Booking', 'Booking.com', 'Priceline'],
    'DIS': ['Disney', 'Walt Disney'],
    'CMCSA': ['Comcast', 'NBCUniversal', 'Xfinity'],
    'WBD': ['Warner Bros', 'Discovery'],
    'PARA': ['Paramount'],
    'FOXA': ['Fox'],
    'NWSA': ['News Corp'],
    'LYV': ['Live Nation'],
    'EA': ['Electronic Arts', 'EA Sports'],
    'TTWO': ['Take-Two', 'Rockstar', 'GTA'],
    'ATVI': ['Activision', 'Blizzard'],
    'TJX': ['TJX', 'TJ Maxx', 'Marshalls'],
    'ROST': ['Ross Stores', 'Ross'],
    'BURL': ['Burlington'],
    'GPS': ['Gap'],
    'ANF': ['Abercrombie'],
    'LULU': ['Lululemon'],
    'VFC': ['VF Corp', 'North Face', 'Vans'],
    'RL': ['Ralph Lauren'],
    'PVH': ['PVH', 'Calvin Klein', 'Tommy Hilfiger'],
    'TPR': ['Tapestry', 'Coach', 'Kate Spade'],
    'CPRI': ['Capri', 'Michael Kors', 'Versace'],
    'AEO': ['American Eagle'],
    'URBN': ['Urban Outfitters'],
    'BBY': ['Best Buy'],
    'GME': ['GameStop'],
    'ULTA': ['Ulta'],
    'DG': ['Dollar General'],
    'DLTR': ['Dollar Tree'],
    'FIVE': ['Five Below'],
    'ORLY': ['O\'Reilly', 'O\'Reilly Auto'],
    'AZO': ['AutoZone'],
    'AAP': ['Advance Auto'],
    'KMX': ['CarMax'],
    'AN': ['AutoNation'],
    'F': ['Ford'],
    'GM': ['General Motors', 'GM', 'Chevrolet', 'Cadillac'],
    'STLA': ['Stellantis', 'Jeep', 'Dodge', 'Ram', 'Chrysler', 'Peugeot', 'Fiat'],
    'RIVN': ['Rivian'],
    'LCID': ['Lucid'],
    'NIO': ['NIO'],
    'XPEV': ['XPeng'],
    'LI': ['Li Auto'],

    # ==================== US INDUSTRIAL ====================
    'CAT': ['Caterpillar'],
    'DE': ['Deere', 'John Deere'],
    'BA': ['Boeing'],
    'RTX': ['Raytheon', 'RTX'],
    'LMT': ['Lockheed Martin', 'Lockheed'],
    'NOC': ['Northrop Grumman', 'Northrop'],
    'GD': ['General Dynamics'],
    'GE': ['General Electric', 'GE Aerospace'],
    'HON': ['Honeywell'],
    'MMM': ['3M'],
    'EMR': ['Emerson'],
    'ETN': ['Eaton'],
    'ROK': ['Rockwell'],
    'PH': ['Parker Hannifin', 'Parker'],
    'ITW': ['Illinois Tool Works'],
    'IR': ['Ingersoll Rand'],
    'DOV': ['Dover'],
    'SWK': ['Stanley Black & Decker', 'Stanley', 'DeWalt'],
    'CMI': ['Cummins'],
    'PCAR': ['Paccar', 'Kenworth', 'Peterbilt'],
    'TT': ['Trane Technologies', 'Trane'],
    'CARR': ['Carrier'],
    'OTIS': ['Otis'],
    'JCI': ['Johnson Controls'],
    'LII': ['Lennox'],
    'FDX': ['FedEx'],
    'UPS': ['UPS', 'United Parcel'],
    'UNP': ['Union Pacific'],
    'CSX': ['CSX'],
    'NSC': ['Norfolk Southern'],
    'DAL': ['Delta', 'Delta Airlines'],
    'UAL': ['United Airlines'],
    'AAL': ['American Airlines'],
    'LUV': ['Southwest', 'Southwest Airlines'],
    'ALK': ['Alaska Airlines'],
    'JBLU': ['JetBlue'],
    'WM': ['Waste Management'],
    'RSG': ['Republic Services'],
    'WCN': ['Waste Connections'],
    'GWW': ['Grainger'],
    'FAST': ['Fastenal'],
    'URI': ['United Rentals'],

    # ==================== US ENERGY ====================
    'XOM': ['Exxon', 'ExxonMobil'],
    'CVX': ['Chevron'],
    'COP': ['ConocoPhillips', 'Conoco'],
    'EOG': ['EOG'],
    'SLB': ['Schlumberger', 'SLB'],
    'OXY': ['Occidental'],
    'MPC': ['Marathon Petroleum'],
    'VLO': ['Valero'],
    'PSX': ['Phillips 66'],
    'PXD': ['Pioneer Natural'],
    'DVN': ['Devon Energy', 'Devon'],
    'FANG': ['Diamondback'],
    'HES': ['Hess'],
    'HAL': ['Halliburton'],
    'BKR': ['Baker Hughes'],
    'KMI': ['Kinder Morgan'],
    'WMB': ['Williams Companies', 'Williams'],
    'OKE': ['ONEOK'],
    'ET': ['Energy Transfer'],
    'EPD': ['Enterprise Products'],
    'LNG': ['Cheniere'],

    # ==================== US UTILITIES & REITS ====================
    'NEE': ['NextEra', 'NextEra Energy'],
    'DUK': ['Duke Energy', 'Duke'],
    'SO': ['Southern Company', 'Southern'],
    'D': ['Dominion', 'Dominion Energy'],
    'AEP': ['American Electric Power', 'AEP'],
    'EXC': ['Exelon'],
    'SRE': ['Sempra'],
    'XEL': ['Xcel Energy', 'Xcel'],
    'ED': ['Consolidated Edison', 'ConEd'],
    'WEC': ['WEC Energy'],
    'ES': ['Eversource'],
    'AWK': ['American Water'],
    'AMT': ['American Tower'],
    'CCI': ['Crown Castle'],
    'SBAC': ['SBA Communications'],
    'PLD': ['Prologis'],
    'EQIX': ['Equinix'],
    'DLR': ['Digital Realty'],
    'PSA': ['Public Storage'],
    'EXR': ['Extra Space Storage'],
    'AVB': ['AvalonBay'],
    'EQR': ['Equity Residential'],
    'MAA': ['Mid-America Apartment'],
    'UDR': ['UDR'],
    'SPG': ['Simon Property'],
    'O': ['Realty Income'],
    'VICI': ['VICI Properties'],
    'WELL': ['Welltower'],
    'VTR': ['Ventas'],
    'ARE': ['Alexandria Real Estate'],
    'BXP': ['Boston Properties'],

    # ==================== US MATERIALS ====================
    'LIN': ['Linde'],
    'APD': ['Air Products'],
    'SHW': ['Sherwin-Williams', 'Sherwin Williams'],
    'ECL': ['Ecolab'],
    'DD': ['DuPont'],
    'DOW': ['Dow'],
    'LYB': ['LyondellBasell', 'Lyondell'],
    'PPG': ['PPG'],
    'NEM': ['Newmont'],
    'FCX': ['Freeport-McMoRan', 'Freeport'],
    'NUE': ['Nucor'],
    'STLD': ['Steel Dynamics'],
    'CF': ['CF Industries'],
    'MOS': ['Mosaic'],
    'ALB': ['Albemarle'],
    'EMN': ['Eastman Chemical', 'Eastman'],
    'CE': ['Celanese'],
    'IFF': ['IFF', 'International Flavors'],
    'IP': ['International Paper'],
    'PKG': ['Packaging Corp'],
    'AVY': ['Avery Dennison'],
    'BALL': ['Ball Corp', 'Ball'],
    'AMCR': ['Amcor'],

    # ==================== US TELECOM ====================
    'T': ['AT&T'],
    'VZ': ['Verizon'],
    'TMUS': ['T-Mobile'],
    'CHTR': ['Charter', 'Spectrum'],

    # ==================== EUROPEAN STOCKS ====================
    # Technology
    'ASML': ['ASML', 'EUV', 'lithography'],
    'SAP': ['SAP'],
    'ERIC': ['Ericsson'],
    'NOK': ['Nokia'],
    'STM': ['STMicroelectronics', 'STMicro'],
    'IFNNY': ['Infineon'],
    'CAP': ['Capgemini'],
    'DAST': ['Dassault Systemes', 'Dassault'],

    # Finance
    'HSBC': ['HSBC'],
    'BCS': ['Barclays'],
    'LYG': ['Lloyds', 'Lloyds Bank'],
    'NWG': ['NatWest'],
    'DB': ['Deutsche Bank'],
    'UBS': ['UBS'],
    'CS': ['Credit Suisse'],
    'ING': ['ING'],
    'BNPQY': ['BNP Paribas', 'BNP'],
    'SCGLY': ['Societe Generale'],
    'SAN': ['Santander'],
    'BBVA': ['BBVA'],
    'UNCRY': ['UniCredit'],
    'ISP': ['Intesa Sanpaolo', 'Intesa'],
    'AXA': ['AXA'],
    'ALIZY': ['Allianz'],
    'MUV2': ['Munich Re'],
    'ZURN': ['Zurich Insurance', 'Zurich'],

    # Healthcare & Pharma
    'NVS': ['Novartis'],
    'ROG': ['Roche'],
    'RHHBY': ['Roche'],
    'AZN': ['AstraZeneca'],
    'GSK': ['GSK', 'GlaxoSmithKline'],
    'SNY': ['Sanofi'],
    'NVO': ['Novo Nordisk', 'Ozempic', 'Wegovy'],
    'BAYRY': ['Bayer'],
    'ELAN': ['Elanco'],

    # Consumer
    'NSRGY': ['Nestle', 'Nestlé'],
    'NESN': ['Nestle', 'Nestlé'],
    'UL': ['Unilever'],
    'DEO': ['Diageo'],
    'BUD': ['AB InBev', 'Anheuser-Busch', 'Budweiser'],
    'LVMUY': ['LVMH', 'Louis Vuitton', 'Moet', 'Hennessy', 'Bernard Arnault', 'Dior', 'Sephora', 'Tiffany', 'Bulgari', 'Fendi', 'Givenchy', 'Kenzo', 'Loewe', 'Celine', 'luxury stocks', 'French luxury'],
    'MC': ['LVMH', 'Louis Vuitton', 'Moet', 'Hennessy', 'Bernard Arnault', 'Dior', 'Sephora', 'Tiffany', 'Bulgari', 'Fendi', 'Givenchy', 'Kenzo', 'Loewe', 'Celine', 'luxury stocks', 'French luxury'],
    'PPRUY': ['Kering', 'Gucci', 'Saint Laurent', 'YSL', 'Bottega Veneta', 'Balenciaga', 'Alexander McQueen', 'François-Henri Pinault', 'luxury stocks', 'French luxury'],
    'KER': ['Kering', 'Gucci', 'Saint Laurent', 'YSL', 'Bottega Veneta', 'Balenciaga', 'Alexander McQueen', 'François-Henri Pinault', 'luxury stocks', 'French luxury'],
    'HESAY': ['Hermes', 'Hermès', 'Birkin', 'Kelly bag', 'luxury stocks', 'French luxury'],
    'RMS': ['Hermes', 'Hermès', 'Birkin', 'Kelly bag', 'luxury stocks', 'French luxury'],
    'CFR': ['Richemont', 'Cartier', 'Van Cleef', 'Montblanc', 'IWC', 'Jaeger-LeCoultre', 'Piaget', 'Vacheron Constantin', 'luxury stocks', 'Swiss luxury'],
    'ADDYY': ['Adidas'],
    'ADS': ['Adidas'],
    'PMMAF': ['Philip Morris'],
    'LRLCY': ['L\'Oreal', 'L\'Oréal', 'Loreal'],
    'OR': ['L\'Oreal', 'L\'Oréal', 'Loreal'],
    'DANOY': ['Danone'],

    # Industrial
    'SIEGY': ['Siemens'],
    'SIE': ['Siemens'],
    'ABB': ['ABB'],
    'ATLKY': ['Atlas Copco'],
    'VOLVY': ['Volvo'],
    'SCHN': ['Schneider Electric', 'Schneider'],
    'LEGIF': ['Legrand'],
    'SBGSY': ['Schneider Electric'],
    'ALIZF': ['Air Liquide'],
    'AI': ['Air Liquide'],
    'VWAGY': ['Volkswagen', 'VW', 'Audi', 'Porsche'],
    'VOW3': ['Volkswagen', 'VW'],
    'BAMXF': ['BMW'],
    'BMW': ['BMW', 'Mini', 'Rolls-Royce Motors'],
    'DDAIF': ['Mercedes-Benz', 'Mercedes', 'Daimler'],
    'MBG': ['Mercedes-Benz', 'Mercedes'],
    'RACE': ['Ferrari'],
    'POAHY': ['Porsche'],
    'P911': ['Porsche'],
    'RNLSY': ['Renault'],
    'RNO': ['Renault'],
    'STLA': ['Stellantis', 'Peugeot', 'Citroen', 'Fiat', 'Jeep'],
    'EADSY': ['Airbus'],
    'AIR': ['Airbus'],
    'SAFRY': ['Safran'],
    'SAF': ['Safran'],
    'RYCEY': ['Rolls-Royce'],
    'RR': ['Rolls-Royce'],
    'BA.L': ['BAE Systems', 'BAE'],

    # Energy
    'SHEL': ['Shell'],
    'BP': ['BP', 'British Petroleum'],
    'TTE': ['TotalEnergies', 'Total'],
    'EQNR': ['Equinor'],
    'ENI': ['ENI'],
    'REPSOL': ['Repsol'],
    'IBDRY': ['Iberdrola'],
    'IBE': ['Iberdrola'],
    'ENGI': ['Engie'],
    'ENEL': ['Enel'],
    'ORSTED': ['Orsted', 'Ørsted'],

    # Telecom
    'VOD': ['Vodafone'],
    'DTEGY': ['Deutsche Telekom', 'T-Mobile'],
    'DTE': ['Deutsche Telekom'],
    'ORAN': ['Orange'],
    'TEF': ['Telefonica', 'Telefónica'],

    # Materials & Mining
    'RIO': ['Rio Tinto'],
    'BHP': ['BHP', 'BHP Billiton'],
    'VALE': ['Vale'],
    'GLNCY': ['Glencore'],
    'GLEN': ['Glencore'],
    'AAL.L': ['Anglo American'],
    'MT': ['ArcelorMittal'],
    'BASFY': ['BASF'],
    'BAS': ['BASF'],

    # Other European
    'RELX': ['RELX', 'Reed Elsevier'],
    'WPP': ['WPP'],
    'SPOT': ['Spotify'],
    'NXPI': ['NXP', 'NXP Semiconductors'],

    # ==================== MORE US STOCKS ====================
    # Tech & Software
    'INTU': ['Intuit', 'TurboTax', 'QuickBooks'],
    'ADP': ['ADP', 'Automatic Data Processing'],
    'PAYX': ['Paychex'],
    'CDNS': ['Cadence'],
    'SNPS': ['Synopsys'],
    'ANSS': ['Ansys'],
    'CTSH': ['Cognizant'],
    'ACN': ['Accenture'],
    'IT': ['Gartner'],
    'EPAM': ['EPAM'],
    'GDDY': ['GoDaddy'],
    'WDAY': ['Workday'],
    'VEEV': ['Veeva'],
    'SPLK': ['Splunk'],
    'TEAM': ['Atlassian'],
    'MDB': ['MongoDB'],
    'ESTC': ['Elastic'],
    'OKTA': ['Okta'],
    'HUBS': ['HubSpot'],
    'TTD': ['Trade Desk'],
    'ROKU': ['Roku'],
    'PINS': ['Pinterest'],
    'SNAP': ['Snap', 'Snapchat'],
    'TWTR': ['Twitter', 'X'],
    'RBLX': ['Roblox'],
    'U': ['Unity'],
    'PATH': ['UiPath'],
    'AI': ['C3.ai'],
    'CFLT': ['Confluent'],
    'DOCN': ['DigitalOcean'],
    'BILL': ['Bill.com'],
    'AFRM': ['Affirm'],
    'SOFI': ['SoFi'],
    'HOOD': ['Robinhood'],
    'COIN': ['Coinbase'],
    'MARA': ['Marathon Digital'],
    'RIOT': ['Riot Platforms'],
    'MSTR': ['MicroStrategy', 'Michael Saylor'],
    'SMCI': ['Super Micro', 'Supermicro'],
    'ARM': ['ARM', 'Arm Holdings'],
    'MRVL': ['Marvell'],
    'ON': ['ON Semiconductor', 'onsemi'],
    'SWKS': ['Skyworks'],
    'QRVO': ['Qorvo'],
    'MPWR': ['Monolithic Power'],
    'ALGN': ['Align Technology', 'Invisalign'],
    'ILMN': ['Illumina'],
    'EXAS': ['Exact Sciences'],
    'TECH': ['Bio-Techne'],
    'HOLX': ['Hologic'],
    'PODD': ['Insulet', 'Omnipod'],
    'TER': ['Teradyne'],
    'KEYS': ['Keysight'],
    'ZBRA': ['Zebra Technologies'],
    'TRMB': ['Trimble'],
    'FICO': ['FICO', 'Fair Isaac'],
    'VRSN': ['VeriSign'],
    'AKAM': ['Akamai'],
    'FFIV': ['F5'],
    'JNPR': ['Juniper'],
    'NTAP': ['NetApp'],
    'WDC': ['Western Digital'],
    'STX': ['Seagate'],
    'PSTG': ['Pure Storage'],

    # More Finance
    'SIVB': ['Silicon Valley Bank', 'SVB'],
    'FRC': ['First Republic'],
    'WAL': ['Western Alliance'],
    'ZION': ['Zions'],
    'CFG': ['Citizens Financial'],
    'FITB': ['Fifth Third'],
    'HBAN': ['Huntington'],
    'KEY': ['KeyCorp', 'KeyBank'],
    'MTB': ['M&T Bank'],
    'RF': ['Regions Financial'],
    'NDAQ': ['Nasdaq'],
    'CBOE': ['Cboe'],
    'MKTX': ['MarketAxess'],
    'TW': ['Tradeweb'],
    'LPLA': ['LPL Financial'],
    'RJF': ['Raymond James'],
    'SEIC': ['SEI Investments'],
    'AMG': ['Affiliated Managers'],
    'TROW': ['T. Rowe Price'],
    'BEN': ['Franklin Templeton', 'Franklin Resources'],
    'IVZ': ['Invesco'],
    'JHG': ['Janus Henderson'],
    'NTRS': ['Northern Trust'],
    'WRB': ['Berkley'],
    'L': ['Loews'],
    'HIG': ['Hartford'],
    'CINF': ['Cincinnati Financial'],
    'RE': ['Everest Re'],
    'RNR': ['RenaissanceRe'],
    'ACGL': ['Arch Capital'],
    'AJG': ['Arthur J. Gallagher'],
    'MMC': ['Marsh McLennan', 'Marsh'],
    'AON': ['Aon'],
    'WTW': ['Willis Towers Watson'],
    'BRO': ['Brown & Brown'],

    # More Healthcare
    'HCA': ['HCA Healthcare'],
    'THC': ['Tenet Healthcare'],
    'UHS': ['Universal Health Services'],
    'DVA': ['DaVita'],
    'EHC': ['Encompass Health'],
    'GEHC': ['GE Healthcare'],
    'HOLX': ['Hologic'],
    'COO': ['CooperCompanies'],
    'TFX': ['Teleflex'],
    'PEN': ['Penumbra'],
    'NUVA': ['NuVasive'],
    'GMED': ['Globus Medical'],
    'XRAY': ['Dentsply Sirona'],
    'ALGN': ['Align', 'Invisalign'],
    'HSIC': ['Henry Schein'],
    'PDCO': ['Patterson'],
    'CRL': ['Charles River'],
    'ICLR': ['ICON'],
    'MEDP': ['Medpace'],
    'PRGO': ['Perrigo'],
    'VTRS': ['Viatris'],
    'TAK': ['Takeda'],
    'ZTS': ['Zoetis'],

    # More Consumer
    'MNST': ['Monster Beverage', 'Monster Energy'],
    'CELH': ['Celsius'],
    'SAM': ['Boston Beer', 'Samuel Adams'],
    'STZ': ['Constellation Brands', 'Corona', 'Modelo'],
    'BF.B': ['Brown-Forman', 'Jack Daniels'],
    'SYY': ['Sysco'],
    'USFD': ['US Foods'],
    'PFGC': ['Performance Food'],
    'CASY': ['Casey\'s'],
    'MUSA': ['Murphy USA'],
    'DINO': ['HF Sinclair'],
    'CZR': ['Caesars'],
    'PENN': ['Penn Entertainment'],
    'DKNG': ['DraftKings'],
    'CHDN': ['Churchill Downs'],
    'SIX': ['Six Flags'],
    'FUN': ['Cedar Fair'],
    'SEAS': ['SeaWorld'],
    'PLNT': ['Planet Fitness'],
    'POOL': ['Pool Corp'],
    'SITE': ['SiteOne'],
    'TSCO': ['Tractor Supply'],
    'WSM': ['Williams-Sonoma'],
    'RH': ['RH', 'Restoration Hardware'],
    'W': ['Wayfair'],
    'ETSY': ['Etsy'],
    'EBAY': ['eBay'],
    'CHWY': ['Chewy'],
    'CVNA': ['Carvana'],
    'CPNG': ['Coupang'],
    'SE': ['Sea Limited', 'Shopee', 'Garena'],
    'MELI': ['MercadoLibre'],
    'GLOB': ['Globant'],
    'GRAB': ['Grab'],
    'BABA': ['Alibaba'],
    'JD': ['JD.com'],
    'PDD': ['PDD', 'Pinduoduo', 'Temu'],
    'BIDU': ['Baidu'],
    'NTES': ['NetEase'],
    'TCEHY': ['Tencent'],
    'TME': ['Tencent Music'],
    'BILI': ['Bilibili'],
    'IQ': ['iQiyi'],
    'VIPS': ['Vipshop'],
    'TAL': ['TAL Education'],
    'EDU': ['New Oriental'],

    # More Industrial
    'GNRC': ['Generac'],
    'AME': ['Ametek'],
    'ROP': ['Roper'],
    'IEX': ['IDEX'],
    'NDSN': ['Nordson'],
    'AAON': ['AAON'],
    'MIDD': ['Middleby'],
    'FBIN': ['Fortune Brands'],
    'MAS': ['Masco'],
    'ALLE': ['Allegion'],
    'AOS': ['A.O. Smith'],
    'SNA': ['Snap-on'],
    'TTC': ['Toro'],
    'BC': ['Brunswick'],
    'HOG': ['Harley-Davidson'],
    'PII': ['Polaris'],
    'THO': ['Thor Industries'],
    'WGO': ['Winnebago'],
    'OSK': ['Oshkosh'],
    'AGCO': ['AGCO'],
    'CNH': ['CNH Industrial'],
    'TEX': ['Terex'],
    'HWM': ['Howmet'],
    'ATI': ['ATI'],
    'CRS': ['Carpenter Technology'],
    'CLF': ['Cleveland-Cliffs'],
    'X': ['U.S. Steel'],
    'AA': ['Alcoa'],
    'CENX': ['Century Aluminum'],
    'RS': ['Reliance Steel'],
    'STLD': ['Steel Dynamics'],
    'BLDR': ['Builders FirstSource'],
    'MLM': ['Martin Marietta'],
    'VMC': ['Vulcan Materials'],
    'EXP': ['Eagle Materials'],
    'SUM': ['Summit Materials'],
    'OC': ['Owens Corning'],
    'JELD': ['JELD-WEN'],
    'DOOR': ['Masonite'],
    'TREX': ['Trex'],
    'AZEK': ['Azek'],
    'AWI': ['Armstrong World'],
    'FBHS': ['Fortune Brands Home'],
    'MHK': ['Mohawk'],
    'FND': ['Floor & Decor'],
    'LL': ['LL Flooring'],
    'LEG': ['Leggett & Platt'],
    'ETD': ['Ethan Allen'],
    'HNI': ['HNI'],
    'KNL': ['Knoll'],
    'MLKN': ['MillerKnoll', 'Herman Miller'],
    'XYL': ['Xylem'],
    'FELE': ['Franklin Electric'],
    'WTS': ['Watts Water'],
    'PNR': ['Pentair'],
    'RXN': ['Rexnord'],
    'GGG': ['Graco'],
    'FLS': ['Flowserve'],
    'CFX': ['Colfax'],
    'CR': ['Crane'],
    'RBC': ['RBC Bearings'],
    'TKR': ['Timken'],
    'WWD': ['Woodward'],
    'HXL': ['Hexcel'],
    'TDG': ['TransDigm'],
    'HEI': ['HEICO'],
    'MOG.A': ['Moog'],
    'CW': ['Curtiss-Wright'],
    'AXON': ['Axon', 'Taser'],
    'TDY': ['Teledyne'],
    'LDOS': ['Leidos'],
    'SAIC': ['SAIC'],
    'BAH': ['Booz Allen'],
    'CACI': ['CACI'],
    'KTOS': ['Kratos'],
    'PSN': ['Parsons'],
    'J': ['Jacobs'],
    'KBR': ['KBR'],
    'FLR': ['Fluor'],
    'PWR': ['Quanta Services'],
    'EME': ['EMCOR'],
    'MTZ': ['MasTec'],
    'DY': ['Dycom'],
    'PRIM': ['Primoris'],
    'AGX': ['Argan'],
    'GVA': ['Granite Construction'],
    'ROAD': ['Construction Partners'],
    'WERN': ['Werner'],
    'JBHT': ['J.B. Hunt'],
    'KNX': ['Knight-Swift'],
    'ODFL': ['Old Dominion'],
    'SAIA': ['Saia'],
    'XPO': ['XPO'],
    'CHRW': ['C.H. Robinson'],
    'EXPD': ['Expeditors'],
    'HUBG': ['Hub Group'],
    'MATX': ['Matson'],
    'KEX': ['Kirby'],
    'SBLK': ['Star Bulk'],
    'GOGL': ['Golden Ocean'],
    'ZIM': ['ZIM'],
    'SAVE': ['Spirit Airlines'],
    'HA': ['Hawaiian Airlines'],
    'MESA': ['Mesa Air'],
    'SKYW': ['SkyWest'],
    'ALGT': ['Allegiant'],

    # More Energy
    'APA': ['APA', 'Apache'],
    'CTRA': ['Coterra'],
    'MRO': ['Marathon Oil'],
    'MGY': ['Magnolia'],
    'PR': ['Permian Resources'],
    'MTDR': ['Matador'],
    'CHRD': ['Chord Energy'],
    'SM': ['SM Energy'],
    'RRC': ['Range Resources'],
    'AR': ['Antero'],
    'EQT': ['EQT'],
    'SWN': ['Southwestern Energy'],
    'CNX': ['CNX Resources'],
    'CHK': ['Chesapeake'],
    'BTU': ['Peabody'],
    'ARCH': ['Arch Resources'],
    'AMR': ['Alpha Metallurgical'],
    'CEIX': ['CONSOL Energy'],
    'NOV': ['NOV'],
    'CHX': ['ChampionX'],
    'WHD': ['Cactus'],
    'HP': ['Helmerich & Payne'],
    'PTEN': ['Patterson-UTI'],
    'NBR': ['Nabors'],
    'DRQ': ['Dril-Quip'],
    'OII': ['Oceaneering'],
    'TDW': ['Tidewater'],
    'HLX': ['Helix Energy'],
    'CLR': ['Continental Resources'],
    'OVV': ['Ovintiv'],
    'CPE': ['Callon'],
    'PDCE': ['PDC Energy'],
    'TRGP': ['Targa Resources'],
    'WES': ['Western Midstream'],
    'AM': ['Antero Midstream'],
    'HESM': ['Hess Midstream'],
    'MPLX': ['MPLX'],
    'PAA': ['Plains All American'],
    'PAGP': ['Plains GP'],
    'NS': ['NuStar'],
    'DCP': ['DCP Midstream'],
    'ENLC': ['EnLink'],
    'CEQP': ['Crestwood'],
    'SMLP': ['Summit Midstream'],

    # More Utilities
    'CNP': ['CenterPoint'],
    'NI': ['NiSource'],
    'DTE': ['DTE Energy'],
    'CMS': ['CMS Energy'],
    'LNT': ['Alliant Energy'],
    'EVRG': ['Evergy'],
    'ALE': ['Allete'],
    'OGE': ['OGE Energy'],
    'POR': ['Portland General'],
    'IDA': ['Idacorp'],
    'AVA': ['Avista'],
    'NWE': ['NorthWestern'],
    'PNW': ['Pinnacle West'],
    'AEE': ['Ameren'],
    'ETR': ['Entergy'],
    'FE': ['FirstEnergy'],
    'PPL': ['PPL'],
    'AES': ['AES'],
    'VST': ['Vistra'],
    'NRG': ['NRG Energy'],
    'CWEN': ['Clearway Energy'],
    'BEPC': ['Brookfield Renewable'],
    'AQN': ['Algonquin'],
    'AGR': ['Avangrid'],

    # More REITs
    'CBRE': ['CBRE'],
    'JLL': ['JLL', 'Jones Lang LaSalle'],
    'CWK': ['Cushman & Wakefield'],
    'CSGP': ['CoStar'],
    'ZG': ['Zillow'],
    'RDFN': ['Redfin'],
    'OPEN': ['Opendoor'],
    'INVH': ['Invitation Homes'],
    'AMH': ['American Homes'],
    'SUI': ['Sun Communities'],
    'ELS': ['Equity LifeStyle'],
    'REXR': ['Rexford'],
    'FR': ['First Industrial'],
    'STAG': ['STAG Industrial'],
    'TRNO': ['Terreno'],
    'COLD': ['Americold'],
    'LSI': ['Life Storage'],
    'CUBE': ['CubeSmart'],
    'NSA': ['National Storage'],
    'REG': ['Regency Centers'],
    'KIM': ['Kimco'],
    'FRT': ['Federal Realty'],
    'BRX': ['Brixmor'],
    'ROIC': ['Retail Opportunity'],
    'SKT': ['Tanger'],
    'MAC': ['Macerich'],
    'PEI': ['PREIT'],
    'CBL': ['CBL'],
    'WPC': ['W. P. Carey'],
    'NNN': ['National Retail'],
    'ADC': ['Agree Realty'],
    'EPRT': ['Essential Properties'],
    'STOR': ['Store Capital'],
    'SRC': ['Spirit Realty'],
    'GTY': ['Getty Realty'],
    'FCPT': ['Four Corners'],
    'OHI': ['Omega Healthcare'],
    'SBRA': ['Sabra Healthcare'],
    'HR': ['Healthcare Realty'],
    'PEAK': ['Healthpeak'],
    'DOC': ['Physicians Realty'],
    'MPW': ['Medical Properties'],
    'HST': ['Host Hotels'],
    'RLJ': ['RLJ Lodging'],
    'PK': ['Park Hotels'],
    'SHO': ['Sunstone'],
    'XHR': ['Xenia Hotels'],
    'DRH': ['DiamondRock'],
    'APLE': ['Apple Hospitality'],
    'INN': ['Summit Hotel'],
    'HT': ['Hersha'],
    'PEB': ['Pebblebrook'],
    'KRC': ['Kilroy'],
    'HIW': ['Highwoods'],
    'CUZ': ['Cousins'],
    'DEI': ['Douglas Emmett'],
    'PDM': ['Piedmont'],
    'OFC': ['Corporate Office'],
    'CLI': ['Mack-Cali'],
    'SLG': ['SL Green'],
    'VNO': ['Vornado'],
    'PGRE': ['Paramount'],
    'ESRT': ['Empire State Realty'],
    'NYC': ['New York Mortgage'],
    'NLY': ['Annaly'],
    'AGNC': ['AGNC'],
    'STWD': ['Starwood Property'],
    'BXMT': ['Blackstone Mortgage'],
    'LADR': ['Ladder Capital'],
    'GPMT': ['Granite Point'],
    'ARI': ['Apollo Commercial'],
    'KREF': ['KKR Real Estate'],

    # ==================== MORE EUROPEAN STOCKS ====================
    # UK
    'LSEG': ['London Stock Exchange', 'LSEG'],
    'III': ['3i Group'],
    'LAND.L': ['Land Securities'],
    'BLND': ['British Land'],
    'SGRO': ['Segro'],
    'UTG': ['Unite Group'],
    'PSN.L': ['Persimmon'],
    'BDEV': ['Barratt'],
    'TW.L': ['Taylor Wimpey'],
    'RMV': ['Rightmove'],
    'AUTO': ['Auto Trader'],
    'JET': ['Just Eat'],
    'OCDO': ['Ocado'],
    'TSCO.L': ['Tesco'],
    'SBRY': ['Sainsbury'],
    'MKS': ['Marks & Spencer', 'M&S'],
    'KGF': ['Kingfisher'],
    'JD.L': ['JD Sports'],
    'FRAS': ['Frasers'],
    'NXT': ['Next'],
    'ABF': ['Associated British Foods', 'Primark'],
    'PSON': ['Pearson'],
    'ITV': ['ITV'],
    'REL.L': ['RELX'],
    'INF': ['Informa'],
    'RTO': ['Rentokil'],
    'EZJ': ['easyJet'],
    'IAG': ['IAG', 'British Airways', 'Iberia'],
    'WIZ': ['Wizz Air'],
    'SSE.L': ['SSE'],
    'NG.L': ['National Grid'],
    'CNA': ['Centrica'],
    'SVT': ['Severn Trent'],
    'UU': ['United Utilities'],
    'PNN': ['Pennon'],
    'DCC': ['DCC'],
    'EXPN.L': ['Experian'],
    'HLMA': ['Halma'],
    'SMIN': ['Smiths Group'],
    'IMI': ['IMI'],
    'RR.L': ['Rolls-Royce'],
    'BA.L': ['BAE Systems'],
    'SMDS': ['Smith & Nephew'],
    'SN.L': ['Smith & Nephew'],
    'HIK': ['Hikma'],
    'INDV': ['Indivior'],
    'SHP': ['Shire'],
    'AHT.L': ['Ashtead'],
    'BKG': ['Berkeley'],
    'CRH.L': ['CRH'],
    'DGE.L': ['Diageo'],
    'RKT.L': ['Reckitt'],
    'ULVR.L': ['Unilever'],
    'BATS.L': ['British American Tobacco', 'BAT'],
    'IMB': ['Imperial Brands'],

    # Germany
    'SAP.DE': ['SAP'],
    'SIE.DE': ['Siemens'],
    'ALV.DE': ['Allianz'],
    'DTE.DE': ['Deutsche Telekom'],
    'BAYN.DE': ['Bayer'],
    'BAS.DE': ['BASF'],
    'BMW.DE': ['BMW'],
    'MBG.DE': ['Mercedes-Benz'],
    'VOW3.DE': ['Volkswagen', 'VW'],
    'P911.DE': ['Porsche'],
    'PAH3.DE': ['Porsche Holding'],
    'ADS.DE': ['Adidas'],
    'HEN3.DE': ['Henkel'],
    'BEI.DE': ['Beiersdorf', 'Nivea'],
    'DB1.DE': ['Deutsche Boerse'],
    'DBK.DE': ['Deutsche Bank'],
    'CBK.DE': ['Commerzbank'],
    'MUV2.DE': ['Munich Re'],
    'HNR1.DE': ['Hannover Re'],
    'FRE.DE': ['Fresenius'],
    'FME.DE': ['Fresenius Medical'],
    'MRK.DE': ['Merck KGaA'],
    'SHL.DE': ['Siemens Healthineers'],
    'IFX.DE': ['Infineon'],
    'ENR.DE': ['Siemens Energy'],
    'RWE.DE': ['RWE'],
    'EOAN.DE': ['E.ON'],
    'DPW.DE': ['DHL', 'Deutsche Post'],
    'LHA.DE': ['Lufthansa'],
    'TUI1.DE': ['TUI'],
    'HFG.DE': ['HelloFresh'],
    'ZAL.DE': ['Zalando'],
    'PUM.DE': ['Puma'],
    'BOSS.DE': ['Hugo Boss'],
    'CON.DE': ['Continental'],
    'SY1.DE': ['Symrise'],
    '1COV.DE': ['Covestro'],
    'EVK.DE': ['Evonik'],
    'WCH.DE': ['Wacker Chemie'],
    'MTX.DE': ['MTU Aero'],
    'AIR.DE': ['Airbus'],
    'RHM.DE': ['Rheinmetall'],
    'G1A.DE': ['GEA'],
    'KCO.DE': ['Kloeckner'],
    'DHER.DE': ['Delivery Hero'],
    'WDI.DE': ['Wirecard'],
    'QIA.DE': ['Qiagen'],
    'AFX.DE': ['Carl Zeiss'],
    'LEO.DE': ['LPKF'],
    'SRT3.DE': ['Sartorius'],
    'EVT.DE': ['Evotec'],

    # France
    'MC.PA': ['LVMH', 'Louis Vuitton'],
    'OR.PA': ['L\'Oreal'],
    'RMS.PA': ['Hermes'],
    'KER.PA': ['Kering', 'Gucci'],
    'TTE.PA': ['TotalEnergies'],
    'SAN.PA': ['Sanofi'],
    'AI.PA': ['Air Liquide'],
    'AIR.PA': ['Airbus'],
    'SAF.PA': ['Safran'],
    'SU.PA': ['Schneider Electric'],
    'DSY.PA': ['Dassault Systemes'],
    'CAP.PA': ['Capgemini'],
    'STM.PA': ['STMicroelectronics'],
    'BNP.PA': ['BNP Paribas'],
    'GLE.PA': ['Societe Generale'],
    'ACA.PA': ['Credit Agricole'],
    'CS.PA': ['AXA'],
    'ENGI.PA': ['Engie'],
    'VIE.PA': ['Veolia'],
    'DG.PA': ['Vinci'],
    'BN.PA': ['Danone'],
    'RI.PA': ['Pernod Ricard'],
    'SW.PA': ['Sodexo'],
    'PUB.PA': ['Publicis'],
    'VIV.PA': ['Vivendi'],
    'ORA.PA': ['Orange'],
    'STLA.PA': ['Stellantis'],
    'RNO.PA': ['Renault'],
    'ML.PA': ['Michelin'],
    'HO.PA': ['Thales'],
    'LR.PA': ['Legrand'],
    'SGO.PA': ['Saint-Gobain'],
    'EN.PA': ['Bouygues'],
    'ATO.PA': ['Atos'],
    'TEP.PA': ['Teleperformance'],
    'FGR.PA': ['Eiffage'],
    'EDEN.PA': ['Edenred'],
    'ALO.PA': ['Alstom'],
    'GET.PA': ['Getlink'],
    'ERA.PA': ['Eramet'],
    'MT.PA': ['ArcelorMittal'],
    'UBI.PA': ['Ubisoft'],
    'WLN.PA': ['Worldline'],
    'RF.PA': ['Eurofins'],
    'BVI.PA': ['Bureau Veritas'],
    'ERF.PA': ['Eurazeo'],
    'NK.PA': ['Imerys'],
    'ILD.PA': ['Iliad'],
    'FTI.PA': ['TechnipFMC'],
    'CGG.PA': ['CGG'],
    'VK.PA': ['Vallourec'],
    'SESG.PA': ['SES'],
    'IPN.PA': ['Ipsen'],
    'COV.PA': ['Covivio'],
    'GFC.PA': ['Gecina'],
    'URW.PA': ['Unibail-Rodamco-Westfield'],
    'KOF.PA': ['Klepierre'],

    # Netherlands
    'ASML.AS': ['ASML'],
    'PHIA.AS': ['Philips'],
    'INGA.AS': ['ING'],
    'ABN.AS': ['ABN AMRO'],
    'NN.AS': ['NN Group'],
    'AGN.AS': ['Aegon'],
    'HEIA.AS': ['Heineken'],
    'AD.AS': ['Ahold Delhaize', 'Albert Heijn'],
    'UNA.AS': ['Unilever'],
    'AKZA.AS': ['AkzoNobel'],
    'DSM.AS': ['DSM'],
    'WKL.AS': ['Wolters Kluwer'],
    'RAND.AS': ['Randstad'],
    'LIGHT.AS': ['Signify'],
    'IMCD.AS': ['IMCD'],
    'ASM.AS': ['ASM International'],
    'BESI.AS': ['BE Semiconductor'],
    'ADYEN.AS': ['Adyen'],
    'PRX.AS': ['Prosus'],
    'JDEP.AS': ['JDE Peet\'s'],
    'EXO.AS': ['Exor'],
    'FLOW.AS': ['Flow Traders'],
    'TKWY.AS': ['Just Eat Takeaway'],

    # Switzerland
    'NESN.SW': ['Nestle'],
    'ROG.SW': ['Roche'],
    'NOVN.SW': ['Novartis'],
    'UBSG.SW': ['UBS'],
    'CSGN.SW': ['Credit Suisse'],
    'ZURN.SW': ['Zurich Insurance'],
    'SREN.SW': ['Swiss Re'],
    'ABBN.SW': ['ABB'],
    'GIVN.SW': ['Givaudan'],
    'SIKA.SW': ['Sika'],
    'GEBN.SW': ['Geberit'],
    'SOON.SW': ['Sonova'],
    'LONN.SW': ['Lonza'],
    'STMN.SW': ['Straumann'],
    'ALC.SW': ['Alcon'],
    'CFR.SW': ['Richemont'],
    'UHR.SW': ['Swatch'],
    'SLHN.SW': ['Swiss Life'],
    'BALN.SW': ['Baloise'],
    'HOLN.SW': ['Holcim'],
    'SCMN.SW': ['Swisscom'],
    'PGHN.SW': ['Partners Group'],
    'TEMN.SW': ['Temenos'],
    'LOGN.SW': ['Logitech'],
    'AMS.SW': ['AMS-OSRAM'],
    'VAT.SW': ['VAT Group'],
    'SGSN.SW': ['SGS'],
    'BARN.SW': ['Barry Callebaut'],
    'LHN.SW': ['LafargeHolcim'],
    'SGKN.SW': ['SGS'],
    'KNIN.SW': ['Kuehne Nagel'],
    'DUFN.SW': ['Dufry'],
    'CLN.SW': ['Clariant'],
    'ADEN.SW': ['Adecco'],
    'VACN.SW': ['VAT'],
    'SIGN.SW': ['SIG'],

    # Spain
    'SAN.MC': ['Santander'],
    'BBVA.MC': ['BBVA'],
    'CABK.MC': ['CaixaBank'],
    'SAB.MC': ['Sabadell'],
    'MAP.MC': ['Mapfre'],
    'TEF.MC': ['Telefonica'],
    'IBE.MC': ['Iberdrola'],
    'ENG.MC': ['Enagas'],
    'REE.MC': ['Red Electrica'],
    'ELE.MC': ['Endesa'],
    'NTGY.MC': ['Naturgy'],
    'REP.MC': ['Repsol'],
    'ITX.MC': ['Inditex', 'Zara'],
    'FER.MC': ['Ferrovial'],
    'ACS.MC': ['ACS'],
    'ACX.MC': ['Acerinox'],
    'AMS.MC': ['Amadeus'],
    'AENA.MC': ['Aena'],
    'IAG.MC': ['IAG', 'Iberia'],
    'MEL.MC': ['Melia'],
    'GRF.MC': ['Grifols'],
    'ALM.MC': ['Almirall'],
    'PHM.MC': ['PharmaMar'],
    'CLNX.MC': ['Cellnex'],
    'COL.MC': ['Inmobiliaria Colonial'],
    'MRL.MC': ['Merlin Properties'],
    'LOG.MC': ['Logista'],
    'VIS.MC': ['Viscofan'],
    'CIE.MC': ['CIE Automotive'],
    'SGRE.MC': ['Siemens Gamesa'],
    'SOL.MC': ['Solaria'],

    # Italy
    'ENEL.MI': ['Enel'],
    'ENI.MI': ['Eni'],
    'ISP.MI': ['Intesa Sanpaolo'],
    'UCG.MI': ['UniCredit'],
    'BAMI.MI': ['Banco BPM'],
    'RACE.MI': ['Ferrari'],
    'STLA.MI': ['Stellantis'],
    'TEN.MI': ['Tenaris'],
    'LDO.MI': ['Leonardo'],
    'PRY.MI': ['Prysmian'],
    'SRG.MI': ['Snam'],
    'TRN.MI': ['Terna'],
    'ATL.MI': ['Atlantia'],
    'AMP.MI': ['Amplifon'],
    'REC.MI': ['Recordati'],
    'DIA.MI': ['DiaSorin'],
    'MONC.MI': ['Moncler'],
    'CPR.MI': ['Campari'],
    'G.MI': ['Generali'],
    'MB.MI': ['Mediobanca'],
    'SPM.MI': ['Saipem'],
    'A2A.MI': ['A2A'],
    'POSTE.MI': ['Poste Italiane'],
    'TIT.MI': ['Telecom Italia'],
    'HER.MI': ['Hera'],
    'IREN.MI': ['Iren'],
    'BMED.MI': ['Banca Mediolanum'],
    'FBK.MI': ['FinecoBank'],
    'BPE.MI': ['BPER Banca'],
    'BGN.MI': ['Brembo'],
    'CNHI.MI': ['CNH Industrial'],
    'PIRC.MI': ['Pirelli'],
    'IP.MI': ['Interpump'],
    'RMS.MI': ['Reply'],

    # Nordic
    'NOVO-B.CO': ['Novo Nordisk'],
    'MAERSK-B.CO': ['Maersk'],
    'CARL-B.CO': ['Carlsberg'],
    'DSV.CO': ['DSV'],
    'VWS.CO': ['Vestas'],
    'ORSTED.CO': ['Orsted'],
    'COLO-B.CO': ['Coloplast'],
    'GMAB.CO': ['Genmab'],
    'CHR.CO': ['Chr. Hansen'],
    'NZYM-B.CO': ['Novozymes'],
    'DEMANT.CO': ['Demant'],
    'GN.CO': ['GN Store Nord'],
    'PNDORA.CO': ['Pandora'],
    'FLS.CO': ['FLSmidth'],
    'DNORD.CO': ['D/S Norden'],
    'TRYG.CO': ['Tryg'],
    'TOP.CO': ['Topdanmark'],
    'RBREW.CO': ['Royal Unibrew'],
    'NDA-FI.HE': ['Nordea'],
    'SAMPO.HE': ['Sampo'],
    'NOKIA.HE': ['Nokia'],
    'FORTUM.HE': ['Fortum'],
    'NESTE.HE': ['Neste'],
    'UPM.HE': ['UPM'],
    'STORA.HE': ['Stora Enso'],
    'METSO.HE': ['Metso'],
    'KONE.HE': ['Kone'],
    'WRTBV.HE': ['Wartsila'],
    'KNEBV.HE': ['Konecranes'],
    'ELISA.HE': ['Elisa'],
    'TELIA.ST': ['Telia'],
    'ERIC-B.ST': ['Ericsson'],
    'VOLV-B.ST': ['Volvo'],
    'SKA-B.ST': ['Skanska'],
    'SCA-B.ST': ['SCA'],
    'ESSITY-B.ST': ['Essity'],
    'HM-B.ST': ['H&M', 'Hennes & Mauritz'],
    'ATCO-A.ST': ['Atlas Copco'],
    'SAND.ST': ['Sandvik'],
    'ABB.ST': ['ABB'],
    'SKF-B.ST': ['SKF'],
    'ALFA.ST': ['Alfa Laval'],
    'ASSA-B.ST': ['Assa Abloy'],
    'NDA-SE.ST': ['Nordea'],
    'SEB-A.ST': ['SEB'],
    'SWED-A.ST': ['Swedbank'],
    'SHB-A.ST': ['Handelsbanken'],
    'INVE-B.ST': ['Investor'],
    'EQT.ST': ['EQT'],
    'KINV-B.ST': ['Kinnevik'],
    'SPOT.ST': ['Spotify'],
    'HEXA-B.ST': ['Hexagon'],
    'GETI-B.ST': ['Getinge'],
    'EKTA-B.ST': ['Elekta'],
    'AZN.ST': ['AstraZeneca'],
    'EQNR.OL': ['Equinor'],
    'DNB.OL': ['DNB'],
    'MOWI.OL': ['Mowi'],
    'SALM.OL': ['SalMar'],
    'BAKKA.OL': ['Bakkafrost'],
    'ORK.OL': ['Orkla'],
    'YAR.OL': ['Yara'],
    'NHY.OL': ['Norsk Hydro'],
    'TEL.OL': ['Telenor'],
    'SCHB.OL': ['Schibsted'],
    'AKRBP.OL': ['Aker BP'],
    'AKSO.OL': ['Aker Solutions'],
    'TGS.OL': ['TGS-NOPEC'],
    'SUBC.OL': ['Subsea 7'],
    'FRO.OL': ['Frontline'],
}


def get_uploads_playlist_id(channel_id):
    """Convert channel ID to uploads playlist ID (UC... -> UU...)"""
    if channel_id.startswith('UC'):
        return 'UU' + channel_id[2:]
    return channel_id


def matches_company(title, ticker, company_name=None):
    """
    Check if a video title matches a company.
    Uses company_name as primary keyword, plus any extra keywords defined for the ticker.
    """
    title_upper = title.upper()

    # Check ticker itself
    if ticker.upper() in title_upper:
        return True

    # Check company name (primary keyword)
    if company_name and company_name.upper() in title_upper:
        return True

    # Check extra keywords if defined
    extra = EXTRA_KEYWORDS.get(ticker.upper(), [])
    for kw in extra:
        if kw.upper() in title_upper:
            return True

    return False
