# YouTube News Feed Configuration
# Channel whitelist and company keyword mappings

# Channels to fetch videos from
# Format: { 'channel_id': { 'name': 'Channel Name' } }
# To find channel ID: go to YouTube channel > View Page Source > search "channelId"
YOUTUBE_CHANNELS = {
    'UCfCT7SSFEWyG4th9ZmaGYqQ': {
        'name': 'Joseph Carlson After Hours',
    },
    'UCbta0n8i6Rljh0obO7HzG9A': {
        'name': 'Joseph Carlson',
    },
    'UCrp_UI8XtuYfpiqluWLD7Lw': {
        'name': 'CNBC Television',
    },
    'UCEAZeUIeJs0IjQiqTCdVSIg': {
        'name': 'Yahoo Finance',
    },
}

# Additional keywords for specific companies (optional)
# If a ticker is not in this dict, matching uses the company_name passed from frontend
# Format: { 'TICKER': ['extra_keyword1', 'extra_keyword2', ...] }
EXTRA_KEYWORDS = {
    # ==================== US TECH ====================
    'AAPL': ['Apple', 'iPhone', 'iPad', 'Mac', 'Tim Cook'],
    'MSFT': ['Microsoft', 'Azure', 'Windows', 'Satya Nadella', 'Xbox', 'Copilot'],
    'GOOGL': ['Google', 'Alphabet', 'YouTube', 'Android', 'Sundar Pichai', 'Gemini'],
    'GOOG': ['Google', 'Alphabet', 'YouTube', 'Android', 'Sundar Pichai', 'Gemini'],
    'AMZN': ['Amazon', 'AWS', 'Jeff Bezos', 'Andy Jassy', 'Prime'],
    'META': ['Meta', 'Facebook', 'Instagram', 'WhatsApp', 'Zuckerberg'],
    'NVDA': ['Nvidia', 'Jensen Huang', 'GPU', 'CUDA'],
    'TSLA': ['Tesla', 'Elon Musk', 'Cybertruck', 'Model 3', 'Model Y'],
    'NFLX': ['Netflix'],
    'CRM': ['Salesforce'],
    'ORCL': ['Oracle'],
    'ADBE': ['Adobe', 'Photoshop', 'Creative Cloud'],
    'CSCO': ['Cisco'],
    'INTC': ['Intel', 'Pat Gelsinger'],
    'AMD': ['AMD', 'Lisa Su', 'Ryzen', 'Radeon'],
    'AVGO': ['Broadcom'],
    'QCOM': ['Qualcomm', 'Snapdragon'],
    'TXN': ['Texas Instruments'],
    'MU': ['Micron'],
    'AMAT': ['Applied Materials'],
    'LRCX': ['Lam Research'],
    'KLAC': ['KLA'],
    'ADI': ['Analog Devices'],
    'NOW': ['ServiceNow'],
    'SNOW': ['Snowflake'],
    'PLTR': ['Palantir'],
    'UBER': ['Uber'],
    'LYFT': ['Lyft'],
    'ABNB': ['Airbnb'],
    'SQ': ['Square', 'Block'],
    'PYPL': ['PayPal'],
    'SHOP': ['Shopify'],
    'SPOT': ['Spotify'],
    'ZM': ['Zoom'],
    'DOCU': ['DocuSign'],
    'TWLO': ['Twilio'],
    'NET': ['Cloudflare'],
    'DDOG': ['Datadog'],
    'ZS': ['Zscaler'],
    'CRWD': ['CrowdStrike'],
    'PANW': ['Palo Alto Networks'],
    'FTNT': ['Fortinet'],
    'IBM': ['IBM'],
    'HPQ': ['HP', 'Hewlett-Packard'],
    'HPE': ['Hewlett Packard Enterprise'],
    'DELL': ['Dell'],

    # ==================== US FINANCE ====================
    'JPM': ['JPMorgan', 'JP Morgan', 'Jamie Dimon'],
    'BAC': ['Bank of America', 'BofA'],
    'WFC': ['Wells Fargo'],
    'C': ['Citigroup', 'Citi'],
    'GS': ['Goldman Sachs', 'Goldman'],
    'MS': ['Morgan Stanley'],
    'BLK': ['BlackRock', 'Larry Fink'],
    'SCHW': ['Charles Schwab', 'Schwab'],
    'BX': ['Blackstone'],
    'KKR': ['KKR'],
    'APO': ['Apollo'],
    'V': ['Visa'],
    'MA': ['Mastercard'],
    'AXP': ['American Express', 'Amex'],
    'COF': ['Capital One'],
    'DFS': ['Discover'],
    'USB': ['US Bancorp', 'US Bank'],
    'PNC': ['PNC'],
    'TFC': ['Truist'],
    'BK': ['Bank of New York', 'BNY Mellon'],
    'STT': ['State Street'],
    'AIG': ['AIG'],
    'MET': ['MetLife'],
    'PRU': ['Prudential'],
    'ALL': ['Allstate'],
    'TRV': ['Travelers'],
    'CB': ['Chubb'],
    'AFL': ['Aflac'],
    'PGR': ['Progressive'],
    'CME': ['CME Group'],
    'ICE': ['Intercontinental Exchange'],
    'SPGI': ['S&P Global'],
    'MCO': ['Moody\'s'],
    'MSCI': ['MSCI'],
    'FIS': ['FIS', 'Fidelity National'],
    'FISV': ['Fiserv'],
    'GPN': ['Global Payments'],

    # ==================== US HEALTHCARE ====================
    'JNJ': ['Johnson & Johnson', 'J&J'],
    'UNH': ['UnitedHealth', 'United Health'],
    'PFE': ['Pfizer'],
    'MRK': ['Merck'],
    'ABBV': ['AbbVie'],
    'LLY': ['Eli Lilly', 'Lilly'],
    'TMO': ['Thermo Fisher'],
    'ABT': ['Abbott'],
    'DHR': ['Danaher'],
    'BMY': ['Bristol-Myers', 'Bristol Myers Squibb'],
    'AMGN': ['Amgen'],
    'GILD': ['Gilead'],
    'VRTX': ['Vertex'],
    'REGN': ['Regeneron'],
    'BIIB': ['Biogen'],
    'MRNA': ['Moderna'],
    'CVS': ['CVS'],
    'CI': ['Cigna'],
    'ELV': ['Elevance', 'Anthem'],
    'HUM': ['Humana'],
    'CNC': ['Centene'],
    'MCK': ['McKesson'],
    'CAH': ['Cardinal Health'],
    'ABC': ['AmerisourceBergen', 'Cencora'],
    'SYK': ['Stryker'],
    'BSX': ['Boston Scientific'],
    'MDT': ['Medtronic'],
    'ISRG': ['Intuitive Surgical'],
    'EW': ['Edwards Lifesciences'],
    'ZBH': ['Zimmer Biomet'],
    'DXCM': ['DexCom'],
    'IDXX': ['IDEXX'],
    'IQV': ['IQVIA'],
    'A': ['Agilent'],
    'BIO': ['Bio-Rad'],
    'MTD': ['Mettler-Toledo'],
    'WAT': ['Waters'],

    # ==================== US CONSUMER ====================
    'WMT': ['Walmart'],
    'COST': ['Costco'],
    'HD': ['Home Depot'],
    'LOW': ['Lowe\'s', 'Lowes'],
    'TGT': ['Target'],
    'AMZN': ['Amazon', 'AWS', 'Prime'],
    'MCD': ['McDonald\'s', 'McDonalds'],
    'SBUX': ['Starbucks'],
    'NKE': ['Nike'],
    'KO': ['Coca-Cola', 'Coke'],
    'PEP': ['Pepsi', 'PepsiCo'],
    'PG': ['Procter & Gamble', 'P&G'],
    'CL': ['Colgate', 'Colgate-Palmolive'],
    'KMB': ['Kimberly-Clark', 'Kimberly Clark'],
    'EL': ['Estee Lauder', 'Estée Lauder'],
    'PM': ['Philip Morris'],
    'MO': ['Altria'],
    'BTI': ['British American Tobacco'],
    'KHC': ['Kraft Heinz'],
    'MDLZ': ['Mondelez'],
    'GIS': ['General Mills'],
    'K': ['Kellogg', 'Kellanova'],
    'CAG': ['Conagra'],
    'SJM': ['Smucker', 'J.M. Smucker'],
    'HSY': ['Hershey'],
    'CPB': ['Campbell', 'Campbell Soup'],
    'HRL': ['Hormel'],
    'TSN': ['Tyson'],
    'ADM': ['Archer-Daniels-Midland', 'ADM'],
    'BG': ['Bunge'],
    'CMG': ['Chipotle'],
    'DPZ': ['Domino\'s', 'Dominos'],
    'YUM': ['Yum Brands', 'KFC', 'Taco Bell', 'Pizza Hut'],
    'QSR': ['Restaurant Brands', 'Burger King', 'Tim Hortons'],
    'DRI': ['Darden', 'Olive Garden'],
    'MAR': ['Marriott'],
    'HLT': ['Hilton'],
    'H': ['Hyatt'],
    'WH': ['Wyndham'],
    'LVS': ['Las Vegas Sands'],
    'MGM': ['MGM'],
    'WYNN': ['Wynn'],
    'RCL': ['Royal Caribbean'],
    'CCL': ['Carnival'],
    'NCLH': ['Norwegian Cruise'],
    'EXPE': ['Expedia'],
    'BKNG': ['Booking', 'Booking.com', 'Priceline'],
    'DIS': ['Disney', 'Walt Disney'],
    'CMCSA': ['Comcast', 'NBCUniversal', 'Xfinity'],
    'WBD': ['Warner Bros', 'Discovery'],
    'PARA': ['Paramount'],
    'FOXA': ['Fox'],
    'NWSA': ['News Corp'],
    'LYV': ['Live Nation'],
    'EA': ['Electronic Arts', 'EA Sports'],
    'TTWO': ['Take-Two', 'Rockstar', 'GTA'],
    'ATVI': ['Activision', 'Blizzard'],
    'TJX': ['TJX', 'TJ Maxx', 'Marshalls'],
    'ROST': ['Ross Stores', 'Ross'],
    'BURL': ['Burlington'],
    'GPS': ['Gap'],
    'ANF': ['Abercrombie'],
    'LULU': ['Lululemon'],
    'VFC': ['VF Corp', 'North Face', 'Vans'],
    'RL': ['Ralph Lauren'],
    'PVH': ['PVH', 'Calvin Klein', 'Tommy Hilfiger'],
    'TPR': ['Tapestry', 'Coach', 'Kate Spade'],
    'CPRI': ['Capri', 'Michael Kors', 'Versace'],
    'AEO': ['American Eagle'],
    'URBN': ['Urban Outfitters'],
    'BBY': ['Best Buy'],
    'GME': ['GameStop'],
    'ULTA': ['Ulta'],
    'DG': ['Dollar General'],
    'DLTR': ['Dollar Tree'],
    'FIVE': ['Five Below'],
    'ORLY': ['O\'Reilly', 'O\'Reilly Auto'],
    'AZO': ['AutoZone'],
    'AAP': ['Advance Auto'],
    'KMX': ['CarMax'],
    'AN': ['AutoNation'],
    'F': ['Ford'],
    'GM': ['General Motors', 'GM', 'Chevrolet', 'Cadillac'],
    'STLA': ['Stellantis', 'Jeep', 'Dodge', 'Ram', 'Chrysler', 'Peugeot', 'Fiat'],
    'RIVN': ['Rivian'],
    'LCID': ['Lucid'],
    'NIO': ['NIO'],
    'XPEV': ['XPeng'],
    'LI': ['Li Auto'],

    # ==================== US INDUSTRIAL ====================
    'CAT': ['Caterpillar'],
    'DE': ['Deere', 'John Deere'],
    'BA': ['Boeing'],
    'RTX': ['Raytheon', 'RTX'],
    'LMT': ['Lockheed Martin', 'Lockheed'],
    'NOC': ['Northrop Grumman', 'Northrop'],
    'GD': ['General Dynamics'],
    'GE': ['General Electric', 'GE Aerospace'],
    'HON': ['Honeywell'],
    'MMM': ['3M'],
    'EMR': ['Emerson'],
    'ETN': ['Eaton'],
    'ROK': ['Rockwell'],
    'PH': ['Parker Hannifin', 'Parker'],
    'ITW': ['Illinois Tool Works'],
    'IR': ['Ingersoll Rand'],
    'DOV': ['Dover'],
    'SWK': ['Stanley Black & Decker', 'Stanley', 'DeWalt'],
    'CMI': ['Cummins'],
    'PCAR': ['Paccar', 'Kenworth', 'Peterbilt'],
    'TT': ['Trane Technologies', 'Trane'],
    'CARR': ['Carrier'],
    'OTIS': ['Otis'],
    'JCI': ['Johnson Controls'],
    'LII': ['Lennox'],
    'FDX': ['FedEx'],
    'UPS': ['UPS', 'United Parcel'],
    'UNP': ['Union Pacific'],
    'CSX': ['CSX'],
    'NSC': ['Norfolk Southern'],
    'DAL': ['Delta', 'Delta Airlines'],
    'UAL': ['United Airlines'],
    'AAL': ['American Airlines'],
    'LUV': ['Southwest', 'Southwest Airlines'],
    'ALK': ['Alaska Airlines'],
    'JBLU': ['JetBlue'],
    'WM': ['Waste Management'],
    'RSG': ['Republic Services'],
    'WCN': ['Waste Connections'],
    'GWW': ['Grainger'],
    'FAST': ['Fastenal'],
    'URI': ['United Rentals'],

    # ==================== US ENERGY ====================
    'XOM': ['Exxon', 'ExxonMobil'],
    'CVX': ['Chevron'],
    'COP': ['ConocoPhillips', 'Conoco'],
    'EOG': ['EOG'],
    'SLB': ['Schlumberger', 'SLB'],
    'OXY': ['Occidental'],
    'MPC': ['Marathon Petroleum'],
    'VLO': ['Valero'],
    'PSX': ['Phillips 66'],
    'PXD': ['Pioneer Natural'],
    'DVN': ['Devon Energy', 'Devon'],
    'FANG': ['Diamondback'],
    'HES': ['Hess'],
    'HAL': ['Halliburton'],
    'BKR': ['Baker Hughes'],
    'KMI': ['Kinder Morgan'],
    'WMB': ['Williams Companies', 'Williams'],
    'OKE': ['ONEOK'],
    'ET': ['Energy Transfer'],
    'EPD': ['Enterprise Products'],
    'LNG': ['Cheniere'],

    # ==================== US UTILITIES & REITS ====================
    'NEE': ['NextEra', 'NextEra Energy'],
    'DUK': ['Duke Energy', 'Duke'],
    'SO': ['Southern Company', 'Southern'],
    'D': ['Dominion', 'Dominion Energy'],
    'AEP': ['American Electric Power', 'AEP'],
    'EXC': ['Exelon'],
    'SRE': ['Sempra'],
    'XEL': ['Xcel Energy', 'Xcel'],
    'ED': ['Consolidated Edison', 'ConEd'],
    'WEC': ['WEC Energy'],
    'ES': ['Eversource'],
    'AWK': ['American Water'],
    'AMT': ['American Tower'],
    'CCI': ['Crown Castle'],
    'SBAC': ['SBA Communications'],
    'PLD': ['Prologis'],
    'EQIX': ['Equinix'],
    'DLR': ['Digital Realty'],
    'PSA': ['Public Storage'],
    'EXR': ['Extra Space Storage'],
    'AVB': ['AvalonBay'],
    'EQR': ['Equity Residential'],
    'MAA': ['Mid-America Apartment'],
    'UDR': ['UDR'],
    'SPG': ['Simon Property'],
    'O': ['Realty Income'],
    'VICI': ['VICI Properties'],
    'WELL': ['Welltower'],
    'VTR': ['Ventas'],
    'ARE': ['Alexandria Real Estate'],
    'BXP': ['Boston Properties'],

    # ==================== US MATERIALS ====================
    'LIN': ['Linde'],
    'APD': ['Air Products'],
    'SHW': ['Sherwin-Williams', 'Sherwin Williams'],
    'ECL': ['Ecolab'],
    'DD': ['DuPont'],
    'DOW': ['Dow'],
    'LYB': ['LyondellBasell', 'Lyondell'],
    'PPG': ['PPG'],
    'NEM': ['Newmont'],
    'FCX': ['Freeport-McMoRan', 'Freeport'],
    'NUE': ['Nucor'],
    'STLD': ['Steel Dynamics'],
    'CF': ['CF Industries'],
    'MOS': ['Mosaic'],
    'ALB': ['Albemarle'],
    'EMN': ['Eastman Chemical', 'Eastman'],
    'CE': ['Celanese'],
    'IFF': ['IFF', 'International Flavors'],
    'IP': ['International Paper'],
    'PKG': ['Packaging Corp'],
    'AVY': ['Avery Dennison'],
    'BALL': ['Ball Corp', 'Ball'],
    'AMCR': ['Amcor'],

    # ==================== US TELECOM ====================
    'T': ['AT&T'],
    'VZ': ['Verizon'],
    'TMUS': ['T-Mobile'],
    'CHTR': ['Charter', 'Spectrum'],

    # ==================== EUROPEAN STOCKS ====================
    # Technology
    'ASML': ['ASML', 'EUV', 'lithography'],
    'SAP': ['SAP'],
    'ERIC': ['Ericsson'],
    'NOK': ['Nokia'],
    'STM': ['STMicroelectronics', 'STMicro'],
    'IFNNY': ['Infineon'],
    'CAP': ['Capgemini'],
    'DAST': ['Dassault Systemes', 'Dassault'],

    # Finance
    'HSBC': ['HSBC'],
    'BCS': ['Barclays'],
    'LYG': ['Lloyds', 'Lloyds Bank'],
    'NWG': ['NatWest'],
    'DB': ['Deutsche Bank'],
    'UBS': ['UBS'],
    'CS': ['Credit Suisse'],
    'ING': ['ING'],
    'BNPQY': ['BNP Paribas', 'BNP'],
    'SCGLY': ['Societe Generale'],
    'SAN': ['Santander'],
    'BBVA': ['BBVA'],
    'UNCRY': ['UniCredit'],
    'ISP': ['Intesa Sanpaolo', 'Intesa'],
    'AXA': ['AXA'],
    'ALIZY': ['Allianz'],
    'MUV2': ['Munich Re'],
    'ZURN': ['Zurich Insurance', 'Zurich'],

    # Healthcare & Pharma
    'NVS': ['Novartis'],
    'ROG': ['Roche'],
    'RHHBY': ['Roche'],
    'AZN': ['AstraZeneca'],
    'GSK': ['GSK', 'GlaxoSmithKline'],
    'SNY': ['Sanofi'],
    'NVO': ['Novo Nordisk', 'Ozempic', 'Wegovy'],
    'BAYRY': ['Bayer'],
    'ELAN': ['Elanco'],

    # Consumer
    'NSRGY': ['Nestle', 'Nestlé'],
    'NESN': ['Nestle', 'Nestlé'],
    'UL': ['Unilever'],
    'DEO': ['Diageo'],
    'BUD': ['AB InBev', 'Anheuser-Busch', 'Budweiser'],
    'LVMUY': ['LVMH', 'Louis Vuitton', 'Moet', 'Hennessy'],
    'MC': ['LVMH', 'Louis Vuitton'],
    'PPRUY': ['Kering', 'Gucci'],
    'KER': ['Kering', 'Gucci'],
    'HESAY': ['Hermes', 'Hermès'],
    'RMS': ['Hermes', 'Hermès'],
    'CFR': ['Richemont', 'Cartier'],
    'ADDYY': ['Adidas'],
    'ADS': ['Adidas'],
    'PMMAF': ['Philip Morris'],
    'LRLCY': ['L\'Oreal', 'L\'Oréal', 'Loreal'],
    'OR': ['L\'Oreal', 'L\'Oréal', 'Loreal'],
    'DANOY': ['Danone'],

    # Industrial
    'SIEGY': ['Siemens'],
    'SIE': ['Siemens'],
    'ABB': ['ABB'],
    'ATLKY': ['Atlas Copco'],
    'VOLVY': ['Volvo'],
    'SCHN': ['Schneider Electric', 'Schneider'],
    'LEGIF': ['Legrand'],
    'SBGSY': ['Schneider Electric'],
    'ALIZF': ['Air Liquide'],
    'AI': ['Air Liquide'],
    'VWAGY': ['Volkswagen', 'VW', 'Audi', 'Porsche'],
    'VOW3': ['Volkswagen', 'VW'],
    'BAMXF': ['BMW'],
    'BMW': ['BMW', 'Mini', 'Rolls-Royce Motors'],
    'DDAIF': ['Mercedes-Benz', 'Mercedes', 'Daimler'],
    'MBG': ['Mercedes-Benz', 'Mercedes'],
    'RACE': ['Ferrari'],
    'POAHY': ['Porsche'],
    'P911': ['Porsche'],
    'RNLSY': ['Renault'],
    'RNO': ['Renault'],
    'STLA': ['Stellantis', 'Peugeot', 'Citroen', 'Fiat', 'Jeep'],
    'EADSY': ['Airbus'],
    'AIR': ['Airbus'],
    'SAFRY': ['Safran'],
    'SAF': ['Safran'],
    'RYCEY': ['Rolls-Royce'],
    'RR': ['Rolls-Royce'],
    'BA.L': ['BAE Systems', 'BAE'],

    # Energy
    'SHEL': ['Shell'],
    'BP': ['BP', 'British Petroleum'],
    'TTE': ['TotalEnergies', 'Total'],
    'EQNR': ['Equinor'],
    'ENI': ['ENI'],
    'REPSOL': ['Repsol'],
    'IBDRY': ['Iberdrola'],
    'IBE': ['Iberdrola'],
    'ENGI': ['Engie'],
    'ENEL': ['Enel'],
    'ORSTED': ['Orsted', 'Ørsted'],

    # Telecom
    'VOD': ['Vodafone'],
    'DTEGY': ['Deutsche Telekom', 'T-Mobile'],
    'DTE': ['Deutsche Telekom'],
    'ORAN': ['Orange'],
    'TEF': ['Telefonica', 'Telefónica'],

    # Materials & Mining
    'RIO': ['Rio Tinto'],
    'BHP': ['BHP', 'BHP Billiton'],
    'VALE': ['Vale'],
    'GLNCY': ['Glencore'],
    'GLEN': ['Glencore'],
    'AAL.L': ['Anglo American'],
    'MT': ['ArcelorMittal'],
    'BASFY': ['BASF'],
    'BAS': ['BASF'],

    # Other European
    'RELX': ['RELX', 'Reed Elsevier'],
    'WPP': ['WPP'],
    'SPOT': ['Spotify'],
    'NXPI': ['NXP', 'NXP Semiconductors'],
}


def get_uploads_playlist_id(channel_id):
    """Convert channel ID to uploads playlist ID (UC... -> UU...)"""
    if channel_id.startswith('UC'):
        return 'UU' + channel_id[2:]
    return channel_id


def matches_company(title, ticker, company_name=None):
    """
    Check if a video title matches a company.
    Uses company_name as primary keyword, plus any extra keywords defined for the ticker.
    """
    title_upper = title.upper()

    # Check ticker itself
    if ticker.upper() in title_upper:
        return True

    # Check company name (primary keyword)
    if company_name and company_name.upper() in title_upper:
        return True

    # Check extra keywords if defined
    extra = EXTRA_KEYWORDS.get(ticker.upper(), [])
    for kw in extra:
        if kw.upper() in title_upper:
            return True

    return False
