// Company Investor Relations links - maps stock tickers to IR page URLs
// Comprehensive coverage for S&P 500 and STOXX Europe 600

const TICKER_TO_IR: Record<string, string> = {
  // ============================================
  // S&P 500 - Top 200 (Verified)
  // ============================================

  // Top 50
  NVDA: 'https://investor.nvidia.com',
  AAPL: 'https://investor.apple.com',
  MSFT: 'https://www.microsoft.com/en-us/investor',
  AMZN: 'https://ir.aboutamazon.com',
  GOOGL: 'https://abc.xyz/investor',
  GOOG: 'https://abc.xyz/investor',
  META: 'https://investor.meta.com/',
  AVGO: 'https://investors.broadcom.com',
  TSLA: 'https://ir.tesla.com',
  'BRK.B': 'https://www.berkshirehathaway.com',
  'BRK.A': 'https://www.berkshirehathaway.com',
  LLY: 'https://investor.lilly.com',
  JPM: 'https://www.jpmorganchase.com/ir',
  WMT: 'https://stock.walmart.com',
  V: 'https://investor.visa.com',
  XOM: 'https://investor.exxonmobil.com/',
  ORCL: 'https://investor.oracle.com',
  MA: 'https://investor.mastercard.com',
  UNH: 'https://www.unitedhealthgroup.com/investors.html',
  PG: 'https://pginvestor.com',
  COST: 'https://investor.costco.com',
  JNJ: 'https://www.investor.jnj.com/',
  BAC: 'https://investor.bankofamerica.com',
  ABBV: 'https://investors.abbvie.com',
  NFLX: 'https://ir.netflix.net',
  HD: 'https://ir.homedepot.com',
  MRK: 'https://www.merck.com/investor-relations',
  CVX: 'https://www.chevron.com/investors',
  PEP: 'https://www.pepsico.com/investors',
  KO: 'https://investors.coca-colacompany.com',
  TMO: 'https://ir.thermofisher.com',
  CRM: 'https://investor.salesforce.com',
  ADBE: 'https://www.adobe.com/investor-relations.html',
  AMD: 'https://ir.amd.com',
  LIN: 'https://www.linde.com/investors',
  WFC: 'https://www.wellsfargo.com/about/investor-relations',
  ACN: 'https://investor.accenture.com',
  CSCO: 'https://investor.cisco.com',
  MCD: 'https://corporate.mcdonalds.com/corpmcd/investors.html',
  ABT: 'https://www.abbottinvestor.com',
  PM: 'https://www.pmi.com/investor-relations',
  GE: 'https://www.geaerospace.com/investor-relations',
  INTU: 'https://investors.intuit.com',
  DIS: 'https://thewaltdisneycompany.com/investor-relations',
  IBM: 'https://www.ibm.com/investor',
  CAT: 'https://investors.caterpillar.com',
  VZ: 'https://www.verizon.com/about/investors',
  QCOM: 'https://investor.qualcomm.com',
  DHR: 'https://investors.danaher.com',
  ISRG: 'https://isrg.intuitive.com',
  CMCSA: 'https://www.cmcsa.com/investors',
  MS: 'https://www.morganstanley.com/about-us-ir',

  // Ranks 51-100
  INTC: 'https://www.intc.com',
  GEV: 'https://www.gevernova.com/investors',
  SCHW: 'https://www.aboutschwab.com/investor-relations',
  BA: 'https://investors.boeing.com',
  AMGN: 'https://investors.amgen.com',
  T: 'https://investors.att.com',
  UBER: 'https://investor.uber.com',
  BKNG: 'https://ir.bookingholdings.com',
  TJX: 'https://www.tjx.com/investors',
  APH: 'https://investors.amphenol.com',
  NEE: 'https://investor.nexteraenergy.com',
  BLK: 'https://ir.blackrock.com',
  ANET: 'https://investors.arista.com',
  KLAC: 'https://ir.kla.com',
  TXN: 'https://investor.ti.com',
  COF: 'https://investor.capitalone.com',
  SPGI: 'https://investor.spglobal.com',
  NOW: 'https://investors.servicenow.com',
  GILD: 'https://investors.gilead.com',
  PFE: 'https://investors.pfizer.com',
  BSX: 'https://investors.bostonscientific.com',
  LOW: 'https://ir.lowes.com',
  HON: 'https://investor.honeywell.com',
  UNP: 'https://investor.unionpacific.com/',
  PANW: 'https://investors.paloaltonetworks.com',
  SYK: 'https://investors.stryker.com',
  FISV: 'https://investors.fiserv.com',
  FI: 'https://investors.fiserv.com/',
  KKR: 'https://ir.kkr.com',
  ADP: 'https://investors.adp.com',
  CRWD: 'https://ir.crowdstrike.com',
  ETN: 'https://www.eaton.com/us/en-us/company/investor-relations.html',
  MU: 'https://investors.micron.com',
  VRTX: 'https://investors.vrtx.com',
  PGR: 'https://investors.progressive.com',
  COP: 'https://www.conocophillips.com/investor-relations/',
  DE: 'https://investor.deere.com',
  ADI: 'https://investor.analog.com',
  ADM: 'https://investors.adm.com/',
  MDT: 'https://investorrelations.medtronic.com/',
  CB: 'https://investors.chubb.com',
  LRCX: 'https://investor.lamresearch.com',

  // Ranks 101-150
  CME: 'https://www.cmegroup.com/investor-relations.html',
  MO: 'https://investor.altria.com',
  BX: 'https://ir.blackstone.com',
  ICE: 'https://ir.theice.com',
  AMT: 'https://americantower.gcs-web.com/',
  LMT: 'https://investors.lockheedmartin.com',
  SO: 'https://investor.southerncompany.com',
  PLD: 'https://ir.prologis.com',
  BMY: 'https://www.bms.com/investors.html',
  TT: 'https://investors.tranetechnologies.com',
  SBUX: 'https://investor.starbucks.com',
  ELV: 'https://ir.elevancehealth.com',
  DUK: 'https://investors.duke-energy.com',
  WELL: 'https://welltower.com/investors',
  MCK: 'https://investor.mckesson.com',
  CEG: 'https://investors.constellationenergy.com',
  CDNS: 'https://investors.cadence.com',
  CI: 'https://investors.thecignagroup.com',
  AJG: 'https://investor.ajg.com',
  WM: 'https://investors.wm.com',
  PH: 'https://investors.parker.com/',
  MDLZ: 'https://ir.mondelezinternational.com',
  EQIX: 'https://investor.equinix.com',
  SHW: 'https://investors.sherwin-williams.com',
  MMM: 'https://investors.3m.com',
  TDG: 'https://investors.transdigm.com/',
  ORLY: 'https://corporate.oreillyauto.com/investor-relations',
  CVS: 'https://investors.cvshealth.com',
  SNPS: 'https://investor.synopsys.com/',
  AON: 'https://investors.aon.com/',
  CTAS: 'https://www.cintas.com/investor-relations',
  CL: 'https://investor.colgatepalmolive.com',
  MCO: 'https://ir.moodys.com',
  ZTS: 'https://investor.zoetis.com',
  MSI: 'https://investors.motorolasolutions.com',
  PYPL: 'https://investor.pypl.com/home/',
  NKE: 'https://investors.nike.com',
  WMB: 'https://investor.williams.com',
  GD: 'https://investor.gd.com/',
  UPS: 'https://investors.ups.com',
  DASH: 'https://ir.doordash.com',
  CMG: 'https://ir.chipotle.com',
  HCA: 'https://investor.hcahealthcare.com',
  PNC: 'https://investor.pnc.com/',
  USB: 'https://ir.usbank.com',
  HWM: 'https://investors.howmet.com',
  ECL: 'https://investor.ecolab.com',
  EMR: 'https://www.emerson.com/en-us/investors',
  ITW: 'https://investor.itw.com',
  FTNT: 'https://investor.fortinet.com',

  // Ranks 151-200
  AZO: 'https://investors.autozone.com',
  NOC: 'https://investor.northropgrumman.com',
  JCI: 'https://investors.johnsoncontrols.com',
  BK: 'https://www.bny.com/corporate/en/investor-relations.html',
  REGN: 'https://investor.regeneron.com',
  ADSK: 'https://investors.autodesk.com',
  EOG: 'https://investors.eogresources.com',
  TRV: 'https://investor.travelers.com',
  ROP: 'https://investors.ropertech.com',
  APD: 'https://investors.airproducts.com',
  NEM: 'https://investors.newmont.com',
  MAR: 'https://marriott.gcs-web.com',
  HLT: 'https://ir.hilton.com',
  RCL: 'https://www.rclinvestor.com',
  CSX: 'https://investors.csx.com',
  APO: 'https://ir.apollo.com',
  CARR: 'https://ir.carrier.com',
  WDAY: 'https://investor.workday.com',
  ABNB: 'https://investors.airbnb.com',
  AEP: 'https://www.aep.com/investors',
  COIN: 'https://investor.coinbase.com',
  FCX: 'https://investors.fcx.com',
  TGT: 'https://corporate.target.com/investors',
  PSA: 'https://www.publicstorage.com/investor-relations',
  SLB: 'https://investorcenter.slb.com',
  MMC: 'https://ir.marshmclennan.com',
  NSC: 'https://www.norfolksouthern.com/en/investors',
  D: 'https://investors.dominionenergy.com',
  FDX: 'https://investors.fedex.com',
  SPG: 'https://investors.simon.com',
  EW: 'https://ir.edwards.com',
  OXY: 'https://www.oxy.com/investors',
  O: 'https://www.realtyincome.com/investors',
  RACE: 'https://www.ferrari.com/en-EN/corporate/investors',
  DELL: 'https://investors.delltechnologies.com',
  MCHP: 'https://investors.microchip.com',
  ROST: 'https://investors.rossstores.com',
  STZ: 'https://ir.cbrands.com',
  PAYX: 'https://investor.paychex.com',
  LULU: 'https://investor.lululemon.com/',
  MNST: 'https://investors.monsterbevcorp.com',
  ODFL: 'https://ir.odfl.com',
  A: 'https://investor.agilent.com',
  OTIS: 'https://investors.otis.com',
  MSCI: 'https://ir.msci.com',
  TEL: 'https://investors.te.com',
  HES: 'https://investors.hess.com',
  MET: 'https://investor.metlife.com',

  // ============================================
  // S&P 500 - Remaining (Best Effort)
  // ============================================

  ACGL: 'https://investors.archgroup.com',
  AEE: 'https://investor.ameren.com',
  AES: 'https://www.aes.com/investors',
  AFL: 'https://investors.aflac.com/',
  AIG: 'https://aig.gcs-web.com/',
  AIZ: 'https://ir.assurant.com',
  AKAM: 'https://www.ir.akamai.com/',
  ALB: 'https://investors.albemarle.com',
  ALGN: 'https://investor.aligntech.com',
  ALL: 'https://investors.allstate.com/',
  ALLE: 'https://investor.allegion.com',
  AMAT: 'https://ir.appliedmaterials.com',
  AMCR: 'https://www.amcor.com/investors',
  AME: 'https://investors.ametek.com/',
  AMP: 'https://ir.ameriprise.com',
  AOS: 'https://investor.aosmith.com',
  APA: 'https://investor.apacorp.com',
  ANSS: 'https://investors.ansys.com/',
  APTV: 'https://ir.aptiv.com/',
  ARE: 'https://investor.are.com/',
  AZPN: 'https://ir.aspentech.com/',
  ARES: 'https://ir.aresmgmt.com',
  ATO: 'https://investors.atmosenergy.com',
  AVB: 'https://investors.avalonbay.com',
  AVY: 'https://investors.averydennison.com',
  AWK: 'https://ir.amwater.com',
  AXON: 'https://investor.axon.com',
  AXP: 'https://ir.americanexpress.com',
  BALL: 'https://investors.ball.com',
  BAX: 'https://investor.baxter.com',
  BBY: 'https://investors.bestbuy.com',
  BDX: 'https://investors.bd.com',
  BEN: 'https://investor.franklinresources.com',
  'BF.B': 'https://investor.brown-forman.com',
  BG: 'https://investors.bunge.com',
  BIIB: 'https://investors.biogen.com',
  BKR: 'https://investors.bakerhughes.com',
  BLDR: 'https://ir.bldr.com',
  BR: 'https://investor.broadridge.com',
  BRO: 'https://investor.bbinsurance.com',
  BWA: 'https://www.borgwarner.com/investors',
  BXP: 'https://investors.bxp.com',
  C: 'https://www.citigroup.com/global/investors',
  CAG: 'https://www.conagrabrands.com/investor-relations',
  CAH: 'https://ir.cardinalhealth.com',
  CZR: 'https://investor.caesars.com/',
  CBOE: 'https://ir.cboe.com',
  CBRE: 'https://ir.cbre.com',
  CCI: 'https://investors.crowncastle.com/',
  CCL: 'https://www.carnivalcorp.com/investor-relations',
  CDW: 'https://investor.cdw.com',
  CE: 'https://investors.celanese.com',
  CF: 'https://cfinvestors.com/',
  CFG: 'https://investor.citizensbank.com',
  CHD: 'https://investor.churchdwight.com',
  CHRW: 'https://investor.chrobinson.com',
  CHTR: 'https://ir.charter.com',
  CINF: 'https://cinfin.com/investors',
  CLX: 'https://investors.thecloroxcompany.com',
  CMI: 'https://investor.cummins.com',
  CMS: 'https://www.cmsenergy.com/investor-relations/',
  CNC: 'https://investors.centene.com',
  CNP: 'https://investors.centerpointenergy.com',
  COO: 'https://investor.coopercos.com',
  COR: 'https://investor.cencora.com',
  CPAY: 'https://investor.corpay.com',
  CPB: 'https://investor.campbellsoupcompany.com',
  CPRT: 'https://www.copart.com/investor-relations/',
  CPT: 'https://investors.camdenliving.com/',
  CRH: 'https://www.crh.com/investors',
  CRL: 'https://ir.criver.com',
  CSGP: 'https://investors.costargroup.com',
  CTSH: 'https://investors.cognizant.com',
  CTVA: 'https://investors.corteva.com/',
  CTRA: 'https://investors.coterra.com/',
  CVNA: 'https://investors.carvana.com',
  DAL: 'https://ir.delta.com',
  DAY: 'https://investors.dayforce.com',
  DD: 'https://www.investors.dupont.com/',
  DDOG: 'https://investors.datadoghq.com',
  DECK: 'https://ir.deckers.com',
  DFS: 'https://investorrelations.discover.com',
  DG: 'https://investor.dollargeneral.com',
  DGX: 'https://investor.questdiagnostics.com',
  DHI: 'https://investor.drhorton.com',
  DLR: 'https://investor.digitalrealty.com/',
  DLTR: 'https://corporate.dollartree.com/investors',
  DOC: 'https://ir.healthpeak.com',
  DOV: 'https://investors.dovercorporation.com',
  DOW: 'https://investors.dow.com',
  DPZ: 'https://ir.dominos.com',
  DRI: 'https://investor.darden.com',
  DTE: 'https://ir.dteenergy.com/',
  DVA: 'https://investors.davita.com',
  DVN: 'https://investors.devonenergy.com',
  DXCM: 'https://investors.dexcom.com',
  EA: 'https://ir.ea.com',
  EMN: 'https://investors.eastman.com/',
  EBAY: 'https://investors.ebayinc.com',
  ED: 'https://investor.conedison.com',
  EFX: 'https://investor.equifax.com',
  EG: 'https://ir.everestglobal.com/',
  EIX: 'https://www.edisoninvestor.com/',
  EL: 'https://investors.elcompanies.com/',
  EME: 'https://investors.emcorgroup.com',
  ENPH: 'https://investor.enphase.com',
  EPAM: 'https://investors.epam.com',
  EQR: 'https://investors.equityapartments.com',
  EQT: 'https://ir.eqt.com',
  ERIE: 'https://www.erieinsurance.com/investors',
  ES: 'https://www.eversource.com/content/general/about/investors',
  ESNT: 'https://ir.essent.us/',
  ESS: 'https://investors.essexapartmenthomes.com/',
  ETR: 'https://investor.entergy.com',
  EVRG: 'https://investors.evergy.com',
  EXC: 'https://investors.exeloncorp.com',
  EXE: 'https://investors.expandenergy.com',
  EXPD: 'https://investor.expeditors.com',
  EXPE: 'https://ir.expediagroup.com',
  EXR: 'https://ir.extraspace.com',
  F: 'https://shareholder.ford.com',
  FANG: 'https://ir.diamondbackenergy.com',
  FAST: 'https://investor.fastenal.com',
  FDS: 'https://investor.factset.com',
  FE: 'https://investors.firstenergycorp.com',
  FFIV: 'https://investors.f5.com',
  FICO: 'https://investor.fico.com',
  FIS: 'https://investor.fisglobal.com',
  FITB: 'https://ir.53.com',
  FIX: 'https://investors.comfortsystemsusa.com',
  FMC: 'https://investors.fmc.com',
  FOX: 'https://investor.foxcorporation.com',
  FOXA: 'https://investor.foxcorporation.com',
  FRT: 'https://ir.federalrealty.com/',
  FSLR: 'https://investor.firstsolar.com',
  FTV: 'https://investors.fortive.com',
  GDDY: 'https://investors.godaddy.net',
  GEHC: 'https://investor.gehealthcare.com',
  GEN: 'https://investor.gendigital.com',
  GIS: 'https://investors.generalmills.com',
  GL: 'https://investors.globelifeinsurance.com',
  GLW: 'https://investor.corning.com',
  GM: 'https://investor.gm.com',
  GNRC: 'https://investors.generac.com',
  GPC: 'https://investor.genpt.com',
  GPN: 'https://investors.globalpaymentsinc.com/',
  GRMN: 'https://www.garmin.com/en-US/investors/',
  GS: 'https://www.goldmansachs.com/investor-relations',
  GWW: 'https://invest.grainger.com',
  HAL: 'https://ir.halliburton.com',
  HAS: 'https://investor.hasbro.com',
  HBAN: 'https://investors.huntington.com/',
  HIG: 'https://ir.thehartford.com/',
  HII: 'https://investors.huntingtoningalls.com',
  HOLX: 'https://investors.hologic.com',
  HOOD: 'https://investors.robinhood.com',
  HPE: 'https://investors.hpe.com',
  HPQ: 'https://investor.hp.com',
  HRL: 'https://investor.hormelfoods.com',
  HSIC: 'https://investor.henryschein.com',
  HST: 'https://ir.hosthotels.com',
  HSY: 'https://investors.thehersheycompany.com',
  HUBB: 'https://investor.hubbell.com',
  HUM: 'https://investor.humana.com',
  IDXX: 'https://www.idexx.com/en/about-idexx/investor-relations/',
  IEX: 'https://investors.idexcorp.com',
  ILMN: 'https://investor.illumina.com/',
  IFF: 'https://ir.iff.com',
  INCY: 'https://investor.incyte.com',
  INVH: 'https://investors.invitationhomes.com',
  IP: 'https://investor.internationalpaper.com',
  IPG: 'https://investors.interpublic.com',
  IQV: 'https://ir.iqvia.com',
  IR: 'https://investors.irco.com',
  IRM: 'https://investor.ironmountain.com',
  IT: 'https://investor.gartner.com',
  IVZ: 'https://ir.invesco.com',
  J: 'https://investors.jacobs.com/',
  JBHT: 'https://investor.jbhunt.com',
  JBL: 'https://investors.jabil.com',
  JKHY: 'https://ir.jackhenry.com',
  JNPR: 'https://investor.juniper.net/',
  K: 'https://investor.kellanova.com',
  KDP: 'https://investor.keurigdrpepper.com',
  KEY: 'https://investor.key.com',
  KEYS: 'https://investor.keysight.com',
  KHC: 'https://ir.kraftheinzcompany.com',
  KIM: 'https://investors.kimcorealty.com',
  KMB: 'https://investor.kimberly-clark.com',
  KMX: 'https://investors.carmax.com/',
  KMI: 'https://ir.kindermorgan.com',
  KR: 'https://ir.kroger.com',
  KVUE: 'https://investors.kenvue.com',
  L: 'https://loews.com/investor-relations',
  LDOS: 'https://investors.leidos.com',
  LEN: 'https://investors.lennar.com',
  LH: 'https://ir.labcorp.com',
  LHX: 'https://www.l3harris.com/investors',
  LII: 'https://investor.lennoxinternational.com',
  LKQ: 'https://investor.lkq.com',
  LNT: 'https://investor.alliantenergy.com',
  LUV: 'https://www.southwestairlinesinvestorrelations.com',
  LVS: 'https://investor.sands.com',
  LW: 'https://investors.lambweston.com',
  LYB: 'https://www.lyondellbasell.com/en/investors/',
  LYV: 'https://investors.livenationentertainment.com',
  MAA: 'https://investors.maac.com/',
  MAS: 'https://masco.com/investor-relations/',
  MKTX: 'https://investor.marketaxess.com',
  MLM: 'https://investor.martinmarietta.com',
  MGM: 'https://investors.mgmresorts.com',
  MHK: 'https://ir.mohawkind.com/',
  MKC: 'https://ir.mccormick.com',
  MOH: 'https://ir.molinahealthcare.com',
  MOS: 'https://investors.mosaicco.com',
  MPC: 'https://ir.marathonpetroleum.com',
  MPWR: 'https://monolithicpower.com/en/investors.html',
  MRO: 'https://ir.marathonoil.com/',
  MRNA: 'https://investors.modernatx.com',
  MTB: 'https://ir.mtb.com',
  MTCH: 'https://ir.mtch.com',
  MTD: 'https://investor.mt.com',
  NCLH: 'https://investor.nclhltd.com',
  NDAQ: 'https://ir.nasdaq.com',
  NDSN: 'https://investors.nordson.com',
  NI: 'https://investors.nisource.com',
  NRG: 'https://investors.nrg.com',
  NTAP: 'https://investors.netapp.com',
  NTRS: 'https://www.northerntrust.com/about-us/investor-relations',
  NUE: 'https://investors.nucor.com',
  NVR: 'https://www.nvrinc.com/investors',
  NWS: 'https://newscorp.com/investor-relations',
  NWSA: 'https://newscorp.com/investor-relations',
  NXPI: 'https://investors.nxp.com',
  OKE: 'https://investor.oneok.com',
  OC: 'https://investor.owenscorning.com/',
  OGN: 'https://www.organon.com/investor-relations/',
  OMC: 'https://investor.omnicomgroup.com',
  ON: 'https://investor.onsemi.com',
  PARA: 'https://ir.paramount.com',
  PAYC: 'https://investors.paycom.com',
  PCAR: 'https://www.paccar.com/investors',
  PCG: 'https://investor.pgecorp.com',
  PEG: 'https://investor.pseg.com',
  PFG: 'https://investors.principal.com',
  PHM: 'https://investors.pultegroup.com/',
  PKG: 'https://investors.packagingcorp.com',
  PLTR: 'https://investors.palantir.com',
  PNR: 'https://investors.pentair.com',
  PNW: 'https://investors.pinnaclewest.com',
  PODD: 'https://investor.insulet.com',
  POOL: 'https://ir.poolcorp.com',
  PPG: 'https://investor.ppg.com',
  PPL: 'https://investors.pplweb.com',
  PRU: 'https://investor.prudential.com',
  PSX: 'https://investor.phillips66.com',
  PTC: 'https://investor.ptc.com',
  PWR: 'https://investors.quantaservices.com',
  QRVO: 'https://ir.qorvo.com/',
  REG: 'https://investors.regencycenters.com',
  RF: 'https://ir.regions.com',
  RJF: 'https://investor.raymondjames.com',
  RL: 'https://investor.ralphlauren.com',
  RMD: 'https://investor.resmed.com',
  ROK: 'https://ir.rockwellautomation.com',
  ROL: 'https://ir.rollins.com',
  RSG: 'https://investor.republicservices.com',
  RTX: 'https://rtx.com/investors',
  RVTY: 'https://investors.revvity.com',
  SBAC: 'https://investors.sbasite.com',
  SJM: 'https://investor.jmsmucker.com',
  SMCI: 'https://ir.supermicro.com',
  SNA: 'https://www.snapon.com/EN/Investors',
  SOLV: 'https://investors.solventum.com/',
  SRE: 'https://investor.sempra.com',
  STE: 'https://investors.steris.com',
  STLD: 'https://investors.steeldynamics.com',
  STT: 'https://investors.statestreet.com',
  STX: 'https://investors.seagate.com',
  SW: 'https://investors.smurfitwestrock.com',
  SWK: 'https://ir.stanleyblackanddecker.com',
  SWKS: 'https://investors.skyworksinc.com',
  SYF: 'https://investors.synchrony.com',
  SYY: 'https://investors.sysco.com',
  TAP: 'https://ir.molsoncoors.com',
  TDY: 'https://www.teledyne.com/investors',
  TECH: 'https://investors.bio-techne.com',
  TER: 'https://investors.teradyne.com/',
  TFC: 'https://ir.truist.com',
  TFX: 'https://investors.teleflex.com/',
  TKO: 'https://ir.tkogrp.com',
  TMUS: 'https://investor.t-mobile.com',
  TPL: 'https://www.texaspacific.com/investors',
  TPR: 'https://investors.tapestry.com',
  TRGP: 'https://www.targaresources.com/investors',
  TRMB: 'https://investor.trimble.com',
  TROW: 'https://troweprice.gcs-web.com',
  TSCO: 'https://corporate.tractorsupply.com/investors',
  TSN: 'https://ir.tyson.com',
  TTD: 'https://investor.thetradedesk.com',
  TTWO: 'https://www.take2games.com/ir',
  TXT: 'https://investor.textron.com',
  TYL: 'https://investor.tylertech.com',
  UAL: 'https://ir.united.com',
  UDR: 'https://www.udr.com/investors/',
  UHS: 'https://ir.uhsinc.com',
  ULTA: 'https://ir.ulta.com/',
  URI: 'https://unitedrentals.gcs-web.com/',
  VFC: 'https://ir.vfc.com/',
  VICI: 'https://investors.viciproperties.com/',
  VLO: 'https://investorvalero.com/',
  VLTO: 'https://investors.veralto.com',
  VMC: 'https://ir.vulcanmaterials.com',
  VRSK: 'https://investor.verisk.com',
  VRSN: 'https://investor.verisign.com',
  VST: 'https://investor.vistracorp.com',
  VTR: 'https://ir.ventasreit.com',
  VTRS: 'https://investor.viatris.com',
  WAB: 'https://www.wabteccorp.com/investor-relations',
  WAT: 'https://ir.waters.com',
  WBA: 'https://investor.walgreensbootsalliance.com',
  WBD: 'https://ir.wbd.com',
  WDC: 'https://investor.wdc.com',
  WEC: 'https://www.wecenergygroup.com/invest/',
  WHR: 'https://investors.whirlpoolcorp.com/',
  WRB: 'https://ir.wrberkley.com',
  WSO: 'https://www.watsco.com/investor-relations/',
  WSM: 'https://ir.williams-sonomainc.com',
  WST: 'https://investors.westpharma.com',
  WTW: 'https://investors.wtwco.com',
  WY: 'https://investor.weyerhaeuser.com',
  WYNN: 'https://investor.wynnresorts.com',
  XEL: 'https://investors.xcelenergy.com',
  XYL: 'https://www.xylem.com/en-us/investors/',
  YUM: 'https://investors.yum.com',
  ZBH: 'https://investor.zimmerbiomet.com',
  ZBRA: 'https://investors.zebra.com',

  // ============================================
  // STOXX Europe 600 (Best Effort + Known URLs)
  // ============================================

  // Major European Companies (Known URLs)
  // Note: Some European tickers conflict with US tickers - using European suffix where needed
  NESN: 'https://www.nestle.com/investors',
  ROG: 'https://www.roche.com/investors',
  NOVN: 'https://www.novartis.com/investors',
  MC: 'https://www.lvmh.com/investors',
  ASML: 'https://www.asml.com/en/investors',
  AZN: 'https://www.astrazeneca.com/investor-relations.html',
  'NOVO B': 'https://www.novonordisk.com/investors.html',
  RMS: 'https://finance.hermes.com/en/',
  SHEL: 'https://www.shell.com/investors',
  TTE: 'https://totalenergies.com/investors',
  SIE: 'https://www.siemens.com/investor',
  ALV: 'https://www.allianz.com/en/investor_relations',
  'SAN.MC': 'https://www.santander.com/en/shareholders-and-investors',  // Banco Santander (Spain)
  ULVR: 'https://www.unilever.com/investor-relations',
  'DTE.DE': 'https://www.telekom.com/en/investor-relations',  // Deutsche Telekom (Germany)
  HSBA: 'https://www.hsbc.com/investors',
  BNP: 'https://invest.bnpparibas',
  IBE: 'https://www.iberdrola.com/shareholders-investors',
  AIR: 'https://www.airbus.com/en/investors',
  ENEL: 'https://www.enel.com/investors',
  DGE: 'https://www.diageo.com/en/investors',
  GSK: 'https://www.gsk.com/en-gb/investors',
  ABI: 'https://www.ab-inbev.com/investors',
  'BP.': 'https://www.bp.com/en/global/corporate/investors.html',
  RIO: 'https://www.riotinto.com/invest',
  GLEN: 'https://www.glencore.com/investors',
  BAS: 'https://www.basf.com/investors',
  BAYN: 'https://www.bayer.com/investors',
  ENI: 'https://www.eni.com/en-IT/investors.html',
  STLA: 'https://www.stellantis.com/en/investors',
  VOW3: 'https://www.volkswagenag.com/en/InvestorRelations.html',
  BMW: 'https://www.bmwgroup.com/en/investor-relations.html',
  MBG: 'https://group.mercedes-benz.com/investors',
  PHIA: 'https://www.philips.com/a-w/about/investor-relations.html',
  IFX: 'https://www.infineon.com/investors',
  INGA: 'https://www.ing.com/Investor-relations.htm',
  DBK: 'https://investor-relations.db.com',
  ISP: 'https://group.intesasanpaolo.com/en/investor-relations',
  UCG: 'https://www.unicreditgroup.eu/en/investors.html',
  'NG.': 'https://www.nationalgrid.com/investors',
  REL: 'https://www.relx.com/investors',
  EXPN: 'https://www.experianplc.com/investors',
  LSEG: 'https://www.lseg.com/investor-relations',
  CPG: 'https://www.compass-group.com/en/investors.html',
  RKT: 'https://www.reckitt.com/investors',
  SSE: 'https://www.sse.com/investors',
  VOD: 'https://investors.vodafone.com',
  LLOY: 'https://www.lloydsbankinggroup.com/investors.html',
  BARC: 'https://www.barclays.com/investor-relations.html',
  'PRU.L': 'https://www.prudentialplc.com/investors',  // Prudential plc (UK)
  STAN: 'https://www.sc.com/en/investors',
  'AV.': 'https://www.aviva.com/investors',
  LGEN: 'https://www.legalandgeneralgroup.com/investors',

  // European Tech & Software
  ADYEN: 'https://www.adyen.com/investor-relations',
  DSY: 'https://investor.3ds.com',
  CAP: 'https://investors.capgemini.com/en/',
  NOKIA: 'https://www.nokia.com/about-us/investors',
  'ERIC B': 'https://www.ericsson.com/en/investors',
  STMPA: 'https://investors.st.com',

  // European Industrials
  ABB: 'https://global.abb/group/en/investors',
  ABBN: 'https://global.abb/group/en/investors',
  HOLN: 'https://www.holcim.com/investors',
  GEBN: 'https://www.geberit.com/investors',
  SIKA: 'https://www.sika.com/en/investors.html',
  SGO: 'https://www.saint-gobain.com/en/investors',
  KNIN: 'https://newsroom.kuehne-nagel.com/investor-relations/',
  DSV: 'https://investor.dsv.com',
  MTX: 'https://www.mtu.de/investor-relations',
  SAF: 'https://www.safran-group.com/finance',

  // European Healthcare & Pharma
  'SAN.PA': 'https://www.sanofi.com/en/investors',  // Sanofi (France)
  LONN: 'https://www.lonza.com/investors',
  GIVN: 'https://www.givaudan.com/investors',
  SRT3: 'https://www.sartorius.com/en/company/investor-relations',
  'UCB.BR': 'https://www.ucb.com/investors',  // UCB (Belgium)
  ARGX: 'https://www.argenx.com/investors',
  GMAB: 'https://ir.genmab.com',

  // European Consumer & Retail
  KER: 'https://www.kering.com/en/finance',
  MONC: 'https://www.monclergroup.com/en/investors',
  ADS: 'https://www.adidas-group.com/en/investors',
  PUM: 'https://about.puma.com/en/investor-relations',
  'HM B': 'https://hmgroup.com/investors',
  ITX: 'https://www.inditex.com/investors',
  ZAL: 'https://corporate.zalando.com/en/investor-relations',

  // European Banks & Insurance
  UBSG: 'https://www.ubs.com/global/en/investor-relations.html',
  ZURN: 'https://www.zurich.com/en/investors',
  SREN: 'https://www.swissre.com/investors',
  MUV2: 'https://www.munichre.com/en/company/investors.html',
  'CS.PA': 'https://www.axa.com/en/investor',  // AXA (France)
  AGN: 'https://www.aegon.com/investors',
  'NN.AS': 'https://www.nn-group.com/investors.htm',  // NN Group (Netherlands)

  // European Energy & Utilities
  EQNR: 'https://www.equinor.com/investors',
  ENGI: 'https://www.engie.com/en/investors',
  RWE: 'https://www.rwe.com/en/investor-relations',
  EOAN: 'https://www.eon.com/en/investor-relations.html',
  ORSTED: 'https://orsted.com/en/investors',
  VWS: 'https://www.vestas.com/en/investor',

  // European Telecoms
  ORA: 'https://www.orange.com/en/investors',
  TEF: 'https://www.telefonica.com/en/shareholders-investors',
  TELIA: 'https://www.teliacompany.com/en/investors',
  'TEL.OL': 'https://www.telenor.com/investors',  // Telenor (Norway)

  // European Mining & Materials
  AAL: 'https://www.angloamerican.com/investors',
  ANTO: 'https://www.antofagasta.co.uk/investors',
  NHY: 'https://www.hydro.com/en/investors',
  MT: 'https://corporate.arcelormittal.com/investors',

  // More STOXX 600 companies (alphabetical)
  III: 'https://www.3i.com/investor-relations',
  A2A: 'https://www.a2a.eu/en/investors',
  AC: 'https://group.accor.com/en/investors',
  ACS: 'https://www.grupoacs.com/shareholders-and-investors',
  ADEN: 'https://www.adeccogroup.com/investors',
  AENA: 'https://www.aena.es/en/shareholders-and-investors.html',
  AKRBP: 'https://akerbp.com/en/investors',
  AKZA: 'https://www.akzonobel.com/en/investors',
  ALC: 'https://investor.alcon.com',
  ALFA: 'https://www.alfalaval.com/investors',
  ALO: 'https://www.alstom.com/investors',
  AMS: 'https://corporate.amadeus.com/en/investors',
  ANDR: 'https://www.andritz.com/group-en/investors',
  ATE: 'https://www.alten.com/investors',
  AHT: 'https://www.ashtead-group.com/investors',
  ASM: 'https://www.asm.com/investors',
  BATS: 'https://www.bat.com/investors',
  BEI: 'https://www.beiersdorf.com/investors',
  BVI: 'https://group.bureauveritas.com/investors/',
  CABK: 'https://www.caixabank.com/en/shareholders-and-investors.html',
  CLNX: 'https://www.cellnex.com/investor-relations/',
  CFR: 'https://www.richemont.com/investors',
  CON: 'https://www.continental.com/en/investors',
  CRDA: 'https://www.croda.com/en-gb/investors',
  BN: 'https://www.danone.com/investor-relations.html',
  DANSKE: 'https://danskebank.com/investor-relations/',
  'AM.PA': 'https://www.dassault-aviation.com/en/group/finance/',  // Dassault Aviation (France)
  DEMANT: 'https://www.demant.com/investors',
  DB1: 'https://www.deutsche-boerse.com/dbg-en/investor-relations',
  LHA: 'https://investor-relations.lufthansagroup.com/en',
  DHL: 'https://www.dhl.com/global-en/home/about-us/investors.html',
  EDF: 'https://www.edf.fr/en/the-edf-group/investors-shareholders',
  EDP: 'https://www.edp.com/en/investors',
  'EL.PA': 'https://www.essilorluxottica.com/investors',  // EssilorLuxottica (France)
  ENX: 'https://www.euronext.com/en/investor-relations',
  ERF: 'https://www.eurofins.com/investor-relations',
  EVK: 'https://corporate.evonik.com/en/investors',
  FER: 'https://www.ferrovial.com/en/ir/',
  FBK: 'https://www.finecobank.com/en/investor-relations',
  FLTR: 'https://www.flutter.com/investors',
  FME: 'https://www.freseniusmedicalcare.com/en/investors',
  FRE: 'https://www.fresenius.com/investor-relations',
  'G.MI': 'https://www.generali.com/investors',  // Generali (Italy)
  GF: 'https://www.georgfischer.com/en/investors.html',
  G1A: 'https://www.gea.com/en/investor-relations',
  HLMA: 'https://www.halma.com/investors',
  HEI: 'https://www.heidelbergmaterials.com/en/investor-relations',
  HEIA: 'https://www.theheinekencompany.com/investors',
  HEN3: 'https://www.henkel.com/investors-and-analysts',
  'HEXA B': 'https://investors.hexagon.com/',
  HIK: 'https://www.hikma.com/investors',
  IHG: 'https://www.ihgplc.com/investors',
  IMB: 'https://www.imperialbrandsplc.com/investors.html',
  INF: 'https://www.informa.com/investors',
  ITRK: 'https://www.intertek.com/investors',
  IPN: 'https://www.ipsen.com/investors',
  JMT: 'https://www.jeronimomartins.com/en/investor-relations',
  JMAT: 'https://matthey.com/investors',
  BAER: 'https://www.juliusbaer.com/en/investor-relations',
  KBC: 'https://www.kbc.com/en/investor-relations.html',
  KRZ: 'https://www.kerrygroup.com/investors',
  KGF: 'https://www.kingfisher.com/en/investors.html',
  KRX: 'https://www.kingspan.com/group/investors',
  KNEBV: 'https://www.kone.com/en/investors',
  AD: 'https://www.aholddelhaize.com/investors',
  KPN: 'https://www.kpn.com/investors',
  LR: 'https://www.legrandgroup.com/en/investors-and-shareholders',
  LDO: 'https://www.leonardo.com/en/investors',
  LISN: 'https://www.lindt-spruengli.com/investors',
  LOGN: 'https://ir.logitech.com',
  PGHN: 'https://www.partnersgroup.com/investors',
  PSON: 'https://www.pearson.com/corporate/investors.html',
  RI: 'https://www.pernod-ricard.com/en/investors',
  'PSN.L': 'https://www.persimmonhomes.com/corporate/investors',  // Persimmon (UK)
  PRY: 'https://www.prysmian.com/en/investors',
  PUB: 'https://www.publicisgroupe.com/en/investors',
  QGEN: 'https://ir.qiagen.com',
  RAND: 'https://www.randstad.com/investor-relations',
  REC: 'https://www.recordati.com/investors',
  RNO: 'https://www.renaultgroup.com/en/investors',
  RTO: 'https://www.rentokil-initial.com/investors',
  REP: 'https://www.repsol.com/en/shareholders-and-investors',
  RHM: 'https://www.rheinmetall.com/en/investor-relations',
  RMV: 'https://www.rightmove.co.uk/corporate/investors',
  'RR.': 'https://www.rolls-royce.com/investors.aspx',
  RYA: 'https://investor.ryanair.com',
  SAMPO: 'https://www.sampo.com/investors',
  SAND: 'https://www.sandvik.com/investors',
  SU: 'https://www.se.com/ww/en/about-us/investor-relations',
  SDR: 'https://www.schroders.com/en/investor-relations',
  SGRO: 'https://www.segro.com/investors',
  SGSN: 'https://www.sgs.com/en/investors',
  SHL: 'https://www.siemens-healthineers.com/investor-relations',
  ENR: 'https://www.siemens-energy.com/global/en/company/investor-relations.html',
  'SN.': 'https://www.smith-nephew.com/en/investors',
  SMIN: 'https://www.smiths.com/investors',
  GLE: 'https://investors.societegenerale.com/en',
  'SW.PA': 'https://www.sodexo.com/home/finance.html',  // Sodexo (France)
  SOLB: 'https://www.solvay.com/en/investors',
  SOON: 'https://www.sonova.com/en/investors',
  SPX: 'https://www.spiraxgroup.com/investors',
  STMN: 'https://www.straumann.com/group/en/investor-relations.html',
  SY1: 'https://www.symrise.com/investors',
  TATE: 'https://www.tateandlyle.com/investors',
  TEP: 'https://www.teleperformance.com/en-us/investors',
  TEMN: 'https://www.temenos.com/investors',
  TEN: 'https://www.tenaris.com/en/investors',
  TRN: 'https://www.terna.it/en/investor-relations',
  'TSCO.L': 'https://www.tescoplc.com/investors',  // Tesco (UK)
  HO: 'https://www.thalesgroup.com/en/investors',
  TOM: 'https://www.tomra.com/investors',
  TRYG: 'https://tryg.com/en/investors',
  UBI: 'https://www.ubisoft.com/en-us/company/investor-relations',
  UMI: 'https://www.umicore.com/investors',
  URW: 'https://www.urw.com/en/investors',
  UPM: 'https://www.upm.com/investors',
  'FR.PA': 'https://www.valeo.com/en/investors',  // Valeo (France)
  VIE: 'https://www.veolia.com/en/investors',
  'DG.PA': 'https://www.vinci.com/vinci.nsf/en/investors.htm',  // Vinci (France)
  VIV: 'https://www.vivendi.com/en/investors',
  VNA: 'https://investoren.vonovia.de/en',
  WEIR: 'https://www.global.weir/investors',
  WTB: 'https://www.whitbread.co.uk/investors',
  WKL: 'https://www.wolterskluwer.com/en/investors',
  WLN: 'https://investors.worldline.com',
  WPP: 'https://www.wpp.com/investors',
  YAR: 'https://www.yara.com/investor-relations',

  // Additional European companies
  SCMN: 'https://www.swisscom.ch/en/about/investors.html',
  SLHN: 'https://www.swisslife.com/en/home/investors.html',
  CNH: 'https://www.cnhindustrial.com/en-us/investors',
  NET: 'https://cloudflare.net/',
  SHOP: 'https://investors.shopify.com',
  LYFT: 'https://investor.lyft.com',
  SNAP: 'https://investor.snap.com',
  PINS: 'https://investor.pinterestinc.com',
  SPOT: 'https://investors.spotify.com',
  ZM: 'https://investors.zoom.us',
  DOCU: 'https://investor.docusign.com',
  ZS: 'https://ir.zscaler.com',
  OKTA: 'https://investor.okta.com',
  SNOW: 'https://investors.snowflake.com',
  MDB: 'https://investors.mongodb.com',
  RBLX: 'https://ir.roblox.com',
  U: 'https://investors.unity.com',
  ETSY: 'https://investors.etsy.com',
  APP: 'https://investors.applovin.com',

  // ============================================
  // Additional STOXX Europe 600 (101-300)
  // ============================================

  // UK Companies
  BNZL: 'https://www.bunzl.com/investors/',
  BRBY: 'https://www.burberryplc.com/investors',
  'CCL.L': 'https://www.carnivalcorp.com/investor-relations',  // Carnival PLC (UK)
  CNA: 'https://www.centrica.com/investors/',
  CCEP: 'https://ir.cocacolaep.com/',
  CCC: 'https://www.computacenter.com/investor-relations',
  CTEC: 'https://www.convatecgroup.com/investors/',
  CWK: 'https://www.cranswick.plc.uk/investors/',
  DLN: 'https://www.derwentlondon.com/investors',
  DPLM: 'https://www.diplomaplc.com/investors/',
  'DLG.L': 'https://www.directlinegroup.co.uk/en/investors.html',  // Direct Line (UK)
  'DOM.L': 'https://investors.dominos.co.uk/',  // Domino's Pizza Group (UK)
  DRX: 'https://www.drax.com/investors/',
  EZJ: 'https://corporate.easyjet.com/investors',
  ENOG: 'https://www.energean.com/investors/',
  ENT: 'https://entaingroup.com/investor-relations/',
  GAW: 'https://investor.games-workshop.com/',
  GFTU: 'https://www.graftonplc.com/investors/',
  GRG: 'https://corporate.greggs.co.uk/investors',
  HLN: 'https://www.haleon.com/investors/',
  HBR: 'https://www.harbourenergy.com/investors/',
  HSX: 'https://www.hiscoxgroup.com/investors',
  HWDN: 'https://www.howdengroupplc.com/investors',
  INCH: 'https://www.inchcape.com/investors/',
  ICP: 'https://www.icgam.com/shareholders/',
  INVP: 'https://www.investec.com/en_gb/welcome-to-investec/investor-relations.html',
  ITV: 'https://www.itvplc.com/investors',
  'JD.': 'https://www.jdplc.com/investor-relations',
  SBRY: 'https://www.about.sainsburys.co.uk/investors',
  LAND: 'https://landsec.com/investors',
  ROO: 'https://corporate.deliveroo.co.uk/investors/',

  // Germany Companies
  BZU: 'https://www.buzzi.com/en/investors',  // Buzzi (Italy, but listed)
  CBK: 'https://investor-relations.commerzbank.com/en/',
  '1COV': 'https://www.covestro.com/en/investors',
  EVD: 'https://corporate.eventim.de/en/investor-relations/',
  DTG: 'https://www.daimlertruck.com/en/investors',
  DHER: 'https://ir.deliveryhero.com/',
  GXI: 'https://www.gerresheimer.com/en/company/investor-relations',
  HNR1: 'https://www.hannover-re.com/en/investors/',
  HLAG: 'https://www.hapag-lloyd.com/en/company/ir.html',
  HFG: 'https://ir.hellofreshgroup.com/',
  BOSS: 'https://group.hugoboss.com/en/investors',
  LXS: 'https://lanxess.com/en/Investors',
  KBX: 'https://www.knorr-bremse.com/en/investor-relations/',
  FNTN: 'https://www.freenet-group.de/investor-relations/en/',
  SDF: 'https://www.kpluss.com/en-us/investor-relations/',

  // France Companies
  ACA: 'https://www.credit-agricole.com/en/finance',
  CA: 'https://www.carrefour.com/en/finance',
  COV: 'https://www.covivio.eu/en/investors/',
  EDEN: 'https://www.edenred.com/en/investors-shareholders',
  FGR: 'https://www.eiffage.com/en/finance',
  ERA: 'https://www.eramet.com/en/investors',
  'RF.PA': 'https://www.eurazeo.com/en/shareholders-investors',  // Eurazeo (France)
  FRVIA: 'https://www.forvia.com/investors',
  GFC: 'https://www.gecina.fr/en/investors',
  ICAD: 'https://www.icade.fr/en/finance',
  OR: 'https://www.loreal-finance.com/en/',
  FDJ: 'https://www.groupefdj.com/en/investors/',

  // Italy Companies
  CPR: 'https://www.camparigroup.com/en/page/investors',
  DLG: 'https://www.delonghigroup.com/en/investors',
  INW: 'https://www.inwit.it/en/investors/',
  'IP.MI': 'https://www.interpumpgroup.it/en/investor-relations',  // Interpump (Italy)
  IG: 'https://www.italgas.it/en/investors/',
  IVG: 'https://www.ivecogroup.com/investors',
  HER: 'https://eng.gruppohera.it/group/investors',

  // Spain Companies
  ENG: 'https://www.enagas.es/en/investors/',
  ELE: 'https://www.endesa.com/en/shareholders-and-investors',
  FDR: 'https://www.fluidra.com/shareholders-investors',
  GRF: 'https://www.grifols.com/en/investors',
  IDR: 'https://www.indracompany.com/en/indra/shareholders-investors',

  // Switzerland Companies
  CLN: 'https://www.clariant.com/en/Investors',
  CCH: 'https://www.coca-colahellenic.com/en/investor-relations',
  DSFIR: 'https://www.dsm-firmenich.com/corporate/investors.html',
  GALD: 'https://www.galderma.com/investors',
  HELN: 'https://www.helvetia.com/corporate/en/investor-relations.html',
  IWG: 'https://www.iwgplc.com/en-gb/investors',

  // Netherlands Companies
  CVC: 'https://www.cvc.com/shareholders/',
  EXO: 'https://www.exor.com/pages/investors-media/investor-relations',
  FUR: 'https://www.fugro.com/investors',
  HEIO: 'https://www.heinekenholding.com/',
  IMCD: 'https://www.imcdgroup.com/en/investors',
  JDEP: 'https://www.jdepeets.com/investors/',

  // Denmark Companies
  'CARL B': 'https://www.carlsberggroup.com/investor-relations/',
  'COLO B': 'https://www.coloplast.com/investor-relations',
  GN: 'https://www.gn.com/investors',
  ISS: 'https://inv.issworld.com/',
  JYSK: 'https://www.jyskebank.com/investorrelations',
  PNDORA: 'https://pandoragroup.com/investor',

  // Sweden Companies
  CAST: 'https://www.castellum.com/investors/',
  DOM: 'https://www.dometicgroup.com/en/investors',
  'ELUX B': 'https://www.electroluxgroup.com/en/category/investors/',
  'EKTA B': 'https://www.elekta.com/investors/',
  'EMBRAC B': 'https://embracer.com/investors/',
  EVO: 'https://www.evolution.com/investors/',
  'GETI B': 'https://www.getinge.com/int/company/investors/',
  'HPOL B': 'https://www.hexpol.com/investors/',
  'HUSQ B': 'https://www.husqvarnagroup.com/en/investors',
  INVEA: 'https://www.investorab.com/investors-media/',
  'KINV B': 'https://www.kinnevik.com/investors',
  'LIFCO B': 'https://lifco.se/investors/',
  'BALD B': 'https://en.balder.se/investor-relations',

  // Norway Companies
  DNB: 'https://www.ir.dnb.no/',
  GJF: 'https://www.gjensidige.no/group/investor-relations',
  KOG: 'https://www.kongsberg.com/investors/',

  // Finland Companies
  ELISA: 'https://elisa.com/corporate/investors/',
  FSKRS: 'https://fiskarsgroup.com/investors/',
  FORTUM: 'https://www.fortum.com/investors',
  HUH1V: 'https://www.huhtamaki.com/en/investors/',
  KESKOB: 'https://www.kesko.fi/en/investor/',
  KOJAMO: 'https://kojamo.fi/en/investors/',
  KCR: 'https://www.konecranes.com/investors',

  // Belgium Companies
  COFB: 'https://www.cofinimmo.com/investors/',
  DIE: 'https://www.dieterengroup.com/investors',
  ELI: 'https://www.eliagroup.eu/investor-relations',
  FAGR: 'https://investors.fagron.com/',
  GBLB: 'https://www.gbl.be/en/investors',
  LOTB: 'https://www.lotusbakeries.com/ir-home',

  // Ireland Companies
  DCC: 'https://www.dcc.ie/investors',
  GLB: 'https://www.glanbia.com/investors',

  // Portugal Companies
  GALP: 'https://www.galp.com/corp/en/investors',

  // Poland Companies
  DNP: 'https://grupadino.pl/en/investor-relations/',

  // Greece Companies
  EUROB: 'https://www.eurobank.gr/en/group/investor-relations',

  // Austria Companies
  EBS: 'https://www.erstegroup.com/en/investors',
  // Note: ANDR (Andritz) already defined above
  BAWAG: 'https://www.bawaggroup.com/IR',

  // ============================================
  // Additional STOXX Europe 600 (1-100)
  // ============================================

  // Germany (1-100)
  '1U1': 'https://www.1und1.ag/investor-relations-en',
  AIXA: 'https://www.aixtron.com/en/investors',
  NDA: 'https://www.aurubis.com/en/investor-relations',
  BC8: 'https://www.bechtle.com/en/about-bechtle/investors',
  GBF: 'https://www.bilfinger.com/en/investor-relations/',
  BNR: 'https://corporate.brenntag.com/en/investor-relations/',
  // Note: RHM (Rheinmetall) already defined above

  // UK
  ABDN: 'https://www.abrdn.com/corporate/investors',
  'ADM.L': 'https://admiralgroup.co.uk/investor-relations',  // Admiral Group
  ABF: 'https://www.abf.co.uk/investors',
  AUTO: 'https://plc.autotrader.co.uk/investors/',
  BME: 'https://www.bandmretail.com/investors',
  BAB: 'https://www.babcockinternational.com/investors/',
  'BA.': 'https://www.baesystems.com/en/investors',
  BDEV: 'https://www.barrattredrow.com/investors',
  BEZ: 'https://www.beazley.com/en-001/about-us/investor-relations',
  BWY: 'https://www.bellwayplc.co.uk/investor-centre',
  BKG: 'https://www.berkeleygroup.co.uk/investors',
  BYG: 'https://corporate.bigyellow.co.uk/investors',
  BLND: 'https://www.britishland.com/investors',
  'BT.A': 'https://www.bt.com/about/investors',

  // France
  'ADP.PA': 'https://www.parisaeroport.fr/en/group/finance',  // Aéroports de Paris (not US ADP)
  AF: 'https://www.airfranceklm.com/en/finance',
  AI: 'https://www.airliquide.com/investors',
  ALD: 'https://www.ayvens.com/en-cp/investors/',
  AMUN: 'https://about.amundi.com/investor-relations',
  BIM: 'https://www.biomerieux.com/en/investors',
  'BOL.PA': 'https://www.bollore.com/en/investors',
  EN: 'https://www.bouygues.com/en/finance-shareholders/',

  // Spain
  ANA: 'https://www.acciona.com/shareholders-investors/',
  ANE: 'https://www.acciona-energia.com/shareholders-investors/',
  SAB: 'https://www.grupobancosabadell.com/en/shareholders-and-investors/',
  BKT: 'https://www.bankinter.com/webcorporativa/en/shareholders-investors',

  // Italy
  'AMP.MI': 'https://corporate.amplifon.com/en/investors',
  BGN: 'https://www.bancagenerali.com/en/investor-relations',
  BMED: 'https://www.bancamediolanum.it/corp/investor-relations',
  BAMI: 'https://gruppo.bancobpm.it/en/investor-relations/',

  // Netherlands
  AALB: 'https://aalberts.com/investors',
  ARCAD: 'https://www.arcadis.com/en/investors',
  ASRNL: 'https://www.asrnl.com/investor-relations',
  BESI: 'https://www.besi.com/investor-relations/',

  // Switzerland
  BALN: 'https://www.baloise.com/en/home/investors.html',
  BARN: 'https://www.barry-callebaut.com/en-group/investors',
  BEAN: 'https://www.belimo.com/ch/en_GB/investor-relations',
  BUCN: 'https://www.bucherindustries.com/en/investors',

  // Sweden
  AAK: 'https://www.aak.com/investors/',
  'ASSA B': 'https://www.assaabloy.com/group/en/investors',
  'ATCO A': 'https://www.atlascopcogroup.com/en/investor-relations',
  'ATCO B': 'https://www.atlascopcogroup.com/en/investor-relations',
  BILL: 'https://www.billerud.com/investors',
  BOL: 'https://www.boliden.com/investor-relations',

  // Denmark
  MAERSK: 'https://www.maersk.com/investor-relations',
  'MAERSK A': 'https://www.maersk.com/investor-relations',
  'MAERSK B': 'https://www.maersk.com/investor-relations',
  AMBU: 'https://www.ambu.com/investors',

  // Belgium
  AVH: 'https://www.avh.be/en/investors',
  AGS: 'https://www.ageas.com/investors',
  AZE: 'https://www.azelis.com/investors',

  // Ireland
  AIBG: 'https://aib.ie/investorrelations',
  BIRG: 'https://investorrelations.bankofireland.com/',

  // Luxembourg
  APAM: 'https://www.aperam.com/investors/',
  AT1: 'https://www.aroundtown.de/investor-relations/',

  // Poland
  ALE: 'https://allegro.eu/investors',

  // Faroe Islands
  BAKKA: 'https://www.bakkafrost.com/en/investor-relations/',

  // ============================================
  // Swiss SPI (Additional Swiss stocks)
  // ============================================

  // Swiss Banks & Financials
  SQN: 'https://www.swissquote.com/sqweb/company/en/investors',
  EFGN: 'https://www.efginternational.com/shareholders-investors.html',
  VONN: 'https://www.vontobel.com/en-ch/about-vontobel/investor-relations/',
  CMBN: 'https://www.cembra.ch/en/investors',
  VALN: 'https://www.valiant.ch/en/about-us/investors',
  VZH: 'https://www.vzch.com/en/investors',
  BCVN: 'https://www.bcv.ch/en/About-us/Investor-relations',
  SGKN: 'https://www.sgkb.ch/en/investor-relations',
  BKBN: 'https://www.bekb.ch/en/investor-relations',
  THKB: 'https://www.tkb.ch/en/investor-relations',
  ZUGK: 'https://www.zugerkb.ch/en/investor-relations',
  GKB: 'https://www.gkb.ch/en/investor-relations',
  LLBN: 'https://www.llb.li/en/llb/investor-relations',
  LUKN: 'https://www.lukb.ch/en/investor-relations',
  BCGE: 'https://www.bcge.ch/en/investor-relations',

  // Swiss Real Estate
  SPRE: 'https://www.sps.swiss/en/investors',
  PSPN: 'https://www.psp.info/en/investors.html',
  MOBN: 'https://www.mobimo.ch/en/investors',
  ALLH: 'https://www.allreal.ch/en/investors',
  HIAG: 'https://www.hiag.com/en/investors',
  WARN: 'https://www.warteck-invest.ch/en/investor-relations',
  PEHN: 'https://www.peachproperty.com/en/investors',

  // Swiss Healthcare & Pharma
  MEDN: 'https://www.medacta.com/EN/investors',
  YPSN: 'https://www.ypsomed.com/yps/en/investors.html',
  GALN: 'https://www.galenica.com/en/investor-relations',
  BACH: 'https://www.bachem.com/company/investors/',
  DOTT: 'https://www.dfrgroup.swiss/en/investor-relations/',
  // Note: SIE conflicts with Siemens (Germany) - use SIEG for Siegfried if needed
  BION: 'https://www.bbbiotech.ch/en/investor-relations',

  // Swiss Industrials
  SUN: 'https://www.sulzer.com/en/investors',
  SFSG: 'https://www.sfs.biz/en/investors',
  HUBN: 'https://www.hubersuhner.com/en/company/investors',
  DMKN: 'https://www.dormakaba.com/en/investors',
  DAWG: 'https://www.datwyler.com/investors',
  IFCN: 'https://www.inficon.com/en/investors',
  ACLN: 'https://www.accelleron-industries.com/investors',
  SIGG: 'https://www.sig.biz/investors',
  BOBNN: 'https://www.bobst.com/en/investor-relations',
  KOMAX: 'https://www.komaxgroup.com/en/Investors',
  ARYN: 'https://www.aryzta.com/investors',
  INRN: 'https://www.interroll.com/investors',
  GURN: 'https://www.gurit.com/en/investors',
  LISP: 'https://www.landisgyr.com/investors/',
  COTN: 'https://www.comet-group.com/en/investors',
  KARN: 'https://www.kardex.com/en/investors',
  ZEHN: 'https://www.zehndergroup.com/en/investor-relations',
  VETN: 'https://www.vetropack.com/en/investors/',
  FORN: 'https://www.forbo.com/corporate/en-gl/investors/',
  MBTN: 'https://www.meyerburger.com/en/investors',

  // Swiss Consumer & Services
  DKSH: 'https://www.dksh.com/global-en/investors',
  AVOL: 'https://www.avoltaworld.com/en/investors',
  EMMI: 'https://group.emmi.com/en/investors',
  BELL: 'https://www.bellfoodgroup.com/en/investors/',
  ORNA: 'https://www.orior.ch/en/investors/',
  HBLN: 'https://www.hochdorf.com/en/investors',
  VBSN: 'https://www.valora.com/en/investors/',

  // Swiss Technology
  ALSN: 'https://www.also.com/ec/cms5/en_6000/6000/investor-relations/index.jsp',
  SOFTG: 'https://www.softwareone.com/en/investors',
  UHRN: 'https://www.u-blox.com/en/investors',
  SENS: 'https://www.sensirion.com/en/company/investors/',

  // Swiss Energy & Transport
  BKW: 'https://www.bkw.ch/en/about-us/investor-relations',
  ROMN: 'https://www.romande-energie.ch/investisseurs',
  FHZN: 'https://www.flughafen-zuerich.ch/en/company/investors',

  // Swiss Other
  APGN: 'https://www.apgsga.ch/en/investor-relations/',
  UHR: 'https://www.swatchgroup.com/en/investors',
  VAHN: 'https://www.vaudoise.ch/en/group/investor-relations',

  // ============================================
  // Additional European companies (from ticker map)
  // ============================================

  // Spain
  BBVA: 'https://www.bbva.com/en/shareholders-and-investors/',

  // Austria
  OMV: 'https://www.omv.com/en/investors',
  VOE: 'https://www.voestalpine.com/group/en/investors/',

  // Norway
  MOWI: 'https://mowi.com/investors/',
  ORK: 'https://www.orkla.com/investors/',

  // Finland
  NESTE: 'https://www.neste.com/investors',
  STERV: 'https://www.stora-enso.com/investors',

  // Netherlands
  ABN: 'https://www.abnamro.com/en/investor-relations',
  UNA: 'https://www.unilever.com/investor-relations/',

  // Sweden
  'VOLV-B': 'https://www.volvogroup.com/en/investors.html',
  'SEB-A': 'https://sebgroup.com/about-seb/investor-relations',
  'SKA-B': 'https://www.skanska.com/investors/',
  'INVE-B': 'https://www.investorab.com/investors-media/',

  // UK (additional)
  NWG: 'https://www.natwestgroup.com/investors.html',

  // Germany (additional)
  TKA: 'https://www.thyssenkrupp.com/en/investors',
  PAH3: 'https://www.porsche-se.com/en/investor-relations',

  // France (additional)
  ML: 'https://www.michelin.com/en/finance/',
  'ATO.PA': 'https://www.atos.net/en/investors',
  RBO: 'https://finance.rfrochebobois.com/',

  // Italy (additional)
  SRG: 'https://www.snamretegas.it/en/investor-relations/',
  SPM: 'https://www.saipem.com/en/investors',
  MB: 'https://www.mediobanca.com/en/investor-relations.html',

  // Ireland
  CRG: 'https://www.crh.com/investors',
};

/**
 * Get investor relations URL for a stock ticker
 * Returns null if no IR link is known for this ticker
 */
export function getCompanyIRUrl(ticker: string): string | null {
  const upperTicker = ticker.toUpperCase();
  return TICKER_TO_IR[upperTicker] || null;
}
