// S&P 500 stocks list (all ~503 components as of January 2025)
export interface Stock {
  ticker: string;
  name: string;
}

export const SP500_STOCKS: Stock[] = [
  { ticker: 'A', name: 'Agilent Technologies' },
  { ticker: 'AAPL', name: 'Apple' },
  { ticker: 'ABBV', name: 'AbbVie' },
  { ticker: 'ABNB', name: 'Airbnb' },
  { ticker: 'ABT', name: 'Abbott Laboratories' },
  { ticker: 'ACGL', name: 'Arch Capital Group' },
  { ticker: 'ACN', name: 'Accenture' },
  { ticker: 'ADBE', name: 'Adobe' },
  { ticker: 'ADI', name: 'Analog Devices' },
  { ticker: 'ADM', name: 'Archer Daniels Midland' },
  { ticker: 'ADP', name: 'Automatic Data Processing' },
  { ticker: 'ADSK', name: 'Autodesk' },
  { ticker: 'AEE', name: 'Ameren' },
  { ticker: 'AEP', name: 'American Electric Power' },
  { ticker: 'AES', name: 'AES Corporation' },
  { ticker: 'AFL', name: 'Aflac' },
  { ticker: 'AIG', name: 'American International Group' },
  { ticker: 'AIZ', name: 'Assurant' },
  { ticker: 'AJG', name: 'Arthur J. Gallagher' },
  { ticker: 'AKAM', name: 'Akamai Technologies' },
  { ticker: 'ALB', name: 'Albemarle' },
  { ticker: 'ALGN', name: 'Align Technology' },
  { ticker: 'ALL', name: 'Allstate' },
  { ticker: 'ALLE', name: 'Allegion' },
  { ticker: 'AMAT', name: 'Applied Materials' },
  { ticker: 'AMCR', name: 'Amcor' },
  { ticker: 'AMD', name: 'Advanced Micro Devices' },
  { ticker: 'AME', name: 'Ametek' },
  { ticker: 'AMGN', name: 'Amgen' },
  { ticker: 'AMP', name: 'Ameriprise Financial' },
  { ticker: 'AMT', name: 'American Tower' },
  { ticker: 'AMZN', name: 'Amazon' },
  { ticker: 'ANET', name: 'Arista Networks' },
  { ticker: 'AON', name: 'Aon' },
  { ticker: 'AOS', name: 'A. O. Smith' },
  { ticker: 'APA', name: 'APA Corporation' },
  { ticker: 'APD', name: 'Air Products & Chemicals' },
  { ticker: 'APH', name: 'Amphenol' },
  { ticker: 'APO', name: 'Apollo Global Management' },
  { ticker: 'APP', name: 'AppLovin' },
  { ticker: 'APTV', name: 'Aptiv' },
  { ticker: 'ARE', name: 'Alexandria Real Estate' },
  { ticker: 'ARES', name: 'Ares Management' },
  { ticker: 'ATO', name: 'Atmos Energy' },
  { ticker: 'AVB', name: 'AvalonBay Communities' },
  { ticker: 'AVGO', name: 'Broadcom' },
  { ticker: 'AVY', name: 'Avery Dennison' },
  { ticker: 'AWK', name: 'American Water Works' },
  { ticker: 'AXON', name: 'Axon Enterprise' },
  { ticker: 'AXP', name: 'American Express' },
  { ticker: 'AZO', name: 'AutoZone' },
  { ticker: 'BA', name: 'Boeing' },
  { ticker: 'BAC', name: 'Bank of America' },
  { ticker: 'BALL', name: 'Ball Corporation' },
  { ticker: 'BAX', name: 'Baxter International' },
  { ticker: 'BBY', name: 'Best Buy' },
  { ticker: 'BDX', name: 'Becton Dickinson' },
  { ticker: 'BEN', name: 'Franklin Resources' },
  { ticker: 'BF.B', name: 'Brown-Forman' },
  { ticker: 'BG', name: 'Bunge Global' },
  { ticker: 'BIIB', name: 'Biogen' },
  { ticker: 'BK', name: 'Bank of New York Mellon' },
  { ticker: 'BKNG', name: 'Booking Holdings' },
  { ticker: 'BKR', name: 'Baker Hughes' },
  { ticker: 'BLK', name: 'BlackRock' },
  { ticker: 'BLDR', name: 'Builders FirstSource' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb' },
  { ticker: 'BR', name: 'Broadridge Financial' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway' },
  { ticker: 'BRO', name: 'Brown & Brown' },
  { ticker: 'BSX', name: 'Boston Scientific' },
  { ticker: 'BX', name: 'Blackstone' },
  { ticker: 'BXP', name: 'BXP' },
  { ticker: 'C', name: 'Citigroup' },
  { ticker: 'CAG', name: 'Conagra Brands' },
  { ticker: 'CAH', name: 'Cardinal Health' },
  { ticker: 'CARR', name: 'Carrier Global' },
  { ticker: 'CAT', name: 'Caterpillar' },
  { ticker: 'CB', name: 'Chubb' },
  { ticker: 'CBOE', name: 'Cboe Global Markets' },
  { ticker: 'CBRE', name: 'CBRE Group' },
  { ticker: 'CCI', name: 'Crown Castle' },
  { ticker: 'CCL', name: 'Carnival' },
  { ticker: 'CDNS', name: 'Cadence Design Systems' },
  { ticker: 'CDW', name: 'CDW' },
  { ticker: 'CE', name: 'Celanese' },
  { ticker: 'CEG', name: 'Constellation Energy' },
  { ticker: 'CF', name: 'CF Industries' },
  { ticker: 'CFG', name: 'Citizens Financial Group' },
  { ticker: 'CHD', name: 'Church & Dwight' },
  { ticker: 'CHRW', name: 'C.H. Robinson' },
  { ticker: 'CHTR', name: 'Charter Communications' },
  { ticker: 'CI', name: 'Cigna Group' },
  { ticker: 'CINF', name: 'Cincinnati Financial' },
  { ticker: 'CL', name: 'Colgate-Palmolive' },
  { ticker: 'CLX', name: 'Clorox' },
  { ticker: 'CMCSA', name: 'Comcast' },
  { ticker: 'CME', name: 'CME Group' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill' },
  { ticker: 'CMI', name: 'Cummins' },
  { ticker: 'CMS', name: 'CMS Energy' },
  { ticker: 'CNC', name: 'Centene' },
  { ticker: 'CNP', name: 'CenterPoint Energy' },
  { ticker: 'COF', name: 'Capital One' },
  { ticker: 'COIN', name: 'Coinbase Global' },
  { ticker: 'COO', name: 'Cooper Companies' },
  { ticker: 'COP', name: 'ConocoPhillips' },
  { ticker: 'COR', name: 'Cencora' },
  { ticker: 'COST', name: 'Costco Wholesale' },
  { ticker: 'CPAY', name: 'Corpay' },
  { ticker: 'CPB', name: 'Campbell Soup' },
  { ticker: 'CPRT', name: 'Copart' },
  { ticker: 'CPT', name: 'Camden Property Trust' },
  { ticker: 'CRH', name: 'CRH' },
  { ticker: 'CRL', name: 'Charles River Laboratories' },
  { ticker: 'CRM', name: 'Salesforce' },
  { ticker: 'CRWD', name: 'CrowdStrike' },
  { ticker: 'CSCO', name: 'Cisco Systems' },
  { ticker: 'CSGP', name: 'CoStar Group' },
  { ticker: 'CSX', name: 'CSX' },
  { ticker: 'CTAS', name: 'Cintas' },
  { ticker: 'CTRA', name: 'Coterra Energy' },
  { ticker: 'CTSH', name: 'Cognizant' },
  { ticker: 'CTVA', name: 'Corteva' },
  { ticker: 'CVNA', name: 'Carvana' },
  { ticker: 'CVS', name: 'CVS Health' },
  { ticker: 'CVX', name: 'Chevron' },
  { ticker: 'D', name: 'Dominion Energy' },
  { ticker: 'DAL', name: 'Delta Air Lines' },
  { ticker: 'DASH', name: 'DoorDash' },
  { ticker: 'DAY', name: 'Dayforce' },
  { ticker: 'DD', name: 'DuPont' },
  { ticker: 'DDOG', name: 'Datadog' },
  { ticker: 'DE', name: 'Deere & Co' },
  { ticker: 'DECK', name: 'Deckers Brands' },
  { ticker: 'DELL', name: 'Dell Technologies' },
  { ticker: 'DFS', name: 'Discover Financial' },
  { ticker: 'DG', name: 'Dollar General' },
  { ticker: 'DGX', name: 'Quest Diagnostics' },
  { ticker: 'DHI', name: 'D.R. Horton' },
  { ticker: 'DHR', name: 'Danaher' },
  { ticker: 'DIS', name: 'Walt Disney' },
  { ticker: 'DLR', name: 'Digital Realty Trust' },
  { ticker: 'DLTR', name: 'Dollar Tree' },
  { ticker: 'DOC', name: 'Healthpeak Properties' },
  { ticker: 'DOV', name: 'Dover Corporation' },
  { ticker: 'DOW', name: 'Dow' },
  { ticker: 'DPZ', name: "Domino's Pizza" },
  { ticker: 'DRI', name: 'Darden Restaurants' },
  { ticker: 'DTE', name: 'DTE Energy' },
  { ticker: 'DUK', name: 'Duke Energy' },
  { ticker: 'DVA', name: 'DaVita' },
  { ticker: 'DVN', name: 'Devon Energy' },
  { ticker: 'DXCM', name: 'Dexcom' },
  { ticker: 'EA', name: 'Electronic Arts' },
  { ticker: 'EBAY', name: 'eBay' },
  { ticker: 'ECL', name: 'Ecolab' },
  { ticker: 'ED', name: 'Consolidated Edison' },
  { ticker: 'EFX', name: 'Equifax' },
  { ticker: 'EG', name: 'Everest Group' },
  { ticker: 'EIX', name: 'Edison International' },
  { ticker: 'EL', name: 'Estee Lauder' },
  { ticker: 'ELV', name: 'Elevance Health' },
  { ticker: 'EME', name: 'EMCOR Group' },
  { ticker: 'EMR', name: 'Emerson Electric' },
  { ticker: 'ENPH', name: 'Enphase Energy' },
  { ticker: 'EOG', name: 'EOG Resources' },
  { ticker: 'EPAM', name: 'EPAM Systems' },
  { ticker: 'EQIX', name: 'Equinix' },
  { ticker: 'EQR', name: 'Equity Residential' },
  { ticker: 'EQT', name: 'EQT Corporation' },
  { ticker: 'ERIE', name: 'Erie Indemnity' },
  { ticker: 'ES', name: 'Eversource Energy' },
  { ticker: 'ESS', name: 'Essex Property Trust' },
  { ticker: 'ETN', name: 'Eaton' },
  { ticker: 'ETR', name: 'Entergy' },
  { ticker: 'EVRG', name: 'Evergy' },
  { ticker: 'EW', name: 'Edwards Lifesciences' },
  { ticker: 'EXC', name: 'Exelon' },
  { ticker: 'EXE', name: 'Expand Energy' },
  { ticker: 'EXPD', name: 'Expeditors International' },
  { ticker: 'EXPE', name: 'Expedia Group' },
  { ticker: 'EXR', name: 'Extra Space Storage' },
  { ticker: 'F', name: 'Ford Motor' },
  { ticker: 'FANG', name: 'Diamondback Energy' },
  { ticker: 'FAST', name: 'Fastenal' },
  { ticker: 'FCX', name: 'Freeport-McMoRan' },
  { ticker: 'FDS', name: 'FactSet' },
  { ticker: 'FDX', name: 'FedEx' },
  { ticker: 'FE', name: 'FirstEnergy' },
  { ticker: 'FFIV', name: 'F5' },
  { ticker: 'FICO', name: 'Fair Isaac' },
  { ticker: 'FIS', name: 'Fidelity National Information Services' },
  { ticker: 'FISV', name: 'Fiserv' },
  { ticker: 'FITB', name: 'Fifth Third Bancorp' },
  { ticker: 'FIX', name: 'Comfort Systems USA' },
  { ticker: 'FLT', name: 'FleetCor Technologies' },
  { ticker: 'FMC', name: 'FMC Corporation' },
  { ticker: 'FOX', name: 'Fox Corporation Class B' },
  { ticker: 'FOXA', name: 'Fox Corporation Class A' },
  { ticker: 'FRT', name: 'Federal Realty' },
  { ticker: 'FSLR', name: 'First Solar' },
  { ticker: 'FTNT', name: 'Fortinet' },
  { ticker: 'FTV', name: 'Fortive' },
  { ticker: 'GD', name: 'General Dynamics' },
  { ticker: 'GDDY', name: 'GoDaddy' },
  { ticker: 'GE', name: 'GE Aerospace' },
  { ticker: 'GEHC', name: 'GE HealthCare' },
  { ticker: 'GEN', name: 'Gen Digital' },
  { ticker: 'GEV', name: 'GE Vernova' },
  { ticker: 'GILD', name: 'Gilead Sciences' },
  { ticker: 'GIS', name: 'General Mills' },
  { ticker: 'GL', name: 'Globe Life' },
  { ticker: 'GLW', name: 'Corning' },
  { ticker: 'GM', name: 'General Motors' },
  { ticker: 'GNRC', name: 'Generac' },
  { ticker: 'GOOG', name: 'Alphabet Class C' },
  { ticker: 'GOOGL', name: 'Alphabet Class A' },
  { ticker: 'GPC', name: 'Genuine Parts Company' },
  { ticker: 'GPN', name: 'Global Payments' },
  { ticker: 'GRMN', name: 'Garmin' },
  { ticker: 'GS', name: 'Goldman Sachs' },
  { ticker: 'GWW', name: 'W.W. Grainger' },
  { ticker: 'HAL', name: 'Halliburton' },
  { ticker: 'HAS', name: 'Hasbro' },
  { ticker: 'HBAN', name: 'Huntington Bancshares' },
  { ticker: 'HCA', name: 'HCA Healthcare' },
  { ticker: 'HD', name: 'Home Depot' },
  { ticker: 'HES', name: 'Hess Corporation' },
  { ticker: 'HIG', name: 'Hartford Financial' },
  { ticker: 'HII', name: 'Huntington Ingalls' },
  { ticker: 'HLT', name: 'Hilton Worldwide' },
  { ticker: 'HOLX', name: 'Hologic' },
  { ticker: 'HON', name: 'Honeywell' },
  { ticker: 'HOOD', name: 'Robinhood Markets' },
  { ticker: 'HPE', name: 'Hewlett Packard Enterprise' },
  { ticker: 'HPQ', name: 'HP' },
  { ticker: 'HRL', name: 'Hormel Foods' },
  { ticker: 'HSIC', name: 'Henry Schein' },
  { ticker: 'HST', name: 'Host Hotels & Resorts' },
  { ticker: 'HSY', name: 'Hershey' },
  { ticker: 'HUBB', name: 'Hubbell' },
  { ticker: 'HUM', name: 'Humana' },
  { ticker: 'HWM', name: 'Howmet Aerospace' },
  { ticker: 'IBM', name: 'IBM' },
  { ticker: 'ICE', name: 'Intercontinental Exchange' },
  { ticker: 'IDXX', name: 'Idexx Laboratories' },
  { ticker: 'IEX', name: 'IDEX Corporation' },
  { ticker: 'IFF', name: 'International Flavors & Fragrances' },
  { ticker: 'INCY', name: 'Incyte' },
  { ticker: 'INTC', name: 'Intel' },
  { ticker: 'INTU', name: 'Intuit' },
  { ticker: 'INVH', name: 'Invitation Homes' },
  { ticker: 'IP', name: 'International Paper' },
  { ticker: 'IPG', name: 'Interpublic Group' },
  { ticker: 'IQV', name: 'IQVIA' },
  { ticker: 'IR', name: 'Ingersoll Rand' },
  { ticker: 'IRM', name: 'Iron Mountain' },
  { ticker: 'ISRG', name: 'Intuitive Surgical' },
  { ticker: 'IT', name: 'Gartner' },
  { ticker: 'ITW', name: 'Illinois Tool Works' },
  { ticker: 'IVZ', name: 'Invesco' },
  { ticker: 'J', name: 'Jacobs Solutions' },
  { ticker: 'JBHT', name: 'J.B. Hunt' },
  { ticker: 'JBL', name: 'Jabil' },
  { ticker: 'JCI', name: 'Johnson Controls' },
  { ticker: 'JKHY', name: 'Jack Henry & Associates' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'JPM', name: 'JPMorgan Chase' },
  { ticker: 'K', name: 'Kellanova' },
  { ticker: 'KDP', name: 'Keurig Dr Pepper' },
  { ticker: 'KEY', name: 'KeyCorp' },
  { ticker: 'KEYS', name: 'Keysight Technologies' },
  { ticker: 'KHC', name: 'Kraft Heinz' },
  { ticker: 'KIM', name: 'Kimco Realty' },
  { ticker: 'KKR', name: 'KKR' },
  { ticker: 'KLAC', name: 'KLA' },
  { ticker: 'KMB', name: 'Kimberly-Clark' },
  { ticker: 'KMI', name: 'Kinder Morgan' },
  { ticker: 'KO', name: 'Coca-Cola' },
  { ticker: 'KR', name: 'Kroger' },
  { ticker: 'KVUE', name: 'Kenvue' },
  { ticker: 'L', name: 'Loews Corporation' },
  { ticker: 'LDOS', name: 'Leidos' },
  { ticker: 'LEN', name: 'Lennar' },
  { ticker: 'LH', name: 'LabCorp' },
  { ticker: 'LHX', name: 'L3Harris Technologies' },
  { ticker: 'LII', name: 'Lennox International' },
  { ticker: 'LIN', name: 'Linde' },
  { ticker: 'LKQ', name: 'LKQ Corporation' },
  { ticker: 'LLY', name: 'Eli Lilly' },
  { ticker: 'LMT', name: 'Lockheed Martin' },
  { ticker: 'LNT', name: 'Alliant Energy' },
  { ticker: 'LOW', name: "Lowe's" },
  { ticker: 'LRCX', name: 'Lam Research' },
  { ticker: 'LULU', name: 'Lululemon Athletica' },
  { ticker: 'LUV', name: 'Southwest Airlines' },
  { ticker: 'LVS', name: 'Las Vegas Sands' },
  { ticker: 'LW', name: 'Lamb Weston' },
  { ticker: 'LYB', name: 'LyondellBasell' },
  { ticker: 'LYV', name: 'Live Nation Entertainment' },
  { ticker: 'MA', name: 'Mastercard' },
  { ticker: 'MAA', name: 'Mid-America Apartment' },
  { ticker: 'MAR', name: 'Marriott International' },
  { ticker: 'MAS', name: 'Masco' },
  { ticker: 'MCD', name: "McDonald's" },
  { ticker: 'MCHP', name: 'Microchip Technology' },
  { ticker: 'MCK', name: 'McKesson' },
  { ticker: 'MCO', name: "Moody's" },
  { ticker: 'MDLZ', name: 'Mondelez International' },
  { ticker: 'MDT', name: 'Medtronic' },
  { ticker: 'MET', name: 'MetLife' },
  { ticker: 'META', name: 'Meta Platforms' },
  { ticker: 'MGM', name: 'MGM Resorts' },
  { ticker: 'MKC', name: 'McCormick & Company' },
  { ticker: 'MKTX', name: 'MarketAxess' },
  { ticker: 'MLM', name: 'Martin Marietta Materials' },
  { ticker: 'MMC', name: 'Marsh & McLennan' },
  { ticker: 'MMM', name: '3M Company' },
  { ticker: 'MNST', name: 'Monster Beverage' },
  { ticker: 'MO', name: 'Altria Group' },
  { ticker: 'MOH', name: 'Molina Healthcare' },
  { ticker: 'MOS', name: 'Mosaic Company' },
  { ticker: 'MPC', name: 'Marathon Petroleum' },
  { ticker: 'MPWR', name: 'Monolithic Power Systems' },
  { ticker: 'MRK', name: 'Merck' },
  { ticker: 'MRNA', name: 'Moderna' },
  { ticker: 'MS', name: 'Morgan Stanley' },
  { ticker: 'MSCI', name: 'MSCI' },
  { ticker: 'MSFT', name: 'Microsoft' },
  { ticker: 'MSI', name: 'Motorola Solutions' },
  { ticker: 'MTB', name: 'M&T Bank' },
  { ticker: 'MTCH', name: 'Match Group' },
  { ticker: 'MTD', name: 'Mettler Toledo' },
  { ticker: 'MU', name: 'Micron Technology' },
  { ticker: 'NCLH', name: 'Norwegian Cruise Line' },
  { ticker: 'NDAQ', name: 'Nasdaq' },
  { ticker: 'NDSN', name: 'Nordson Corporation' },
  { ticker: 'NEE', name: 'NextEra Energy' },
  { ticker: 'NEM', name: 'Newmont' },
  { ticker: 'NFLX', name: 'Netflix' },
  { ticker: 'NI', name: 'NiSource' },
  { ticker: 'NKE', name: 'Nike' },
  { ticker: 'NOC', name: 'Northrop Grumman' },
  { ticker: 'NOW', name: 'ServiceNow' },
  { ticker: 'NRG', name: 'NRG Energy' },
  { ticker: 'NSC', name: 'Norfolk Southern' },
  { ticker: 'NTAP', name: 'NetApp' },
  { ticker: 'NTRS', name: 'Northern Trust' },
  { ticker: 'NUE', name: 'Nucor' },
  { ticker: 'NVDA', name: 'NVIDIA' },
  { ticker: 'NVR', name: 'NVR' },
  { ticker: 'NWS', name: 'News Corp Class B' },
  { ticker: 'NWSA', name: 'News Corp Class A' },
  { ticker: 'NXPI', name: 'NXP Semiconductors' },
  { ticker: 'O', name: 'Realty Income' },
  { ticker: 'ODFL', name: 'Old Dominion Freight' },
  { ticker: 'OKE', name: 'ONEOK' },
  { ticker: 'OMC', name: 'Omnicom Group' },
  { ticker: 'ON', name: 'ON Semiconductor' },
  { ticker: 'ORCL', name: 'Oracle' },
  { ticker: 'ORLY', name: "O'Reilly Automotive" },
  { ticker: 'OTIS', name: 'Otis Worldwide' },
  { ticker: 'OXY', name: 'Occidental Petroleum' },
  { ticker: 'PANW', name: 'Palo Alto Networks' },
  { ticker: 'PARA', name: 'Paramount Global' },
  { ticker: 'PAYC', name: 'Paycom' },
  { ticker: 'PAYX', name: 'Paychex' },
  { ticker: 'PCAR', name: 'PACCAR' },
  { ticker: 'PCG', name: 'PG&E Corporation' },
  { ticker: 'PEG', name: 'Public Service Enterprise' },
  { ticker: 'PEP', name: 'PepsiCo' },
  { ticker: 'PFE', name: 'Pfizer' },
  { ticker: 'PFG', name: 'Principal Financial' },
  { ticker: 'PG', name: 'Procter & Gamble' },
  { ticker: 'PGR', name: 'Progressive' },
  { ticker: 'PH', name: 'Parker Hannifin' },
  { ticker: 'PHM', name: 'PulteGroup' },
  { ticker: 'PKG', name: 'Packaging Corporation' },
  { ticker: 'PLD', name: 'Prologis' },
  { ticker: 'PLTR', name: 'Palantir Technologies' },
  { ticker: 'PM', name: 'Philip Morris International' },
  { ticker: 'PNC', name: 'PNC Financial Services' },
  { ticker: 'PNR', name: 'Pentair' },
  { ticker: 'PNW', name: 'Pinnacle West' },
  { ticker: 'PODD', name: 'Insulet Corporation' },
  { ticker: 'POOL', name: 'Pool Corporation' },
  { ticker: 'PPG', name: 'PPG Industries' },
  { ticker: 'PPL', name: 'PPL Corporation' },
  { ticker: 'PRU', name: 'Prudential Financial' },
  { ticker: 'PSA', name: 'Public Storage' },
  { ticker: 'PSX', name: 'Phillips 66' },
  { ticker: 'PTC', name: 'PTC' },
  { ticker: 'PWR', name: 'Quanta Services' },
  { ticker: 'PYPL', name: 'PayPal Holdings' },
  { ticker: 'QCOM', name: 'Qualcomm' },
  { ticker: 'RCL', name: 'Royal Caribbean' },
  { ticker: 'REG', name: 'Regency Centers' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals' },
  { ticker: 'RF', name: 'Regions Financial' },
  { ticker: 'RJF', name: 'Raymond James Financial' },
  { ticker: 'RL', name: 'Ralph Lauren' },
  { ticker: 'RMD', name: 'ResMed' },
  { ticker: 'ROK', name: 'Rockwell Automation' },
  { ticker: 'ROL', name: 'Rollins' },
  { ticker: 'ROP', name: 'Roper Technologies' },
  { ticker: 'ROST', name: 'Ross Stores' },
  { ticker: 'RSG', name: 'Republic Services' },
  { ticker: 'RTX', name: 'RTX' },
  { ticker: 'RVTY', name: 'Revvity' },
  { ticker: 'SBAC', name: 'SBA Communications' },
  { ticker: 'SBUX', name: 'Starbucks' },
  { ticker: 'SCHW', name: 'Charles Schwab' },
  { ticker: 'SHW', name: 'Sherwin-Williams' },
  { ticker: 'SJM', name: 'J.M. Smucker' },
  { ticker: 'SLB', name: 'Schlumberger' },
  { ticker: 'SMCI', name: 'Super Micro Computer' },
  { ticker: 'SNA', name: 'Snap-on' },
  { ticker: 'SNPS', name: 'Synopsys' },
  { ticker: 'SO', name: 'Southern Company' },
  { ticker: 'SOLV', name: 'Solventum' },
  { ticker: 'SPG', name: 'Simon Property Group' },
  { ticker: 'SPGI', name: 'S&P Global' },
  { ticker: 'SRE', name: 'Sempra Energy' },
  { ticker: 'STE', name: 'Steris' },
  { ticker: 'STLD', name: 'Steel Dynamics' },
  { ticker: 'STT', name: 'State Street' },
  { ticker: 'STX', name: 'Seagate Technology' },
  { ticker: 'STZ', name: 'Constellation Brands' },
  { ticker: 'SW', name: 'Smurfit WestRock' },
  { ticker: 'SWK', name: 'Stanley Black & Decker' },
  { ticker: 'SWKS', name: 'Skyworks Solutions' },
  { ticker: 'SYF', name: 'Synchrony Financial' },
  { ticker: 'SYK', name: 'Stryker' },
  { ticker: 'SYY', name: 'Sysco' },
  { ticker: 'T', name: 'AT&T' },
  { ticker: 'TAP', name: 'Molson Coors' },
  { ticker: 'TDG', name: 'TransDigm Group' },
  { ticker: 'TDY', name: 'Teledyne Technologies' },
  { ticker: 'TECH', name: 'Bio-Techne' },
  { ticker: 'TEL', name: 'TE Connectivity' },
  { ticker: 'TER', name: 'Teradyne' },
  { ticker: 'TFC', name: 'Truist Financial' },
  { ticker: 'TGT', name: 'Target' },
  { ticker: 'TJX', name: 'TJX Companies' },
  { ticker: 'TKO', name: 'TKO Group Holdings' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific' },
  { ticker: 'TMUS', name: 'T-Mobile US' },
  { ticker: 'TPL', name: 'Texas Pacific Land' },
  { ticker: 'TPR', name: 'Tapestry' },
  { ticker: 'TRGP', name: 'Targa Resources' },
  { ticker: 'TRMB', name: 'Trimble' },
  { ticker: 'TROW', name: 'T. Rowe Price' },
  { ticker: 'TRV', name: 'Travelers Companies' },
  { ticker: 'TSCO', name: 'Tractor Supply' },
  { ticker: 'TSLA', name: 'Tesla' },
  { ticker: 'TSN', name: 'Tyson Foods' },
  { ticker: 'TT', name: 'Trane Technologies' },
  { ticker: 'TTD', name: 'The Trade Desk' },
  { ticker: 'TTWO', name: 'Take-Two Interactive' },
  { ticker: 'TXT', name: 'Textron' },
  { ticker: 'TYL', name: 'Tyler Technologies' },
  { ticker: 'UAL', name: 'United Airlines' },
  { ticker: 'UBER', name: 'Uber Technologies' },
  { ticker: 'UDR', name: 'UDR' },
  { ticker: 'UHS', name: 'Universal Health Services' },
  { ticker: 'ULTA', name: 'Ulta Beauty' },
  { ticker: 'UNH', name: 'UnitedHealth Group' },
  { ticker: 'UNP', name: 'Union Pacific' },
  { ticker: 'UPS', name: 'United Parcel Service' },
  { ticker: 'URI', name: 'United Rentals' },
  { ticker: 'USB', name: 'U.S. Bancorp' },
  { ticker: 'V', name: 'Visa' },
  { ticker: 'VICI', name: 'Vici Properties' },
  { ticker: 'VLO', name: 'Valero Energy' },
  { ticker: 'VLTO', name: 'Veralto' },
  { ticker: 'VMC', name: 'Vulcan Materials' },
  { ticker: 'VRSK', name: 'Verisk Analytics' },
  { ticker: 'VRSN', name: 'Verisign' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals' },
  { ticker: 'VST', name: 'Vistra' },
  { ticker: 'VTR', name: 'Ventas' },
  { ticker: 'VTRS', name: 'Viatris' },
  { ticker: 'VZ', name: 'Verizon Communications' },
  { ticker: 'WAB', name: 'Wabtec' },
  { ticker: 'WAT', name: 'Waters Corporation' },
  { ticker: 'WBA', name: 'Walgreens Boots Alliance' },
  { ticker: 'WBD', name: 'Warner Bros. Discovery' },
  { ticker: 'WDC', name: 'Western Digital' },
  { ticker: 'WEC', name: 'WEC Energy Group' },
  { ticker: 'WELL', name: 'Welltower' },
  { ticker: 'WFC', name: 'Wells Fargo' },
  { ticker: 'WM', name: 'Waste Management' },
  { ticker: 'WMB', name: 'Williams Companies' },
  { ticker: 'WMT', name: 'Walmart' },
  { ticker: 'WRB', name: 'W.R. Berkley' },
  { ticker: 'WSM', name: 'Williams-Sonoma' },
  { ticker: 'WST', name: 'West Pharmaceutical' },
  { ticker: 'WTW', name: 'Willis Towers Watson' },
  { ticker: 'WY', name: 'Weyerhaeuser' },
  { ticker: 'WYNN', name: 'Wynn Resorts' },
  { ticker: 'XEL', name: 'Xcel Energy' },
  { ticker: 'XOM', name: 'Exxon Mobil' },
  { ticker: 'XYL', name: 'Xylem' },
  { ticker: 'YUM', name: 'Yum! Brands' },
  { ticker: 'ZBH', name: 'Zimmer Biomet' },
  { ticker: 'ZBRA', name: 'Zebra Technologies' },
  { ticker: 'ZTS', name: 'Zoetis' },
];

// Search function for autocomplete
export function searchStocks(query: string): Stock[] {
  if (!query.trim()) return [];

  const q = query.toLowerCase();

  // Separate matches into priority groups (ticker and name have equal importance)
  const exact: Stock[] = [];
  const startsWith: Stock[] = [];
  const contains: Stock[] = [];

  for (const stock of SP500_STOCKS) {
    const tickerLower = stock.ticker.toLowerCase();
    const nameLower = stock.name.toLowerCase();

    if (tickerLower === q || nameLower === q) {
      exact.push(stock);
    } else if (tickerLower.startsWith(q) || nameLower.startsWith(q)) {
      startsWith.push(stock);
    } else if (tickerLower.includes(q) || nameLower.includes(q)) {
      contains.push(stock);
    }
  }

  // Return prioritized results: exact > starts with > contains
  return [...exact, ...startsWith, ...contains].slice(0, 10);
}
