// S&P 500 stocks list (top companies by market cap)
export interface Stock {
  ticker: string;
  name: string;
}

export const SP500_STOCKS: Stock[] = [
  { ticker: 'AAPL', name: 'Apple' },
  { ticker: 'ABBV', name: 'AbbVie' },
  { ticker: 'ABT', name: 'Abbott Laboratories' },
  { ticker: 'ACN', name: 'Accenture' },
  { ticker: 'ADBE', name: 'Adobe' },
  { ticker: 'ADI', name: 'Analog Devices' },
  { ticker: 'ADP', name: 'Automatic Data Processing' },
  { ticker: 'ADSK', name: 'Autodesk' },
  { ticker: 'AEP', name: 'American Electric Power' },
  { ticker: 'AFL', name: 'Aflac' },
  { ticker: 'AIG', name: 'American International Group' },
  { ticker: 'AMAT', name: 'Applied Materials' },
  { ticker: 'AMD', name: 'Advanced Micro Devices' },
  { ticker: 'AMGN', name: 'Amgen' },
  { ticker: 'AMT', name: 'American Tower' },
  { ticker: 'AMZN', name: 'Amazon' },
  { ticker: 'ANET', name: 'Arista Networks' },
  { ticker: 'AON', name: 'Aon' },
  { ticker: 'APD', name: 'Air Products & Chemicals' },
  { ticker: 'APH', name: 'Amphenol' },
  { ticker: 'AVGO', name: 'Broadcom' },
  { ticker: 'AXP', name: 'American Express' },
  { ticker: 'AZO', name: 'AutoZone' },
  { ticker: 'BA', name: 'Boeing' },
  { ticker: 'BAC', name: 'Bank of America' },
  { ticker: 'BDX', name: 'Becton Dickinson' },
  { ticker: 'BIIB', name: 'Biogen' },
  { ticker: 'BK', name: 'Bank of New York Mellon' },
  { ticker: 'BKNG', name: 'Booking Holdings' },
  { ticker: 'BLK', name: 'BlackRock' },
  { ticker: 'BMY', name: 'Bristol-Myers Squibb' },
  { ticker: 'BRK.B', name: 'Berkshire Hathaway B' },
  { ticker: 'BSX', name: 'Boston Scientific' },
  { ticker: 'C', name: 'Citigroup' },
  { ticker: 'CAT', name: 'Caterpillar' },
  { ticker: 'CB', name: 'Chubb' },
  { ticker: 'CCI', name: 'Crown Castle' },
  { ticker: 'CDNS', name: 'Cadence Design Systems' },
  { ticker: 'CEG', name: 'Constellation Energy' },
  { ticker: 'CHTR', name: 'Charter Communications' },
  { ticker: 'CI', name: 'Cigna Group' },
  { ticker: 'CL', name: 'Colgate-Palmolive' },
  { ticker: 'CMCSA', name: 'Comcast' },
  { ticker: 'CME', name: 'CME Group' },
  { ticker: 'CMG', name: 'Chipotle Mexican Grill' },
  { ticker: 'COP', name: 'ConocoPhillips' },
  { ticker: 'COST', name: 'Costco Wholesale' },
  { ticker: 'CRM', name: 'Salesforce' },
  { ticker: 'CSCO', name: 'Cisco Systems' },
  { ticker: 'CSX', name: 'CSX' },
  { ticker: 'CTAS', name: 'Cintas' },
  { ticker: 'CVS', name: 'CVS Health' },
  { ticker: 'CVX', name: 'Chevron' },
  { ticker: 'D', name: 'Dominion Energy' },
  { ticker: 'DE', name: 'Deere & Co' },
  { ticker: 'DHR', name: 'Danaher' },
  { ticker: 'DIS', name: 'Walt Disney' },
  { ticker: 'DLR', name: 'Digital Realty Trust' },
  { ticker: 'DOW', name: 'Dow' },
  { ticker: 'DUK', name: 'Duke Energy' },
  { ticker: 'ECL', name: 'Ecolab' },
  { ticker: 'EL', name: 'Estee Lauder' },
  { ticker: 'ELV', name: 'Elevance Health' },
  { ticker: 'EMR', name: 'Emerson Electric' },
  { ticker: 'EOG', name: 'EOG Resources' },
  { ticker: 'EQIX', name: 'Equinix' },
  { ticker: 'ETN', name: 'Eaton' },
  { ticker: 'EW', name: 'Edwards Lifesciences' },
  { ticker: 'EXC', name: 'Exelon' },
  { ticker: 'F', name: 'Ford Motor' },
  { ticker: 'FDX', name: 'FedEx' },
  { ticker: 'FI', name: 'Fiserv' },
  { ticker: 'FTNT', name: 'Fortinet' },
  { ticker: 'GD', name: 'General Dynamics' },
  { ticker: 'GE', name: 'General Electric' },
  { ticker: 'GILD', name: 'Gilead Sciences' },
  { ticker: 'GM', name: 'General Motors' },
  { ticker: 'GOOG', name: 'Alphabet Class C' },
  { ticker: 'GOOGL', name: 'Alphabet Class A' },
  { ticker: 'GS', name: 'Goldman Sachs' },
  { ticker: 'HD', name: 'Home Depot' },
  { ticker: 'HLT', name: 'Hilton Worldwide' },
  { ticker: 'HON', name: 'Honeywell International' },
  { ticker: 'HUM', name: 'Humana' },
  { ticker: 'IBM', name: 'IBM' },
  { ticker: 'ICE', name: 'Intercontinental Exchange' },
  { ticker: 'INTC', name: 'Intel' },
  { ticker: 'INTU', name: 'Intuit' },
  { ticker: 'ISRG', name: 'Intuitive Surgical' },
  { ticker: 'ITW', name: 'Illinois Tool Works' },
  { ticker: 'JNJ', name: 'Johnson & Johnson' },
  { ticker: 'JPM', name: 'JPMorgan Chase' },
  { ticker: 'KO', name: 'Coca-Cola' },
  { ticker: 'KLAC', name: 'KLA' },
  { ticker: 'LHX', name: 'L3Harris Technologies' },
  { ticker: 'LIN', name: 'Linde' },
  { ticker: 'LLY', name: 'Eli Lilly' },
  { ticker: 'LMT', name: 'Lockheed Martin' },
  { ticker: 'LOW', name: 'Lowe\'s' },
  { ticker: 'LRCX', name: 'Lam Research' },
  { ticker: 'MA', name: 'Mastercard' },
  { ticker: 'MAR', name: 'Marriott International' },
  { ticker: 'MCD', name: 'McDonald\'s' },
  { ticker: 'MCHP', name: 'Microchip Technology' },
  { ticker: 'MCK', name: 'McKesson' },
  { ticker: 'MCO', name: 'Moody\'s' },
  { ticker: 'MDLZ', name: 'Mondelez International' },
  { ticker: 'MDT', name: 'Medtronic' },
  { ticker: 'MET', name: 'MetLife' },
  { ticker: 'META', name: 'Meta Platforms' },
  { ticker: 'MMC', name: 'Marsh & McLennan' },
  { ticker: 'MMM', name: '3M Company' },
  { ticker: 'MO', name: 'Altria Group' },
  { ticker: 'MRK', name: 'Merck' },
  { ticker: 'MS', name: 'Morgan Stanley' },
  { ticker: 'MSFT', name: 'Microsoft' },
  { ticker: 'MSI', name: 'Motorola Solutions' },
  { ticker: 'MU', name: 'Micron Technology' },
  { ticker: 'NEE', name: 'NextEra Energy' },
  { ticker: 'NFLX', name: 'Netflix' },
  { ticker: 'NKE', name: 'Nike' },
  { ticker: 'NOC', name: 'Northrop Grumman' },
  { ticker: 'NOW', name: 'ServiceNow' },
  { ticker: 'NSC', name: 'Norfolk Southern' },
  { ticker: 'NVDA', name: 'NVIDIA' },
  { ticker: 'ORCL', name: 'Oracle' },
  { ticker: 'ORLY', name: 'O\'Reilly Automotive' },
  { ticker: 'OXY', name: 'Occidental Petroleum' },
  { ticker: 'PANW', name: 'Palo Alto Networks' },
  { ticker: 'PAYX', name: 'Paychex' },
  { ticker: 'PCAR', name: 'PACCAR' },
  { ticker: 'PEP', name: 'PepsiCo' },
  { ticker: 'PFE', name: 'Pfizer' },
  { ticker: 'PG', name: 'Procter & Gamble' },
  { ticker: 'PGR', name: 'Progressive' },
  { ticker: 'PLD', name: 'Prologis' },
  { ticker: 'PM', name: 'Philip Morris International' },
  { ticker: 'PNC', name: 'PNC Financial Services' },
  { ticker: 'PSA', name: 'Public Storage' },
  { ticker: 'PSX', name: 'Phillips 66' },
  { ticker: 'PYPL', name: 'PayPal Holdings' },
  { ticker: 'QCOM', name: 'Qualcomm' },
  { ticker: 'REGN', name: 'Regeneron Pharmaceuticals' },
  { ticker: 'ROP', name: 'Roper Technologies' },
  { ticker: 'ROST', name: 'Ross Stores' },
  { ticker: 'RTX', name: 'RTX' },
  { ticker: 'SBUX', name: 'Starbucks' },
  { ticker: 'SCHW', name: 'Charles Schwab' },
  { ticker: 'SHW', name: 'Sherwin-Williams' },
  { ticker: 'SLB', name: 'Schlumberger' },
  { ticker: 'SNPS', name: 'Synopsys' },
  { ticker: 'SO', name: 'Southern Company' },
  { ticker: 'SPG', name: 'Simon Property Group' },
  { ticker: 'SPGI', name: 'S&P Global' },
  { ticker: 'SRE', name: 'Sempra Energy' },
  { ticker: 'SYK', name: 'Stryker' },
  { ticker: 'SYY', name: 'Sysco' },
  { ticker: 'T', name: 'AT&T' },
  { ticker: 'TDG', name: 'TransDigm Group' },
  { ticker: 'TGT', name: 'Target' },
  { ticker: 'TJX', name: 'TJX Companies' },
  { ticker: 'TMO', name: 'Thermo Fisher Scientific' },
  { ticker: 'TMUS', name: 'T-Mobile US' },
  { ticker: 'TRV', name: 'Travelers Companies' },
  { ticker: 'TSLA', name: 'Tesla' },
  { ticker: 'TXN', name: 'Texas Instruments' },
  { ticker: 'UNH', name: 'UnitedHealth Group' },
  { ticker: 'UNP', name: 'Union Pacific' },
  { ticker: 'UPS', name: 'United Parcel Service' },
  { ticker: 'USB', name: 'U.S. Bancorp' },
  { ticker: 'V', name: 'Visa' },
  { ticker: 'VLO', name: 'Valero Energy' },
  { ticker: 'VRTX', name: 'Vertex Pharmaceuticals' },
  { ticker: 'VZ', name: 'Verizon Communications' },
  { ticker: 'WBA', name: 'Walgreens Boots Alliance' },
  { ticker: 'WFC', name: 'Wells Fargo' },
  { ticker: 'WM', name: 'Waste Management' },
  { ticker: 'WMT', name: 'Walmart' },
  { ticker: 'XOM', name: 'Exxon Mobil' },
  { ticker: 'ZTS', name: 'Zoetis' },
];

// Search function for autocomplete
export function searchStocks(query: string): Stock[] {
  if (!query.trim()) return [];

  const q = query.toLowerCase();

  // Separate matches into priority groups (ticker and name have equal importance)
  const exact: Stock[] = [];
  const startsWith: Stock[] = [];
  const contains: Stock[] = [];

  for (const stock of SP500_STOCKS) {
    const tickerLower = stock.ticker.toLowerCase();
    const nameLower = stock.name.toLowerCase();

    if (tickerLower === q || nameLower === q) {
      exact.push(stock);
    } else if (tickerLower.startsWith(q) || nameLower.startsWith(q)) {
      startsWith.push(stock);
    } else if (tickerLower.includes(q) || nameLower.includes(q)) {
      contains.push(stock);
    }
  }

  // Return prioritized results: exact > starts with > contains
  return [...exact, ...startsWith, ...contains].slice(0, 10);
}
