// STOXX Europe 600 stocks list (components as of January 2025)
// Note: European tickers may need exchange suffixes for API lookups
// (e.g., .PA for Paris, .DE for Frankfurt, .L for London, .AS for Amsterdam, etc.)
export interface Stock {
  ticker: string;
  name: string;
}

export const STOXX600_STOCKS: Stock[] = [
  { ticker: '1U1', name: '1&1 Drillisch' },
  { ticker: 'III', name: '3i Group' },
  { ticker: 'A2A', name: 'A2A' },
  { ticker: 'AAK', name: 'AAK' },
  { ticker: 'AALB', name: 'Aalberts' },
  { ticker: 'ARL', name: 'Aareal Bank' },
  { ticker: 'ABBN', name: 'ABB' },
  { ticker: 'ABDN', name: 'abrdn' },
  { ticker: 'ABN', name: 'ABN AMRO Bank' },
  { ticker: 'AC', name: 'Accor' },
  { ticker: 'ACKB', name: 'Ackermans & van Haaren' },
  { ticker: 'ACS', name: 'ACS' },
  { ticker: 'ADEN', name: 'Adecco Group' },
  { ticker: 'ADS', name: 'Adidas' },
  { ticker: 'ADM', name: 'Admiral Group' },
  { ticker: 'ADYEN', name: 'Adyen' },
  { ticker: 'AGN', name: 'Aegon' },
  { ticker: 'AENA', name: 'Aena' },
  { ticker: 'ADP', name: 'Aeroports de Paris' },
  { ticker: 'AGS', name: 'Ageas' },
  { ticker: 'AIBG', name: 'AIB Group' },
  { ticker: 'AIR', name: 'Airbus' },
  { ticker: 'AF', name: 'Air France-KLM' },
  { ticker: 'AI', name: 'Air Liquide' },
  { ticker: 'AKRBP', name: 'Aker BP' },
  { ticker: 'AKZA', name: 'Akzo Nobel' },
  { ticker: 'ALC', name: 'Alcon' },
  { ticker: 'ALFA', name: 'Alfa Laval' },
  { ticker: 'ALV', name: 'Allianz' },
  { ticker: 'ALO', name: 'Alstom' },
  { ticker: 'ATE', name: 'Alten' },
  { ticker: 'AMS', name: 'Amadeus IT Group' },
  { ticker: 'AMBU B', name: 'Ambu' },
  { ticker: 'AMUN', name: 'Amundi' },
  { ticker: 'ANDR', name: 'Andritz' },
  { ticker: 'AAL', name: 'Anglo American' },
  { ticker: 'ABI', name: 'Anheuser-Busch InBev' },
  { ticker: 'ANTO', name: 'Antofagasta' },
  { ticker: 'MAERSK B', name: 'A.P. Moller-Maersk' },
  { ticker: 'MT', name: 'ArcelorMittal' },
  { ticker: 'ARGX', name: 'argenx' },
  { ticker: 'AKE', name: 'Arkema' },
  { ticker: 'AT1', name: 'Aroundtown' },
  { ticker: 'AHT', name: 'Ashtead Group' },
  { ticker: 'ASM', name: 'ASM International' },
  { ticker: 'ASML', name: 'ASML Holding' },
  { ticker: 'ASRNL', name: 'ASR Nederland' },
  { ticker: 'ASSA B', name: 'Assa Abloy' },
  { ticker: 'ABF', name: 'Associated British Foods' },
  { ticker: 'AZN', name: 'AstraZeneca' },
  { ticker: 'ATCO A', name: 'Atlas Copco' },
  { ticker: 'ATO', name: 'Atos' },
  { ticker: 'NDA', name: 'Aurubis' },
  { ticker: 'AUTO', name: 'Auto Trader Group' },
  { ticker: 'AV.', name: 'Aviva' },
  { ticker: 'AVOL', name: 'Avolta' },
  { ticker: 'CS', name: 'AXA' },
  { ticker: 'BA.', name: 'BAE Systems' },
  { ticker: 'BBY', name: 'Balfour Beatty' },
  { ticker: 'BALN', name: 'Baloise' },
  { ticker: 'BBVA', name: 'Banco Bilbao Vizcaya Argentaria' },
  { ticker: 'BAMI', name: 'Banco BPM' },
  { ticker: 'BCP', name: 'Banco Comercial Portugues' },
  { ticker: 'SAB', name: 'Banco de Sabadell' },
  { ticker: 'SAN', name: 'Banco Santander' },
  { ticker: 'BKT', name: 'Bankinter' },
  { ticker: 'BIRG', name: 'Bank of Ireland' },
  { ticker: 'PEO', name: 'Bank Pekao' },
  { ticker: 'BARC', name: 'Barclays' },
  { ticker: 'BTRW', name: 'Barratt Redrow' },
  { ticker: 'BARN', name: 'Barry Callebaut' },
  { ticker: 'BAS', name: 'BASF' },
  { ticker: 'BAYN', name: 'Bayer' },
  { ticker: 'BMW', name: 'Bayerische Motoren Werke' },
  { ticker: 'BION', name: 'BB Biotech' },
  { ticker: 'BEZ', name: 'Beazley' },
  { ticker: 'BC8', name: 'Bechtle' },
  { ticker: 'BEI', name: 'Beiersdorf' },
  { ticker: 'BWY', name: 'Bellway' },
  { ticker: 'BKGH', name: 'Berkeley Group' },
  { ticker: 'BB', name: 'BIC' },
  { ticker: 'BIM', name: 'bioMerieux' },
  { ticker: 'BME', name: 'B&M European Value Retail' },
  { ticker: 'BNP', name: 'BNP Paribas' },
  { ticker: 'BOL', name: 'Boliden' },
  { ticker: 'BOL', name: 'Bollore' },
  { ticker: 'EN', name: 'Bouygues' },
  { ticker: 'BP.', name: 'BP' },
  { ticker: 'BNR', name: 'Brenntag' },
  { ticker: 'BATS', name: 'British American Tobacco' },
  { ticker: 'BLND', name: 'British Land' },
  { ticker: 'BVIC', name: 'Britvic' },
  { ticker: 'BT.A', name: 'BT Group' },
  { ticker: 'BUCN', name: 'Bucher Industries' },
  { ticker: 'BNZL', name: 'Bunzl' },
  { ticker: 'BRBY', name: 'Burberry' },
  { ticker: 'BVI', name: 'Bureau Veritas' },
  { ticker: 'CABK', name: 'CaixaBank' },
  { ticker: 'CAP', name: 'Capgemini' },
  { ticker: 'CPI', name: 'Capita' },
  { ticker: 'CARL A', name: 'Carlsberg' },
  { ticker: 'AFX', name: 'Carl Zeiss Meditec' },
  { ticker: 'CCL', name: 'Carnival' },
  { ticker: 'CA', name: 'Carrefour' },
  { ticker: 'CO', name: 'Casino Guichard-Perrachon' },
  { ticker: 'CAST', name: 'Castellum' },
  { ticker: 'CDR', name: 'CD Projekt' },
  { ticker: 'CLNX', name: 'Cellnex Telecom' },
  { ticker: 'CMBN', name: 'Cembra Money Bank' },
  { ticker: 'CNA', name: 'Centrica' },
  { ticker: 'LISN', name: 'Lindt & Sprungli' },
  { ticker: 'CHR', name: 'Chr. Hansen' },
  { ticker: 'CDI', name: 'Christian Dior' },
  { ticker: 'CLN', name: 'Clariant' },
  { ticker: 'CBG', name: 'Close Brothers Group' },
  { ticker: 'CNH', name: 'CNH Industrial' },
  { ticker: 'CNP', name: 'CNP Assurances' },
  { ticker: 'EEE', name: 'Coca-Cola HBC' },
  { ticker: 'COFB', name: 'Cofinimmo' },
  { ticker: 'COLO B', name: 'Coloplast' },
  { ticker: 'COLR', name: 'Colruyt Group' },
  { ticker: 'CBK', name: 'Commerzbank' },
  { ticker: 'SGO', name: 'Saint-Gobain' },
  { ticker: 'CFR', name: 'Richemont' },
  { ticker: 'CPG', name: 'Compass Group' },
  { ticker: 'CON', name: 'Continental' },
  { ticker: 'CTEC', name: 'ConvaTec' },
  { ticker: '1COV', name: 'Covestro' },
  { ticker: 'COV', name: 'Covivio' },
  { ticker: 'ACA', name: 'Credit Agricole' },
  { ticker: 'CRH', name: 'CRH' },
  { ticker: 'CRDA', name: 'Croda International' },
  { ticker: 'BN', name: 'Danone' },
  { ticker: 'DANSKE', name: 'Danske Bank' },
  { ticker: 'AM', name: 'Dassault Aviation' },
  { ticker: 'DSY', name: 'Dassault Systemes' },
  { ticker: 'CPR', name: 'Davide Campari-Milano' },
  { ticker: 'DCC', name: 'DCC' },
  { ticker: 'DPH', name: 'Dechra Pharmaceuticals' },
  { ticker: 'DHER', name: 'Delivery Hero' },
  { ticker: 'DEMANT', name: 'Demant' },
  { ticker: 'DLN', name: 'Derwent London' },
  { ticker: 'DBK', name: 'Deutsche Bank' },
  { ticker: 'DB1', name: 'Deutsche Boerse' },
  { ticker: 'LHA', name: 'Deutsche Lufthansa' },
  { ticker: 'DHL', name: 'Deutsche Post' },
  { ticker: 'DTE', name: 'Deutsche Telekom' },
  { ticker: 'DWNI', name: 'Deutsche Wohnen' },
  { ticker: 'DGE', name: 'Diageo' },
  { ticker: 'DIA', name: 'DiaSorin' },
  { ticker: 'DLG', name: 'Direct Line Insurance' },
  { ticker: 'DKSH', name: 'DKSH Holding' },
  { ticker: 'DOM', name: 'Dometic Group' },
  { ticker: 'SMDS', name: 'DS Smith' },
  { ticker: 'DSV', name: 'DSV' },
  { ticker: 'EZJ', name: 'easyJet' },
  { ticker: 'EDEN', name: 'Edenred' },
  { ticker: 'EDP', name: 'EDP-Energias de Portugal' },
  { ticker: 'FGR', name: 'Eiffage' },
  { ticker: 'EDF', name: 'Electricite de France' },
  { ticker: 'ELUX B', name: 'Electrolux' },
  { ticker: 'EKTA B', name: 'Elekta' },
  { ticker: 'ELIS', name: 'Elis' },
  { ticker: 'ELISA', name: 'Elisa' },
  { ticker: 'EMSN', name: 'EMS-Chemie' },
  { ticker: 'ENG', name: 'Enagas' },
  { ticker: 'ELE', name: 'Endesa' },
  { ticker: 'ENEL', name: 'Enel' },
  { ticker: 'ENGI', name: 'Engie' },
  { ticker: 'ENI', name: 'Eni' },
  { ticker: 'ENT', name: 'Entain' },
  { ticker: 'EOAN', name: 'E.ON' },
  { ticker: 'EPI A', name: 'Epiroc' },
  { ticker: 'EQNR', name: 'Equinor' },
  { ticker: 'EBS', name: 'Erste Group Bank' },
  { ticker: 'EL', name: 'EssilorLuxottica' },
  { ticker: 'ESSITY B', name: 'Essity' },
  { ticker: 'RF', name: 'Eurazeo' },
  { ticker: 'ERF', name: 'Eurofins Scientific' },
  { ticker: 'ENX', name: 'Euronext' },
  { ticker: 'ETL', name: 'Eutelsat Communications' },
  { ticker: 'EVK', name: 'Evonik Industries' },
  { ticker: 'EVT', name: 'Evotec' },
  { ticker: 'EXO', name: 'Exor' },
  { ticker: 'EXPN', name: 'Experian' },
  { ticker: 'FABG', name: 'Fabege' },
  { ticker: 'FERG', name: 'Ferguson' },
  { ticker: 'RACE', name: 'Ferrari' },
  { ticker: 'FER', name: 'Ferrovial' },
  { ticker: 'FBK', name: 'FinecoBank' },
  { ticker: 'FLS', name: 'FLSmidth' },
  { ticker: 'FHZN', name: 'Flughafen Zurich' },
  { ticker: 'FLTR', name: 'Flutter Entertainment' },
  { ticker: 'FORTUM', name: 'Fortum' },
  { ticker: 'FRVIA', name: 'Forvia' },
  { ticker: 'FRA', name: 'Fraport' },
  { ticker: 'FNTN', name: 'freenet' },
  { ticker: 'FME', name: 'Fresenius Medical Care' },
  { ticker: 'FRE', name: 'Fresenius' },
  { ticker: 'FPE3', name: 'Fuchs' },
  { ticker: 'GLPG', name: 'Galapagos' },
  { ticker: 'GALE', name: 'Galenica' },
  { ticker: 'GALP', name: 'Galp Energia' },
  { ticker: 'G1A', name: 'GEA Group' },
  { ticker: 'GEBN', name: 'Geberit' },
  { ticker: 'GFC', name: 'Gecina' },
  { ticker: 'G', name: 'Generali' },
  { ticker: 'GMAB', name: 'Genmab' },
  { ticker: 'GF', name: 'Georg Fischer' },
  { ticker: 'GXI', name: 'Gerresheimer' },
  { ticker: 'GETI B', name: 'Getinge' },
  { ticker: 'GET', name: 'Getlink' },
  { ticker: 'GIVN', name: 'Givaudan' },
  { ticker: 'GJF', name: 'Gjensidige Forsikring' },
  { ticker: 'GL9', name: 'Glanbia' },
  { ticker: 'GLEN', name: 'Glencore' },
  { ticker: 'GN', name: 'GN Store Nord' },
  { ticker: 'GPE', name: 'Great Portland Estates' },
  { ticker: 'GLJ', name: 'Grenke' },
  { ticker: 'GRF', name: 'Grifols' },
  { ticker: 'GBLB', name: 'Groupe Bruxelles Lambert' },
  { ticker: 'GSK', name: 'GSK' },
  { ticker: 'HLMA', name: 'Halma' },
  { ticker: 'HMSO', name: 'Hammerson' },
  { ticker: 'HNR1', name: 'Hannover Ruck' },
  { ticker: 'HL.', name: 'Hargreaves Lansdown' },
  { ticker: 'HAS', name: 'Hays' },
  { ticker: 'HEI', name: 'Heidelberg Materials' },
  { ticker: 'HEIO', name: 'Heineken Holding' },
  { ticker: 'HEIA', name: 'Heineken' },
  { ticker: 'HLE', name: 'HELLA' },
  { ticker: 'HEN3', name: 'Henkel' },
  { ticker: 'HM B', name: 'Hennes & Mauritz' },
  { ticker: 'HER', name: 'Hera' },
  { ticker: 'RMS', name: 'Hermes International' },
  { ticker: 'HEXA B', name: 'Hexagon' },
  { ticker: 'HPOL B', name: 'Hexpol' },
  { ticker: 'HIK', name: 'Hikma Pharmaceuticals' },
  { ticker: 'HSX', name: 'Hiscox' },
  { ticker: 'LUN', name: 'H. Lundbeck' },
  { ticker: 'HOT', name: 'Hochtief' },
  { ticker: 'HOLN', name: 'Holcim' },
  { ticker: 'HSV', name: 'HomeServe' },
  { ticker: 'HWDN', name: 'Howden Joinery' },
  { ticker: 'HSBA', name: 'HSBC Holdings' },
  { ticker: 'BOSS', name: 'Hugo Boss' },
  { ticker: 'HUH1V', name: 'Huhtamaki' },
  { ticker: 'HUSQ B', name: 'Husqvarna' },
  { ticker: 'IBE', name: 'Iberdrola' },
  { ticker: 'ICAD', name: 'Icade' },
  { ticker: 'ICA', name: 'ICA Gruppen' },
  { ticker: 'ICG', name: 'Intermediate Capital Group' },
  { ticker: 'IGG', name: 'IG Group' },
  { ticker: 'IMCD', name: 'IMCD' },
  { ticker: 'NK', name: 'Imerys' },
  { ticker: 'IMI', name: 'IMI' },
  { ticker: 'IMB', name: 'Imperial Brands' },
  { ticker: 'INCH', name: 'Inchcape' },
  { ticker: 'ITX', name: 'Inditex' },
  { ticker: 'INDU A', name: 'Industrivarden' },
  { ticker: 'IFX', name: 'Infineon Technologies' },
  { ticker: 'INF', name: 'Informa' },
  { ticker: 'INGA', name: 'ING Groep' },
  { ticker: 'COL', name: 'Inmobiliaria Colonial' },
  { ticker: 'IHG', name: 'InterContinental Hotels' },
  { ticker: 'IAG', name: 'International Airlines Group' },
  { ticker: 'IDS', name: 'International Distribution Services' },
  { ticker: 'IP', name: 'Interpump Group' },
  { ticker: 'ITRK', name: 'Intertek Group' },
  { ticker: 'ISP', name: 'Intesa Sanpaolo' },
  { ticker: 'INVP', name: 'Investec' },
  { ticker: 'INVE B', name: 'Investor' },
  { ticker: 'IPN', name: 'Ipsen' },
  { ticker: 'ISS', name: 'ISS' },
  { ticker: 'IG', name: 'Italgas' },
  { ticker: 'ITV', name: 'ITV' },
  { ticker: 'DEC', name: 'JCDecaux' },
  { ticker: 'JMT', name: 'Jeronimo Martins' },
  { ticker: 'JMAT', name: 'Johnson Matthey' },
  { ticker: 'WG.', name: 'John Wood Group' },
  { ticker: 'BAER', name: 'Julius Baer' },
  { ticker: 'JUP', name: 'Jupiter Fund Management' },
  { ticker: 'TKWY', name: 'Just Eat Takeaway.com' },
  { ticker: 'JYSK', name: 'Jyske Bank' },
  { ticker: 'KBC', name: 'KBC Group' },
  { ticker: 'KER', name: 'Kering' },
  { ticker: 'KRZ', name: 'Kerry Group' },
  { ticker: 'KESKOB', name: 'Kesko' },
  { ticker: 'KGH', name: 'KGHM Polska Miedz' },
  { ticker: 'KIND SDB', name: 'Kindred Group' },
  { ticker: 'KGF', name: 'Kingfisher' },
  { ticker: 'KRX', name: 'Kingspan Group' },
  { ticker: 'KINV B', name: 'Kinnevik' },
  { ticker: 'KGX', name: 'KION Group' },
  { ticker: 'LI', name: 'Klepierre' },
  { ticker: 'KBX', name: 'Knorr-Bremse' },
  { ticker: 'KNEBV', name: 'Kone' },
  { ticker: 'KCR', name: 'Konecranes' },
  { ticker: 'AD', name: 'Koninklijke Ahold Delhaize' },
  { ticker: 'KPN', name: 'Koninklijke KPN' },
  { ticker: 'PHIA', name: 'Koninklijke Philips' },
  { ticker: 'VPK', name: 'Koninklijke Vopak' },
  { ticker: 'SDF', name: 'K+S' },
  { ticker: 'KNIN', name: 'Kuehne + Nagel' },
  { ticker: 'MMB', name: 'Lagardere' },
  { ticker: 'LAND', name: 'Land Securities' },
  { ticker: 'LXS', name: 'Lanxess' },
  { ticker: 'LGEN', name: 'Legal & General' },
  { ticker: 'LEG', name: 'LEG Immobilien' },
  { ticker: 'LR', name: 'Legrand' },
  { ticker: 'LUND B', name: 'Lundbergforetagen' },
  { ticker: 'LDO', name: 'Leonardo' },
  { ticker: 'LLOY', name: 'Lloyds Banking Group' },
  { ticker: 'LOGN', name: 'Logitech' },
  { ticker: 'LSEG', name: 'London Stock Exchange Group' },
  { ticker: 'LONN', name: 'Lonza' },
  { ticker: 'LOOMIS', name: 'Loomis' },
  { ticker: 'OR', name: "L'Oreal" },
  { ticker: 'LPP', name: 'LPP' },
  { ticker: 'MC', name: 'LVMH' },
  { ticker: 'EMG', name: 'Man Group' },
  { ticker: 'MAP', name: 'Mapfre' },
  { ticker: 'MKS', name: 'Marks & Spencer' },
  { ticker: 'MB', name: 'Mediobanca' },
  { ticker: 'MGGT', name: 'Meggitt' },
  { ticker: 'MRO', name: 'Melrose Industries' },
  { ticker: 'MBG', name: 'Mercedes-Benz Group' },
  { ticker: 'MRK', name: 'Merck KGaA' },
  { ticker: 'MRL', name: 'Merlin Properties' },
  { ticker: 'B4B', name: 'Metro' },
  { ticker: 'ML', name: 'Michelin' },
  { ticker: 'MONC', name: 'Moncler' },
  { ticker: 'MNDI', name: 'Mondi' },
  { ticker: 'MOR', name: 'MorphoSys' },
  { ticker: 'MOWI', name: 'Mowi' },
  { ticker: 'MTX', name: 'MTU Aero Engines' },
  { ticker: 'MUV2', name: 'Munich Re' },
  { ticker: 'NG.', name: 'National Grid' },
  { ticker: 'KN', name: 'Natixis' },
  { ticker: 'NTGY', name: 'Naturgy Energy' },
  { ticker: 'NWG', name: 'NatWest Group' },
  { ticker: 'NELES', name: 'Neles' },
  { ticker: 'NEM', name: 'Nemetschek' },
  { ticker: 'NESTE', name: 'Neste' },
  { ticker: 'NESN', name: 'Nestle' },
  { ticker: 'NXT', name: 'Next' },
  { ticker: 'NIBE B', name: 'NIBE Industrier' },
  { ticker: 'NN', name: 'NN Group' },
  { ticker: 'NOKIA', name: 'Nokia' },
  { ticker: 'TYRES', name: 'Nokian Tyres' },
  { ticker: 'NDA FI', name: 'Nordea Bank' },
  { ticker: 'NHY', name: 'Norsk Hydro' },
  { ticker: 'NOVN', name: 'Novartis' },
  { ticker: 'NSIS B', name: 'Novonesis' },
  { ticker: 'NOVO B', name: 'Novo Nordisk' },
  { ticker: 'OCDO', name: 'Ocado Group' },
  { ticker: 'OERL', name: 'OC Oerlikon' },
  { ticker: 'OMU', name: 'Old Mutual' },
  { ticker: 'OMV', name: 'OMV' },
  { ticker: 'ORA', name: 'Orange' },
  { ticker: 'ORNBV', name: 'Orion' },
  { ticker: 'ORK', name: 'Orkla' },
  { ticker: 'PKN', name: 'Orlen' },
  { ticker: 'ORP', name: 'Orpea' },
  { ticker: 'ORRON', name: 'Orron Energy' },
  { ticker: 'ORSTED', name: 'Orsted' },
  { ticker: 'PNDORA', name: 'Pandora' },
  { ticker: 'PGHN', name: 'Partners Group' },
  { ticker: 'PSON', name: 'Pearson' },
  { ticker: 'PNN', name: 'Pennon Group' },
  { ticker: 'RI', name: 'Pernod Ricard' },
  { ticker: 'PSN', name: 'Persimmon' },
  { ticker: 'PHNX', name: 'Phoenix Group' },
  { ticker: 'PIRC', name: 'Pirelli' },
  { ticker: 'PGN', name: 'PGNiG' },
  { ticker: 'POLY', name: 'Polymetal' },
  { ticker: 'PAH3', name: 'Porsche Automobil Holding' },
  { ticker: 'PST', name: 'Poste Italiane' },
  { ticker: 'PKO', name: 'PKO Bank Polski' },
  { ticker: 'PZU', name: 'Powszechny Zaklad Ubezpieczen' },
  { ticker: 'PSM', name: 'ProSiebenSat.1 Media' },
  { ticker: 'PROX', name: 'Proximus' },
  { ticker: 'PRU', name: 'Prudential' },
  { ticker: 'PRY', name: 'Prysmian' },
  { ticker: 'PSPN', name: 'PSP Swiss Property' },
  { ticker: 'PUB', name: 'Publicis Groupe' },
  { ticker: 'PUM', name: 'Puma' },
  { ticker: 'QGEN', name: 'QIAGEN' },
  { ticker: 'QLT', name: 'Quilter' },
  { ticker: 'RBI', name: 'Raiffeisen Bank International' },
  { ticker: 'RAND', name: 'Randstad' },
  { ticker: 'RKT', name: 'Reckitt Benckiser' },
  { ticker: 'REC', name: 'Recordati' },
  { ticker: 'RED', name: 'Redeia' },
  { ticker: 'REL', name: 'RELX' },
  { ticker: 'RCO', name: 'Remy Cointreau' },
  { ticker: 'RNO', name: 'Renault' },
  { ticker: 'RTO', name: 'Rentokil Initial' },
  { ticker: 'REP', name: 'Repsol' },
  { ticker: 'RXL', name: 'Rexel' },
  { ticker: 'RHM', name: 'Rheinmetall' },
  { ticker: 'RMV', name: 'Rightmove' },
  { ticker: 'RIO', name: 'Rio Tinto' },
  { ticker: 'ROG', name: 'Roche' },
  { ticker: 'RBO', name: 'Roche Bobois' },
  { ticker: 'ROCK B', name: 'Rockwool' },
  { ticker: 'RR.', name: 'Rolls-Royce' },
  { ticker: 'ROR', name: 'Rotork' },
  { ticker: 'BOKA', name: 'Boskalis' },
  { ticker: 'RBREW', name: 'Royal Unibrew' },
  { ticker: 'RS1', name: 'RS Group' },
  { ticker: 'RTLL', name: 'RTL Group' },
  { ticker: 'RUI', name: 'Rubis' },
  { ticker: 'RWE', name: 'RWE' },
  { ticker: 'RYA', name: 'Ryanair' },
  { ticker: 'SAAB B', name: 'Saab' },
  { ticker: 'SAF', name: 'Safran' },
  { ticker: 'SGE', name: 'Sage Group' },
  { ticker: 'SBRY', name: 'Sainsbury' },
  { ticker: 'SPM', name: 'Saipem' },
  { ticker: 'SALM', name: 'SalMar' },
  { ticker: 'SAMPO', name: 'Sampo' },
  { ticker: 'SAND', name: 'Sandvik' },
  { ticker: 'SAN', name: 'Sanofi' },
  { ticker: 'SPL', name: 'Santander Bank Polska' },
  { ticker: 'SAP', name: 'SAP' },
  { ticker: 'SRT3', name: 'Sartorius' },
  { ticker: 'DIM', name: 'Sartorius Stedim Biotech' },
  { ticker: 'SBMO', name: 'SBM Offshore' },
  { ticker: 'SCHP', name: 'Schindler' },
  { ticker: 'SU', name: 'Schneider Electric' },
  { ticker: 'SDR', name: 'Schroders' },
  { ticker: 'SCR', name: 'SCOR' },
  { ticker: 'G24', name: 'Scout24' },
  { ticker: 'SK', name: 'SEB' },
  { ticker: 'SECU B', name: 'Securitas' },
  { ticker: 'SGRO', name: 'Segro' },
  { ticker: 'SESGL', name: 'SES' },
  { ticker: 'SVT', name: 'Severn Trent' },
  { ticker: 'SGSN', name: 'SGS' },
  { ticker: 'SIE', name: 'Siemens' },
  { ticker: 'ENR', name: 'Siemens Energy' },
  { ticker: 'SGRE', name: 'Siemens Gamesa' },
  { ticker: 'SHL', name: 'Siemens Healthineers' },
  { ticker: 'LIGHT', name: 'Signify' },
  { ticker: 'SIKA', name: 'Sika' },
  { ticker: 'WAF', name: 'Siltronic' },
  { ticker: 'SIM', name: 'SimCorp' },
  { ticker: 'SEB A', name: 'Skandinaviska Enskilda Banken' },
  { ticker: 'SKA B', name: 'Skanska' },
  { ticker: 'SKF B', name: 'SKF' },
  { ticker: 'SN.', name: 'Smith & Nephew' },
  { ticker: 'SMIN', name: 'Smiths Group' },
  { ticker: 'SRG', name: 'Snam' },
  { ticker: 'GLE', name: 'Societe Generale' },
  { ticker: 'SW', name: 'Sodexo' },
  { ticker: 'SOF', name: 'Sofina' },
  { ticker: 'SOLB', name: 'Solvay' },
  { ticker: 'SOON', name: 'Sonova' },
  { ticker: 'SOP', name: 'Sopra Steria' },
  { ticker: 'SXS', name: 'Spectris' },
  { ticker: 'SPIE', name: 'SPIE' },
  { ticker: 'SPX', name: 'Spirax-Sarco' },
  { ticker: 'SSE', name: 'SSE' },
  { ticker: 'SSPG', name: 'SSP Group' },
  { ticker: 'STAN', name: 'Standard Chartered' },
  { ticker: 'STLA', name: 'Stellantis' },
  { ticker: 'STJ', name: "St. James's Place" },
  { ticker: 'STMPA', name: 'STMicroelectronics' },
  { ticker: 'STERV', name: 'Stora Enso' },
  { ticker: 'STB', name: 'Storebrand' },
  { ticker: 'STMN', name: 'Straumann' },
  { ticker: 'SUBC', name: 'Subsea 7' },
  { ticker: 'SEV', name: 'Suez' },
  { ticker: 'SCA B', name: 'Svenska Cellulosa' },
  { ticker: 'SHB A', name: 'Svenska Handelsbanken' },
  { ticker: 'UHR', name: 'Swatch Group' },
  { ticker: 'SWED A', name: 'Swedbank' },
  { ticker: 'SWMA', name: 'Swedish Match' },
  { ticker: 'SOBI', name: 'Swedish Orphan Biovitrum' },
  { ticker: 'SCMN', name: 'Swisscom' },
  { ticker: 'SLHN', name: 'Swiss Life' },
  { ticker: 'SPSN', name: 'Swiss Prime Site' },
  { ticker: 'SREN', name: 'Swiss Re' },
  { ticker: 'SY1', name: 'Symrise' },
  { ticker: 'TEG', name: 'TAG Immobilien' },
  { ticker: 'TATE', name: 'Tate & Lyle' },
  { ticker: 'TW.', name: 'Taylor Wimpey' },
  { ticker: 'TECN', name: 'Tecan' },
  { ticker: 'FTI', name: 'TechnipFMC' },
  { ticker: 'TEL2 B', name: 'Tele2' },
  { ticker: 'TIT', name: 'Telecom Italia' },
  { ticker: 'ERIC B', name: 'Ericsson' },
  { ticker: 'O2D', name: 'Telefonica Deutschland' },
  { ticker: 'TEF', name: 'Telefonica' },
  { ticker: 'TNET', name: 'Telenet' },
  { ticker: 'TEL', name: 'Telenor' },
  { ticker: 'TEP', name: 'Teleperformance' },
  { ticker: 'TELIA', name: 'Telia Company' },
  { ticker: 'TEMN', name: 'Temenos' },
  { ticker: 'TEN', name: 'Tenaris' },
  { ticker: 'TRN', name: 'Terna' },
  { ticker: 'TSCO', name: 'Tesco' },
  { ticker: 'TGS', name: 'TGS' },
  { ticker: 'HO', name: 'Thales' },
  { ticker: 'TKA', name: 'thyssenkrupp' },
  { ticker: 'TOM', name: 'Tomra Systems' },
  { ticker: 'TTE', name: 'TotalEnergies' },
  { ticker: 'TPK', name: 'Travis Perkins' },
  { ticker: 'TREL B', name: 'Trelleborg' },
  { ticker: 'BBOX', name: 'Tritax Big Box REIT' },
  { ticker: 'TRYG', name: 'Tryg' },
  { ticker: 'TUI1', name: 'TUI' },
  { ticker: 'UBI', name: 'Ubisoft' },
  { ticker: 'UBSG', name: 'UBS Group' },
  { ticker: 'UCB', name: 'UCB' },
  { ticker: 'UMI', name: 'Umicore' },
  { ticker: 'URW', name: 'Unibail-Rodamco-Westfield' },
  { ticker: 'UCG', name: 'UniCredit' },
  { ticker: 'ULVR', name: 'Unilever' },
  { ticker: 'UN0', name: 'Uniper' },
  { ticker: 'UTDI', name: 'United Internet' },
  { ticker: 'UU.', name: 'United Utilities' },
  { ticker: 'UTG', name: 'Unite Group' },
  { ticker: 'UPM', name: 'UPM-Kymmene' },
  { ticker: 'FR', name: 'Valeo' },
  { ticker: 'VALMT', name: 'Valmet' },
  { ticker: 'VACN', name: 'VAT Group' },
  { ticker: 'VIE', name: 'Veolia Environnement' },
  { ticker: 'VER', name: 'Verbund' },
  { ticker: 'VWS', name: 'Vestas Wind Systems' },
  { ticker: 'VCT', name: 'Victrex' },
  { ticker: 'VIFN', name: 'Vifor Pharma' },
  { ticker: 'DG', name: 'Vinci' },
  { ticker: 'VIS', name: 'Viscofan' },
  { ticker: 'VIV', name: 'Vivendi' },
  { ticker: 'VOD', name: 'Vodafone' },
  { ticker: 'VOE', name: 'voestalpine' },
  { ticker: 'VOW3', name: 'Volkswagen' },
  { ticker: 'VOLV B', name: 'Volvo' },
  { ticker: 'VNA', name: 'Vonovia' },
  { ticker: 'WDP', name: 'Warehouses De Pauw' },
  { ticker: 'WRT1V', name: 'Wartsila' },
  { ticker: 'WEIR', name: 'Weir Group' },
  { ticker: 'MF', name: 'Wendel' },
  { ticker: 'WTB', name: 'Whitbread' },
  { ticker: 'SMWH', name: 'WH Smith' },
  { ticker: 'WIE', name: 'Wienerberger' },
  { ticker: 'WKL', name: 'Wolters Kluwer' },
  { ticker: 'WLN', name: 'Worldline' },
  { ticker: 'WPP', name: 'WPP' },
  { ticker: 'YAR', name: 'Yara International' },
  { ticker: 'ZAL', name: 'Zalando' },
  { ticker: 'ZURN', name: 'Zurich Insurance' },
];

// Search function for autocomplete
export function searchSTOXX600Stocks(query: string): Stock[] {
  if (!query.trim()) return [];

  const q = query.toLowerCase();

  // Separate matches into priority groups (ticker and name have equal importance)
  const exact: Stock[] = [];
  const startsWith: Stock[] = [];
  const contains: Stock[] = [];

  for (const stock of STOXX600_STOCKS) {
    const tickerLower = stock.ticker.toLowerCase();
    const nameLower = stock.name.toLowerCase();

    if (tickerLower === q || nameLower === q) {
      exact.push(stock);
    } else if (tickerLower.startsWith(q) || nameLower.startsWith(q)) {
      startsWith.push(stock);
    } else if (tickerLower.includes(q) || nameLower.includes(q)) {
      contains.push(stock);
    }
  }

  // Return prioritized results: exact > starts with > contains
  return [...exact, ...startsWith, ...contains].slice(0, 10);
}
