import { createContext, useContext, useState, useEffect } from 'react';
import type { ReactNode } from 'react';
type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    'chess.logout': 'Log out',
    'chess.resetAndLogout': 'Reset & log out',

    // Coaches
    'coaches.title': 'AI-Powered Software|for Chess Coaches',
    'coaches.navHome': 'Home',
    'coaches.roleLabel.coach': 'Coach',
    'coaches.roleLabel.student': 'Student',
    'coaches.navMessages': 'Messages',
    'coaches.messages.title': 'Messages',
    'coaches.messages.empty': 'No conversations yet',
    'coaches.messages.emptyHint': 'Invite a student to the platform to start chatting',
    'coaches.studentDashboard.coachLabel': 'Your coach',
    'coaches.studentDashboard.activePacks': 'Your Lesson Packs',
    'coaches.studentDashboard.noPacks': 'No active lesson packs yet.',
    'coaches.studentDashboard.recentLessons': 'Recent Lessons',
    'coaches.studentDashboard.noAccount': 'No student account linked yet.',
    'coaches.invoice.send': 'Send invoice',
    'coaches.students.inviteToPlatform': 'Invite to platform',
    'coaches.students.accountLinked': 'Account linked',
    'coaches.students.linkCopied': 'Link copied!',
    'coaches.students.copyInviteLink': 'Copy invite link',
    'coaches.navProfile': 'My Profile',
    'coaches.navCalendar': 'My Calendar',
    'coaches.profile.name': 'Name',
    'coaches.profile.rates': 'Lesson Rates',
    'coaches.profile.pricingTitle': 'Lessons Pricing',
    'coaches.profile.city': 'City',
    'coaches.profile.currency': 'Currency',
    'coaches.profile.rate': 'Lesson Price',
    'coaches.profile.duration': 'Duration',
    'coaches.profile.bundles': 'Bundle Offers',
    'coaches.profile.addBundle': 'Add bundle offer',
    'coaches.profile.noBundles': 'No bundle offers yet.',
    'coaches.profile.lessonsFor': 'lessons for',
    'coaches.profile.lessonsLabel': 'lessons',
    'coaches.profile.forWord': 'for',
    'coaches.profile.bundleLessons': 'Lessons',
    'coaches.profile.bundlePrice': 'Price',
    'coaches.profile.chesscomUsername': 'Chess.com username',
    'coaches.profile.lichessUsername': 'Lichess username',
    'coaches.profile.infoTitle': 'Personal Information',
    'coaches.profile.personalTitle': 'Personal Info',
    'coaches.profile.edit': 'Edit',
    'coaches.profile.email': 'Email',
    'coaches.profile.phone': 'WhatsApp',
    'coaches.students.email': 'Email',
    'coaches.students.phone': 'WhatsApp',
    'coaches.students.city': 'City',
    'coaches.profile.saveInfo': 'Save profile',
    'coaches.profile.saveRates': 'Save lesson rates',
    'coaches.profile.saved': 'Saved!',
    'coaches.navStudents': 'My Students',
    'coaches.navPacks': 'Payments',
    'coaches.onboardingInstruction': 'Sign in to get started',
    'coaches.onboardingDescription': 'Schedule lessons, manage students and payments, prepare lessons, give homework, digitize chess books. All in one place.',
    'coaches.startFresh': 'Start fresh',
    'coaches.stopProcessing': 'Stop',
    'coaches.navDiagram': 'Position Scanner',
    'coaches.diagram.uploadPrompt': 'Upload a chess diagram',
    'coaches.diagram.dropHint': 'Drop an image, click to browse, or paste (⌘V)',
    'coaches.diagram.explainer': 'Scan a photo, screenshot or image of a chess position into FEN.',
    'coaches.diagram.explainerNote': 'Single or multiple diagrams per image.',
    'coaches.diagram.analyze': 'Scan position',
    'coaches.diagram.analyzing': 'Scanning diagram...',
    'coaches.diagram.analyzingPlural': 'Scanning diagrams...',
    'coaches.diagram.done': 'Position scanned',
    'coaches.diagram.donePlural': 'Positions scanned',
    'coaches.diagram.readerLabel': 'Scanner',
    'coaches.diagram.readerTitle': 'Position Scanner',
    'coaches.diagram.diagramLabel': 'Diagram',
    'coaches.diagram.noneDetected': 'No diagram detected',
    'coaches.diagram.changePiece': 'Change piece',
    'coaches.diagram.erasePiece': 'Remove piece',
    'coaches.diagram.addPiece': 'Add piece',
    'coaches.diagram.editBoard': 'Edit board',
    'coaches.diagram.copyFen': 'Copy FEN',

    'coaches.diagram.copied': 'Copied!',
    'coaches.diagram.whiteToPlay': 'White to play',
    'coaches.diagram.blackToPlay': 'Black to play',
    'coaches.navMistakes': 'Mistake Finder',
    'coaches.mistakes.uploadPrompt': 'Upload a PGN file',
    'coaches.mistakes.uploadHint': '.pgn or .txt — must contain clock annotations [%clk]',
    'coaches.mistakes.findButton': 'Find mistakes',
    'coaches.mistakes.noClockData': 'No clock data found in this PGN. Moves need [%clk h:mm:ss] annotations.',
    'coaches.mistakes.movesWithClock': 'moves with clock data',
    'coaches.mistakes.noMistakes': 'No time-management mistakes found!',
    'coaches.mistakes.mistakeFound': 'time-management mistake found',
    'coaches.mistakes.mistakesFound': 'time-management mistakes found',
    'coaches.mistakes.ofClock': 'of clock spent',
    'coaches.mistakes.clockBefore': 'Clock before',
    'coaches.mistakes.timeSpent': 'Time spent',
    'coaches.mistakes.clockAfter': 'Clock after',
    'coaches.mistakes.analyzeAnother': 'Analyze another game',
    'coaches.mistakes.categoryTime': 'Time Management',
    'coaches.mistakes.categoryTbd': 'To Be Determined',
    'coaches.mistakes.a1.line1': 'Underthinking',
    'coaches.mistakes.a1.line2': 'a critical moment',
    'coaches.mistakes.a2.line1': 'Over-calculating',
    'coaches.mistakes.a2.line2': 'equal alternatives',
    'coaches.mistakes.b1.line1': 'Over-extending',
    'coaches.mistakes.b1.line2': 'a winning position',
    'coaches.mistakes.comingSoon': 'Coming soon',
    'coaches.comingSoon': 'Coming soon..',
    'coaches.navAbout': 'About',
    'coaches.about.description': 'Schedule lessons, manage students and payments, prepare lessons, give homework, digitize chess books. All in one place.',
    'coaches.about.credits': 'Credits & Licenses',
    'coaches.about.chesscomApi': 'Player profiles and game data',
    'coaches.about.gemini': 'Position scanning',
    'coaches.mistakes.selectAnalysis': 'Select an analysis',

    // Students panel — scheduling
    'coaches.students.title': 'My Students',
    'coaches.students.empty': 'No students yet.\nAdd your first student to get started.',
    'coaches.students.addStudent': 'Add Student',
    'coaches.students.editStudent': 'Edit',
    'coaches.students.deleteStudent': 'Delete',
    'coaches.students.deleteConfirm': 'Delete this student and all their lessons?',
    'coaches.students.name': 'Name',
    'coaches.students.timezone': 'Timezone',
    'coaches.students.currency': 'Currency',
    'coaches.students.recurringSlot': 'Recurring lesson slot (optional)',
    'coaches.students.recurringLabel': 'Recurring lesson:',
    'coaches.students.noRecurring': 'No recurring slot',
    'coaches.students.save': 'Save',
    'coaches.students.cancel': 'Cancel',
    'coaches.students.search': 'Search students...',
    'coaches.students.scheduleLesson': 'Schedule',
    'coaches.students.scheduleLessonFull': 'Schedule a lesson',
    'coaches.students.reschedule': 'Reschedule',
    'coaches.students.when': 'When',
    'coaches.students.duration': 'Duration',
    'coaches.students.minutes': 'min',
    'coaches.students.scheduled': 'Scheduled',
    'coaches.students.completedStatus': 'Completed',
    'coaches.students.cancelledStatus': 'Cancelled',
    'coaches.students.rescheduledStatus': 'Rescheduled',
    'coaches.students.dstAlert': 'Daylight saving time change coming',
    'coaches.student.upcoming': 'Upcoming',
    'coaches.student.history': 'Past',
    'coaches.students.deleteStudentFull': 'Delete student',
    'coaches.student.noLessons': 'No lessons yet. Schedule one to get started.',
    'coaches.lessons.title': 'Lessons',
    'coaches.lessons.add': 'Add lesson',
    'coaches.lessons.upcoming': 'Upcoming',
    'coaches.lessons.past': 'Past lessons',
    'coaches.lessons.empty': 'No lessons yet',
    'coaches.lessons.status.scheduled': 'Scheduled',
    'coaches.lessons.status.done': 'Done',
    'coaches.lessons.status.cancelled': 'Cancelled',
    'coaches.lessons.status.tbd': 'To be determined',
    'coaches.calendar.title': 'My Calendar',
    'coaches.calendar.noLessons': 'No lessons this week. Schedule one from My Students.',
    'coaches.calendar.today': 'Today',
    'coaches.calendar.newLesson': 'New lesson',
    'coaches.calendar.selectStudent': 'Select a student...',
    'coaches.calendar.save': 'Save',
    'coaches.calendar.lessonStatus': 'Status',
    'coaches.calendar.viewStudent': 'View student',
    'coaches.calendar.lesson': 'lesson',
    'coaches.calendar.lessons': 'lessons',
    'coaches.calendar.detectTitle': 'Are you in...',
    'coaches.calendar.confirm': 'Yes, confirm',
    'coaches.calendar.changeCity': 'No, change city',
    'coaches.calendar.setupTitle': 'Set your city',
    'coaches.calendar.setupDesc': 'So we can display lesson times in your timezone.',
    'coaches.calendar.myCity': 'My city',
    // Packs
    'coaches.packs.title': 'Lesson Packs',
    'coaches.packs.empty': 'No packs yet. Create one from a student\'s page or use the button above.',
    'coaches.packs.noStudents': 'First, add a student from the My Students page.',
    'coaches.packs.goToStudents': 'Go to My Students',
    'coaches.packs.remaining': 'remaining',
    'coaches.packs.lessonsRemaining': 'Lessons remaining ',
    'coaches.packs.lessonsUnpaid': 'Lessons unpaid ',
    'coaches.packs.used': 'used',
    'coaches.packs.of': 'of',
    'coaches.packs.lessons': 'lessons',
    'coaches.packs.newPack': 'New Pack',
    'coaches.packs.editPack': 'Edit Pack',
    'coaches.packs.deletePack': 'Delete Pack',
    'coaches.packs.totalLessons': 'Total lessons',
    'coaches.packs.lessonsDone': 'Lessons done',
    'coaches.packs.lessonsPaid': 'Lessons paid',
    'coaches.packs.price': 'Price',
    'coaches.packs.currency': 'Currency',
    'coaches.packs.source': 'Source',
    'coaches.packs.note': 'Note (optional)',
    'coaches.packs.active': 'Active',
    'coaches.packs.completed': 'Completed',
    'coaches.packs.markCompleted': 'Mark completed',
    'coaches.packs.reactivate': 'Reactivate',
    'coaches.packs.history': 'Past packs',
    'coaches.packs.completedPacks': 'Completed packs',
    'coaches.packs.credits': 'credits',
    'coaches.packs.allSources': 'All sources',
    'coaches.packs.superprof': 'Superprof',
    'coaches.packs.website': 'Website',
    'coaches.packs.direct': 'Direct',
    'coaches.packs.other': 'Other',
    'coaches.packs.student': 'Student',
    'coaches.packs.save': 'Save',
    'coaches.packs.cancel': 'Cancel',
    // Shared
    'coaches.sectionAdmin': 'Coaching',
    'coaches.sectionAITools': 'AI Tools',
    'coaches.sectionKnowledge': 'Knowledge Center',
    'coaches.navPositions': 'Positions',
    'coaches.positions.folders': 'Folders',
    'coaches.positions.rootFolder': 'All positions',
    'coaches.positions.newFolder': 'New folder',
    'coaches.positions.newSubfolder': 'New subfolder',
    'coaches.positions.openFolder': 'Open folder',
    'coaches.positions.rename': 'Rename',
    'coaches.positions.delete': 'Delete',
    'coaches.positions.folderNamePlaceholder': 'Folder name',
    'coaches.positions.positions': 'positions',
    'coaches.positions.empty': 'No positions in this folder yet. Save one from the Position Scanner.',
    'coaches.positions.confirmDeleteFolder': 'Delete this folder and all its subfolders? Positions inside move back to All positions.',
    'coaches.positions.confirmDeletePosition': 'Delete this position?',
    'coaches.positions.notesPlaceholder': 'Add your notes...',
    'coaches.positions.addNotes': 'Add notes...',
    'coaches.positions.save': 'Save',
    'coaches.positions.cancel': 'Cancel',
    'coaches.positions.saveToKnowledge': 'Save to Knowledge Center',
    'coaches.positions.chooseFolder': 'Choose folder',
    'coaches.positions.saved': 'Saved',
    'coaches.homePrompt': 'Pick a feature to get started',
    'coaches.onboarding.welcome.coach': 'Welcome to LUMNA, the app for chess coaches!',
    'coaches.onboarding.step.profile.before.coach': 'Complete your ',
    'coaches.onboarding.step.profile.link.coach': 'Coach Profile',
    'coaches.onboarding.step.students.before': 'Add one student in ',
    'coaches.onboarding.step.students.link': 'My Students',
    'coaches.onboarding.step.calendar.before': 'Book your first lesson in ',
    'coaches.onboarding.step.calendar.link': 'My Calendar',
    'coaches.previous': 'Previous',
    'coaches.processing': 'Reading in progress',
    'coaches.navAdmin': 'Admin',
    // Admin panel
    'coaches.admin.user1': 'user',
    'coaches.admin.users': 'users',
    'coaches.admin.dailyTimeSpent': 'Daily Time Spent (minutes)',
    'coaches.admin.time': 'Time',
    'coaches.admin.failedLoad': 'Failed to load users',
    'coaches.admin.user': 'User',
    'coaches.admin.joined': 'Joined',
    'coaches.admin.lastActive': 'Last Active',
    'coaches.admin.sessions': 'Sessions',
    'coaches.admin.selectFeature': 'Select a feature',
    'coaches.admin.showingDataFor': 'Showing data for',
    'coaches.admin.geminiUsage': 'Gemini API Usage',
    'coaches.admin.total': 'total',
    'coaches.admin.googleBilling': 'Google Billing',
    'coaches.admin.feature': 'Feature',
    'coaches.admin.uses': 'Uses',
    'coaches.admin.tokens': 'Tokens',
    'coaches.admin.avgTime': 'Avg time',
    'coaches.admin.avgCost': 'Avg cost',
    'coaches.admin.cost': 'Cost',
    'coaches.admin.imagesProcessed': 'Images processed',
    'coaches.admin.images': 'Images',
    'coaches.admin.model': 'Model',
    'coaches.admin.calls': 'Calls',
    'coaches.admin.paid': 'Paid',
    'coaches.admin.free': 'Free',
    'coaches.admin.input': 'Input',
    'coaches.admin.output': 'Output',
    'coaches.admin.thinking': 'Thinking',
    'coaches.admin.errors': 'Errors',
    'coaches.admin.history': 'History',
    'coaches.admin.invocations': 'invocations',
    'coaches.admin.models': 'Models',
    'coaches.admin.tier': 'Tier',
    'coaches.admin.retry': 'Retry',

    // Role selection
    'coaches.roleSelection.welcome': 'Welcome!',
    'coaches.roleSelection.question': 'How will you use LUMNA?',
    'coaches.roleSelection.coach': "I'm a coach",
    'coaches.roleSelection.coachDesc': 'Manage students & lessons',
    'coaches.roleSelection.student': "I'm a student",

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
  },
  fr: {
    'chess.logout': 'Se déconnecter',
    'chess.resetAndLogout': 'Réinitialiser et se déconnecter',

    // Coaches
    'coaches.title': 'Logiciel IA pour|entra\u00EEneurs d\'\u00E9checs',
    'coaches.navHome': 'Accueil',
    'coaches.roleLabel.coach': 'Entra\u00EEneur',
    'coaches.roleLabel.student': '\u00C9l\u00E8ve',
    'coaches.navMessages': 'Messages',
    'coaches.messages.title': 'Messages',
    'coaches.messages.empty': 'Aucune conversation',
    'coaches.messages.emptyHint': "Invitez un \u00E9l\u00E8ve sur la plateforme pour commencer \u00E0 discuter",
    'coaches.studentDashboard.coachLabel': 'Votre entra\u00EEneur',
    'coaches.studentDashboard.activePacks': 'Vos packs de cours',
    'coaches.studentDashboard.noPacks': 'Aucun pack de cours actif.',
    'coaches.studentDashboard.recentLessons': 'Cours r\u00E9cents',
    'coaches.studentDashboard.noAccount': "Aucun compte \u00E9l\u00E8ve li\u00E9.",
    'coaches.invoice.send': 'Envoyer une facture',
    'coaches.students.inviteToPlatform': 'Inviter sur la plateforme',
    'coaches.students.accountLinked': 'Compte lié',
    'coaches.students.linkCopied': 'Lien copié !',
    'coaches.students.copyInviteLink': "Copier le lien d'invitation",
    'coaches.navProfile': 'Mon Profil',
    'coaches.navCalendar': 'Mon Calendrier',
    'coaches.profile.name': 'Nom',
    'coaches.profile.rates': 'Tarifs des cours',
    'coaches.profile.pricingTitle': 'Tarifs des cours',
    'coaches.profile.city': 'Ville',
    'coaches.profile.currency': 'Devise',
    'coaches.profile.rate': 'Prix du cours',
    'coaches.profile.duration': 'Durée',
    'coaches.profile.bundles': 'Offres de forfaits',
    'coaches.profile.addBundle': 'Ajouter une offre de forfait',
    'coaches.profile.noBundles': 'Aucune offre de forfait.',
    'coaches.profile.lessonsFor': 'cours pour',
    'coaches.profile.lessonsLabel': 'cours',
    'coaches.profile.forWord': 'pour',
    'coaches.profile.bundleLessons': 'Cours',
    'coaches.profile.bundlePrice': 'Prix',
    'coaches.profile.chesscomUsername': 'Pseudo Chess.com',
    'coaches.profile.lichessUsername': 'Pseudo Lichess',
    'coaches.profile.infoTitle': 'Informations personnelles',
    'coaches.profile.personalTitle': 'Infos personnelles',
    'coaches.profile.edit': 'Modifier',
    'coaches.profile.email': 'Email',
    'coaches.profile.phone': 'WhatsApp',
    'coaches.students.email': 'Email',
    'coaches.students.phone': 'WhatsApp',
    'coaches.students.city': 'Ville',
    'coaches.profile.saveInfo': 'Enregistrer le profil',
    'coaches.profile.saveRates': 'Enregistrer les tarifs',
    'coaches.profile.saved': 'Enregistré !',
    'coaches.navStudents': 'Mes élèves',
    'coaches.navPacks': 'Paiements',
    'coaches.onboardingInstruction': 'Connectez-vous pour commencer',
    'coaches.onboardingDescription': 'Planifiez vos cours, gérez vos élèves et vos paiements, préparez vos leçons, donnez des devoirs, numérisez vos livres d\'échecs. Tout au même endroit.',
    'coaches.startFresh': 'Recommencer',
    'coaches.stopProcessing': 'Arrêter',
    'coaches.navDiagram': 'Scanner de position',
    'coaches.diagram.uploadPrompt': 'Importer un diagramme d\'échecs',
    'coaches.diagram.dropHint': 'Glissez une image, cliquez pour parcourir, ou collez (⌘V)',
    'coaches.diagram.explainer': 'Scannez une photo, capture d\'écran ou image d\'une position d\'échecs en FEN.',
    'coaches.diagram.explainerNote': 'Un ou plusieurs diagrammes par image.',
    'coaches.diagram.analyze': 'Scanner la position',
    'coaches.diagram.analyzing': 'Scan du diagramme...',
    'coaches.diagram.analyzingPlural': 'Scan des diagrammes...',
    'coaches.diagram.done': 'Position scannée',
    'coaches.diagram.donePlural': 'Positions scannées',
    'coaches.diagram.readerLabel': 'Scanner',
    'coaches.diagram.readerTitle': 'Scanner de position',
    'coaches.diagram.diagramLabel': 'Diagramme',
    'coaches.diagram.noneDetected': 'Aucun diagramme détecté',
    'coaches.diagram.changePiece': 'Changer la pièce',
    'coaches.diagram.erasePiece': 'Supprimer la pièce',
    'coaches.diagram.addPiece': 'Ajouter une pièce',
    'coaches.diagram.editBoard': 'Modifier l\'échiquier',
    'coaches.diagram.copyFen': 'Copier le FEN',

    'coaches.diagram.copied': 'Copié !',
    'coaches.diagram.whiteToPlay': 'Les Blancs jouent',
    'coaches.diagram.blackToPlay': 'Les Noirs jouent',
    'coaches.navMistakes': 'Détecteur d\'erreurs',
    'coaches.mistakes.uploadPrompt': 'Importer un fichier PGN',
    'coaches.mistakes.uploadHint': '.pgn ou .txt — doit contenir des annotations d\'horloge [%clk]',
    'coaches.mistakes.findButton': 'Trouver les erreurs',
    'coaches.mistakes.noClockData': 'Aucune donnée d\'horloge trouvée dans ce PGN. Les coups doivent avoir des annotations [%clk h:mm:ss].',
    'coaches.mistakes.movesWithClock': 'coups avec données d\'horloge',
    'coaches.mistakes.noMistakes': 'Aucune erreur de gestion du temps trouvée !',
    'coaches.mistakes.mistakeFound': 'erreur de gestion du temps trouvée',
    'coaches.mistakes.mistakesFound': 'erreurs de gestion du temps trouvées',
    'coaches.mistakes.ofClock': 'du temps utilisé',
    'coaches.mistakes.clockBefore': 'Horloge avant',
    'coaches.mistakes.timeSpent': 'Temps passé',
    'coaches.mistakes.clockAfter': 'Horloge après',
    'coaches.mistakes.analyzeAnother': 'Analyser une autre partie',
    'coaches.mistakes.categoryTime': 'Gestion du temps',
    'coaches.mistakes.categoryTbd': 'À déterminer',
    'coaches.mistakes.a1.line1': 'Sous-réfléchir',
    'coaches.mistakes.a1.line2': 'un moment critique',
    'coaches.mistakes.a2.line1': 'Sur-calculer',
    'coaches.mistakes.a2.line2': 'des alternatives égales',
    'coaches.mistakes.b1.line1': 'Sur-jouer',
    'coaches.mistakes.b1.line2': 'une position gagnante',
    'coaches.mistakes.comingSoon': 'Bientôt disponible',
    'coaches.comingSoon': 'Bientôt disponible..',
    'coaches.navAbout': 'À propos',
    'coaches.about.description': 'Planifiez vos cours, gérez vos élèves et vos paiements, préparez vos leçons, donnez des devoirs, numérisez vos livres d\'échecs. Tout au même endroit.',
    'coaches.about.credits': 'Crédits & Licences',
    'coaches.about.chesscomApi': 'Profils de joueurs et données de parties',
    'coaches.about.gemini': 'Scan de positions',
    'coaches.mistakes.selectAnalysis': 'Sélectionnez une analyse',

    // Students panel — scheduling
    'coaches.students.title': 'Mes élèves',
    'coaches.students.empty': 'Aucun élève pour le moment.\nAjoutez votre premier élève pour commencer.',
    'coaches.students.addStudent': 'Ajouter un élève',
    'coaches.students.editStudent': 'Modifier',
    'coaches.students.deleteStudent': 'Supprimer',
    'coaches.students.deleteConfirm': 'Supprimer cet élève et tous ses cours ?',
    'coaches.students.name': 'Nom',
    'coaches.students.timezone': 'Fuseau horaire',
    'coaches.students.currency': 'Devise',
    'coaches.students.recurringSlot': 'Créneau de cours récurrent (optionnel)',
    'coaches.students.recurringLabel': 'Cours récurrent :',
    'coaches.students.noRecurring': 'Pas de créneau récurrent',
    'coaches.students.save': 'Enregistrer',
    'coaches.students.cancel': 'Annuler',
    'coaches.students.search': 'Rechercher des élèves...',
    'coaches.students.scheduleLesson': 'Planifier',
    'coaches.students.scheduleLessonFull': 'Planifier un cours',
    'coaches.students.reschedule': 'Reprogrammer',
    'coaches.students.when': 'Quand',
    'coaches.students.duration': 'Durée',
    'coaches.students.minutes': 'min',
    'coaches.students.scheduled': 'Planifié',
    'coaches.students.completedStatus': 'Terminé',
    'coaches.students.cancelledStatus': 'Annulé',
    'coaches.students.rescheduledStatus': 'Reporté',
    'coaches.students.dstAlert': 'Changement d\'heure (heure d\'été) à venir',
    'coaches.student.upcoming': 'À venir',
    'coaches.student.history': 'Passés',
    'coaches.students.deleteStudentFull': 'Supprimer l\'élève',
    'coaches.student.noLessons': 'Aucun cours pour le moment. Planifiez-en un pour commencer.',
    'coaches.lessons.title': 'Cours',
    'coaches.lessons.add': 'Ajouter un cours',
    'coaches.lessons.upcoming': 'A venir',
    'coaches.lessons.past': 'Cours passés',
    'coaches.lessons.empty': 'Aucun cours',
    'coaches.lessons.status.scheduled': 'Planifié',
    'coaches.lessons.status.done': 'Fait',
    'coaches.lessons.status.cancelled': 'Annulé',
    'coaches.lessons.status.tbd': 'A déterminer',
    'coaches.calendar.title': 'Mon Calendrier',
    'coaches.calendar.noLessons': 'Aucun cours cette semaine. Planifiez-en un depuis Mes élèves.',
    'coaches.calendar.today': "Aujourd'hui",
    'coaches.calendar.newLesson': 'Nouveau cours',
    'coaches.calendar.selectStudent': 'Choisir un élève...',
    'coaches.calendar.save': 'Enregistrer',
    'coaches.calendar.lessonStatus': 'Statut',
    'coaches.calendar.viewStudent': 'Voir l\'élève',
    'coaches.calendar.lesson': 'cours',
    'coaches.calendar.lessons': 'cours',
    'coaches.calendar.detectTitle': 'Vous êtes à...',
    'coaches.calendar.confirm': 'Oui, confirmer',
    'coaches.calendar.changeCity': 'Non, changer de ville',
    'coaches.calendar.setupTitle': 'Indiquez votre ville',
    'coaches.calendar.setupDesc': 'Pour afficher les heures de cours dans votre fuseau horaire.',
    'coaches.calendar.myCity': 'Ma ville',
    // Packs
    'coaches.packs.title': 'Forfaits de cours',
    'coaches.packs.empty': 'Aucun forfait pour le moment. Créez-en un depuis la page d\'un élève ou via le bouton ci-dessus.',
    'coaches.packs.noStudents': 'Commencez par ajouter un élève depuis la page Mes élèves.',
    'coaches.packs.goToStudents': 'Aller à Mes élèves',
    'coaches.packs.remaining': 'restant(s)',
    'coaches.packs.lessonsRemaining': 'Cours restants',
    'coaches.packs.lessonsUnpaid': 'Cours impayés',
    'coaches.packs.used': 'utilisé(s)',
    'coaches.packs.of': 'sur',
    'coaches.packs.lessons': 'cours',
    'coaches.packs.newPack': 'Nouveau forfait',
    'coaches.packs.editPack': 'Modifier le forfait',
    'coaches.packs.deletePack': 'Supprimer le forfait',
    'coaches.packs.totalLessons': 'Nombre de cours',
    'coaches.packs.lessonsDone': 'Cours effectués',
    'coaches.packs.lessonsPaid': 'Cours payés',
    'coaches.packs.price': 'Prix',
    'coaches.packs.currency': 'Devise',
    'coaches.packs.source': 'Source',
    'coaches.packs.note': 'Note (optionnel)',
    'coaches.packs.active': 'Actif',
    'coaches.packs.completed': 'Terminé',
    'coaches.packs.markCompleted': 'Marquer terminé',
    'coaches.packs.reactivate': 'Réactiver',
    'coaches.packs.history': 'Forfaits passés',
    'coaches.packs.completedPacks': 'Forfaits terminés',
    'coaches.packs.credits': 'crédits',
    'coaches.packs.allSources': 'Toutes les sources',
    'coaches.packs.superprof': 'Superprof',
    'coaches.packs.website': 'Site web',
    'coaches.packs.direct': 'Direct',
    'coaches.packs.other': 'Autre',
    'coaches.packs.student': 'Élève',
    'coaches.packs.save': 'Enregistrer',
    'coaches.packs.cancel': 'Annuler',
    // Shared
    'coaches.sectionAdmin': 'Coaching',
    'coaches.sectionAITools': 'Outils IA',
    'coaches.sectionKnowledge': 'Centre de connaissances',
    'coaches.navPositions': 'Positions',
    'coaches.positions.folders': 'Dossiers',
    'coaches.positions.rootFolder': 'Toutes les positions',
    'coaches.positions.newFolder': 'Nouveau dossier',
    'coaches.positions.newSubfolder': 'Nouveau sous-dossier',
    'coaches.positions.openFolder': 'Ouvrir le dossier',
    'coaches.positions.rename': 'Renommer',
    'coaches.positions.delete': 'Supprimer',
    'coaches.positions.folderNamePlaceholder': 'Nom du dossier',
    'coaches.positions.positions': 'positions',
    'coaches.positions.empty': 'Aucune position dans ce dossier. Enregistrez-en une depuis le Scanner de position.',
    'coaches.positions.confirmDeleteFolder': 'Supprimer ce dossier et ses sous-dossiers ? Les positions seront replacées dans « Toutes les positions ».',
    'coaches.positions.confirmDeletePosition': 'Supprimer cette position ?',
    'coaches.positions.notesPlaceholder': 'Ajouter des notes...',
    'coaches.positions.addNotes': 'Ajouter des notes...',
    'coaches.positions.save': 'Enregistrer',
    'coaches.positions.cancel': 'Annuler',
    'coaches.positions.saveToKnowledge': 'Enregistrer dans le Centre de connaissances',
    'coaches.positions.chooseFolder': 'Choisir un dossier',
    'coaches.positions.saved': 'Enregistré',
    'coaches.homePrompt': 'Choisissez une fonctionnalité pour commencer',
    'coaches.onboarding.welcome.coach': 'Bienvenue sur LUMNA, l\'app pour les coachs d\'échecs !',
    'coaches.onboarding.step.profile.before.coach': 'Complétez votre ',
    'coaches.onboarding.step.profile.link.coach': 'Profil Coach',
    'coaches.onboarding.step.students.before': 'Ajoutez un élève dans ',
    'coaches.onboarding.step.students.link': 'Mes Élèves',
    'coaches.onboarding.step.calendar.before': 'Planifiez votre premier cours dans ',
    'coaches.onboarding.step.calendar.link': 'Mon Calendrier',
    'coaches.previous': 'Précédent',
    'coaches.processing': 'Lecture en cours',
    'coaches.navAdmin': 'Admin',
    // Admin panel
    'coaches.admin.user1': 'utilisateur',
    'coaches.admin.users': 'utilisateurs',
    'coaches.admin.dailyTimeSpent': 'Temps passé par jour (minutes)',
    'coaches.admin.time': 'Temps',
    'coaches.admin.failedLoad': 'Erreur de chargement des utilisateurs',
    'coaches.admin.user': 'Utilisateur',
    'coaches.admin.joined': 'Inscrit',
    'coaches.admin.lastActive': 'Dernière activité',
    'coaches.admin.sessions': 'Sessions',
    'coaches.admin.selectFeature': 'Sélectionner une fonctionnalité',
    'coaches.admin.showingDataFor': 'Données pour',
    'coaches.admin.geminiUsage': 'Utilisation API Gemini',
    'coaches.admin.total': 'total',
    'coaches.admin.googleBilling': 'Facturation Google',
    'coaches.admin.feature': 'Fonctionnalité',
    'coaches.admin.uses': 'Utilisations',
    'coaches.admin.tokens': 'Tokens',
    'coaches.admin.avgTime': 'Temps moy.',
    'coaches.admin.avgCost': 'Coût moy.',
    'coaches.admin.cost': 'Coût',
    'coaches.admin.imagesProcessed': 'Images traitées',
    'coaches.admin.images': 'Images',
    'coaches.admin.model': 'Modèle',
    'coaches.admin.calls': 'Appels',
    'coaches.admin.paid': 'Payant',
    'coaches.admin.free': 'Gratuit',
    'coaches.admin.input': 'Entrée',
    'coaches.admin.output': 'Sortie',
    'coaches.admin.thinking': 'Réflexion',
    'coaches.admin.errors': 'Erreurs',
    'coaches.admin.history': 'Historique',
    'coaches.admin.invocations': 'invocations',
    'coaches.admin.models': 'Modèles',
    'coaches.admin.tier': 'Niveau',
    'coaches.admin.retry': 'Réessai',

    // Role selection
    'coaches.roleSelection.welcome': 'Bienvenue !',
    'coaches.roleSelection.question': 'Comment allez-vous utiliser LUMNA ?',
    'coaches.roleSelection.coach': 'Je suis entra\u00EEneur',
    'coaches.roleSelection.coachDesc': 'Gérer élèves & cours',
    'coaches.roleSelection.student': 'Je suis élève',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check URL param first (used when transferring between browsers)
    try {
      const params = new URLSearchParams(window.location.search);
      const urlLang = params.get('lang');
      if (urlLang === 'en' || urlLang === 'fr') {
        localStorage.setItem('language', urlLang);
        const url = new URL(window.location.href);
        url.searchParams.delete('lang');
        window.history.replaceState({}, '', url.pathname + url.search + url.hash);
        return urlLang;
      }
    } catch {}
    const saved = localStorage.getItem('language');
    if (saved) return saved as Language;
    const browserLang = navigator.language || navigator.languages?.[0] || '';
    return browserLang.startsWith('fr') ? 'fr' : 'en';
  });

  // Keep <html lang> in sync so Google Sign-In (and other locale-aware libs) pick up our language
  useEffect(() => {
    document.documentElement.lang = language;
  }, [language]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    // Fire-and-forget server persistence (requires auth; silently fails if not logged in)
    fetch('/api/auth/language', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      credentials: 'include',
      body: JSON.stringify({ language: lang }),
    }).catch(() => {});
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
