import { createContext, useContext, useState } from 'react';
import type { ReactNode } from 'react';
import axios from 'axios';

type Language = 'en' | 'fr';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
  tAll: (key: string) => { en: string; fr: string };
}

const translations: Record<Language, Record<string, string>> = {
  en: {
    // Portfolio
    'portfolio.title': 'My Portfolio',
    'portfolio.subtitle': 'Track your investment transactions and performance',
    'portfolio.editButton': 'Edit transactions',
    'portfolio.privateMode': 'Private mode',
    'portfolio.totalValue': 'Current Value (EUR)',
    'portfolio.costBasis': 'Invested Capital (EUR)',
    'portfolio.totalGain': 'Total Gain',

    // Accounts
    'accounts.title': 'Investment Accounts',
    'accounts.addAccount': 'Add Account',
    'accounts.accountType': 'Account Type',
    'accounts.bank': 'Bank / Broker',
    'accounts.selectType': 'Select type...',
    'accounts.selectBank': 'Select bank...',
    'accounts.create': 'Create',
    'accounts.cancel': 'Cancel',
    'accounts.noAccounts': 'No accounts yet. Create an account to track fees.',
    'accounts.type': 'Type',
    'accounts.tax': 'tax',
    'accounts.fees': 'Fees',

    // Transactions
    'transactions.title': 'Transactions History',
    'transactions.addTransaction': 'Add transactions manually',
    'transactions.importRevolut': 'Import directly from Revolut',
    'transactions.close': 'Close',
    'transactions.allStocks': 'All stocks',
    'transactions.searchStocks': 'Search stocks...',
    'transactions.buy': 'Buy',
    'transactions.sell': 'Sell',
    'transactions.quantity': 'Quantity',
    'transactions.year': 'Year',
    'transactions.month': 'Month',
    'transactions.day': 'Day',
    'transactions.noAccount': 'No account',
    'transactions.add': 'Add',
    'transactions.done': 'Done',
    'transactions.priceNote': 'The price will be fetched automatically from market data for the selected date.',
    'transactions.selectAccount': 'Select an account to track fees.',
    'transactions.noTransactions': 'No transactions yet. Add your first transaction to get started.',
    'transactions.shares': 'shares',

    // Holdings
    'holdings.title': 'Current Holdings',
    'holdings.stock': 'Stock',
    'holdings.shares': 'Shares',
    'holdings.price': 'Share Price',
    'holdings.value': 'Value (EUR)',
    'holdings.weight': 'Weight',
    'holdings.gain': 'Gain',
    'holdings.held': 'Held',

    // Performance
    'performance.title': 'Portfolio Performance',
    'performance.cagr': 'Compound Annual Growth Rate (CAGR)',
    'performance.cagrFull': 'Compound Annual Growth Rate',
    'performance.cagrTooltip': 'The annualized rate of return, assuming profits are reinvested. Shows what your investment would grow at per year if growth was constant.',
    'performance.simpleReturn': 'Simple Return (SR)',
    'performance.simpleReturnTooltip': 'Total percentage gain or loss on your investment, calculated as (Current Value - Invested) / Invested.',
    'performance.twr': 'Time-Weighted Return (TWR)',
    'performance.twrFull': 'Time-Weighted Return',
    'performance.twrTooltip': 'Measures investment performance excluding the impact of deposits and withdrawals. Best for comparing portfolio manager performance.',
    'performance.mwr': 'Money-Weighted Return (MWR)',
    'performance.mwrFull': 'Money-Weighted Return',
    'performance.mwrTooltip': 'Measures your actual return including the timing and size of your deposits/withdrawals. Sensitive to when you add or withdraw money.',
    'performance.irr': 'Internal Rate of Return (IRR)',
    'performance.irrFull': 'Internal Rate of Return',
    'performance.irrTooltip': 'The annualized rate that makes the net present value of all cash flows equal to zero. Same calculation as MWR.',
    'performance.metricsInfoTitle': 'About Performance Metrics',
    'performance.metricsInfoText': 'Simple Return and CAGR do not account for intermediate cash flows (deposits/withdrawals). For portfolios with multiple transactions, TWR and MWR provide more accurate performance measures.',
    'performance.advancedMetrics': 'Advanced Performance Metrics',
    'performance.allTime': 'All Time',
    'performance.annualized': 'Annualized',
    'performance.srCagrExample': 'You invest €1,000 at the start of Year 0.\nAfter 1 year, you add €500.\nAfter 2 years, your portfolio is worth €1,815.\n\nSimple Return = (1815 - 1500) / 1500 = +21%\nCAGR = (1815 / 1500)^(1/2) - 1 = +10% per year\n\nNote: These metrics ignore WHEN you added the €500. They only compare total invested vs final value.',
    'performance.twrMwrExample': 'In January, you invest €10,000.\nBy June, it has grown to €11,000.\nYou then add €5,000.\nBy December, the total value is €17,000.\n\nTWR = (11000/10000) × (17000/16000) - 1 = +16.9%\n→ Measures pure investment performance by chaining sub-period returns.\n\nMWR = the rate r where: -10000 + (-5000)/(1+r)^0.5 + 17000/(1+r)^1 = 0 → r = +11.5%\n→ Your actual return, accounting for when you added money.\n\nNote: IRR is simply the annualized version of MWR.',
    'performance.perYear': '(per year)',
    'performance.showExample': 'Show example',
    'performance.year': 'year',
    'performance.years': 'years',
    'performance.month': 'month',
    'performance.months': 'months',
    'performance.since': 'Since',
    'performance.totalReturn': 'Portfolio Gains',
    'performance.benchmark.qqq': 'Benchmark: QQQ (Nasdaq-100)',
    'performance.benchmark.sp500': 'Benchmark: S&P 500',
    'performance.portfolio': 'Portfolio',
    'performance.invested': 'Invested capital',

    // Chess
    'chess.rapid': 'Rapid',
    'chess.bullet': 'Bullet',
    'chess.myData': 'My Data',
    'chess.noData': 'No Data Available',
    'chess.notEnoughGames': 'Only {count} {timeClass} {games} found — not enough for this analysis. Play more to unlock this view!',
    'chess.searchPrompt': 'Search for a player using the sidebar to view their statistics.',
    'chess.eloTitle': 'Elo Rating & Games Played',
    'chess.dailyVolumeTitle': 'How many games should you play every day?',
    'chess.winRate': 'Win Rate',
    'chess.winRateFormula': 'Win rate = (wins + draws / 2) / total.',
    'chess.winRateFilter': 'Only game counts with at least 10 days of data are shown.',
    'chess.gamesPerDay': 'Games per day',
    'chess.gamePerDay': 'Game per day',
    'chess.daysOfData': 'days of data',
    'chess.gameNumberTitle': 'Which games are your best games?',
    'chess.gameNumber': 'Game number',
    'chess.nthGame': 'game of the day',
    'chess.nthGames': 'games of the day',
    'chess.bestResults': 'Best Results',
    'chess.worstResults': 'Worst Results',
    'chess.situation': 'Situation',
    'chess.games': 'games',
    'chess.loadingCached': 'Loading...',
    'chess.fetchingGamesFrom': 'Fetching your games from {month}...',
    'chess.fetchingGames': 'Fetching your games...',
    'chess.aiTagline': 'Your AI chess assistant',
    'chess.analyzedGames': 'Analyzed {count} game{plural}{username}.',
    'chess.after1Win': 'After 1 win',
    'chess.afterNWins': 'After {n} wins',
    'chess.after1Loss': 'After 1 loss',
    'chess.afterNLosses': 'After {n} losses',
    'chess.insufficientData': 'Insufficient data',
    'chess.analysisLoading': 'Analysis loading...',
    'chess.keepPlayingWhileWinning': 'Keep playing as long as you are winning.',
    'chess.keepPlayingUpTo': 'Keep playing up to {n} wins in a row.',
    'chess.stopAfter1Loss': 'Stop playing after 1 loss.',
    'chess.stopAfterNLosses': 'Stop playing after {n} losses in a row.',
    'chess.todaysData': "Today's data",
    'chess.currentSituation': 'Current situation',
    'chess.gamesPlayed': 'Games Played',
    'chess.currentStreak': 'Current streak',
    'chess.predictedWinRate': 'Predicted win rate',
    'chess.win': 'Win',
    'chess.wins': 'Wins',
    'chess.loss': 'Loss',
    'chess.losses': 'Losses',
    'chess.fromDailyVolume': 'from daily volume',
    'chess.fromStreak': 'from streak',
    'chess.welcomeTitle': 'Your AI chess assistant',
    'chess.welcomeBack': 'Welcome back, {name}!',
    'chess.welcome': 'Welcome!',
    'chess.welcomeSubtitle': 'Explore these powerful analysis tools to improve your game:',
    'chess.usernamePrompt': 'What is your Chess.com username?',
    'chess.usernamePlaceholder': 'Enter your chess.com username',
    'chess.fetchData': 'Fetch data',
    'chess.recentSearches': 'Recent searches',
    'chess.loginTitle': "Let's improve your chess rating!",
    'chess.loginSubtitle1': 'Analyze your Chess.com games.',
    'chess.loginSubtitle2': 'Get personalized insights to improve your play.',
    'chess.eloDescription': 'Track your Elo progression and games played over time.',
    'chess.todayTitle': "Next game's predicted win rate",
    'chess.bestGamesTitle': 'Best Games',
    'chess.bestGamesCardTitle': 'Are you better on your 1st, 3rd or 5th game of the day?',
    'chess.streaksCardTitle': 'Should you keep playing after a loss?',
    'chess.breaksCardTitle': 'Should you take breaks between games?',
    'chess.breakGap': 'Break duration',
    'chess.breakBetweenGames': 'between games',
    'chess.breakRegression': 'Linear regression',
    'chess.onboardingInstruction': 'Enter your Chess.com username to get your personalized data analysis.',
    'chess.onboardingDescription': 'LUMNA is an AI-powered chess analytics tool which provides insights on how and when you should play to improve faster, based on your complete games history.',
    'chess.navHome': 'Home',
    'chess.navElo': 'Elo',
    'chess.navToday': 'Today',
    'chess.navDailyVolume': 'Daily Volume',
    'chess.navBestGames': 'Best Games',
    'chess.navStreaks': 'Streaks',
    'chess.navWhenToPlay': 'When to play',
    'chess.navBreaks': 'Breaks',
    'chess.whenToPlayTitle': 'When should you play?',
    'chess.bestHoursTitle': 'When should you play during the day?',
    'chess.bestDaysTitle': 'When should you play during the week?',
    'chess.heatmapTitle': 'Combined view',
    'chess.logout': 'Log out',
    'chess.continue': 'Continue',
    'chess.selectLanguage': 'Select preferred language',
    'chess.explore': 'Click to explore',
    'chess.fetchingData': 'Your data is being fetched...',
    'chess.ob.slide0': "Welcome to LUMNA. We analyze your chess games to find patterns in how you play, what helps you win, and what doesn't.",
    'chess.ob.slide1': 'We analyze your play volume, frequency, when you take breaks between games, and much more. By compiling your full Chess.com history, we provide a comprehensive look at your playing habits.',
    'chess.ob.slide2': 'Before we continue, which time control do you prefer?',
    'chess.ob.currentElo': 'Your current {timeClass} elo is',
    'chess.ob.unrated': 'You are currently unrated in {timeClass}. Set a goal to work towards.',
    'chess.ob.goalPrompt': "What's your goal for the next 3 months?",
    'chess.ob.noRating': 'Play some {timeClass} games on Chess.com to track your progress.',
    'chess.ob.conclusion': "You're all set. Let's see what your games reveal.",
    'chess.ob.next': 'Next',
    'chess.ob.letsGo': "Let's go",
    'chess.ob.almostReady': 'Almost ready...',
    'chess.ob.processing': 'Processing {month}...',
    'chess.navGoal': 'Your Goal',
    'chess.navFide': 'FIDE Rating',
    'chess.fide.title': 'Your FIDE Rating',
    'chess.fide.link': 'Link your FIDE profile',
    'chess.fide.enterFideId': 'Enter your FIDE ID',
    'chess.fide.notRated': 'N/R',
    'chess.fide.unrated': 'Unrated',
    'chess.fide.save': 'Save',
    'chess.fide.updateId': 'Update FIDE ID',
    'chess.fide.leaderboard': 'Leaderboard',
    'chess.fide.addFriend': 'Add a friend',
    'chess.fide.removeFriend': 'Remove',
    'chess.fide.enterFriendId': 'Enter FIDE ID',
    'chess.fide.add': 'Add',
    'chess.fide.invalidFideId': 'Invalid FIDE ID — please try again',
    'chess.fide.name': 'Name',
    'chess.fide.elo': 'Elo',
    'chess.fide.renameLeaderboard': 'Rename leaderboard',
    'chess.fide.rank': '#',
    'chess.goalCard.title': 'Your Goal',
    'chess.goalCard.updateGoal': 'Update goal',
    'chess.goalCard.setGoal': 'Set a goal',
    'chess.goalCard.setGoalPrompt': 'Set an elo goal to track your progress.',
    'chess.goalCard.goal': 'Goal',
    'chess.goalCard.actual': 'Actual',
    'chess.goalCard.save': 'Save',
    'chess.goalCard.cancel': 'Cancel',
    'chess.goalCard.months': 'in {n} month',
    'chess.goalCard.monthsPlural': 'in {n} months',
    'chess.goalCard.timeline': 'Timeline',

    // Coaches
    'coaches.title': 'AI-Powered Suite for Chess Coaches',
    'coaches.navHome': 'Home',
    'coaches.navCalendar': 'My Calendar',
    'coaches.navStudents': 'My Students',
    'coaches.navPayments': 'Payments',
    'coaches.navScoresheets': 'Scoresheet → PGN',
    'coaches.onboardingInstruction': 'Sign in to get started',
    'coaches.onboardingDescription': 'Manage your students, digitize scoresheets, analyze diagrams, and review time management — all in one place.',
    'coaches.uploadPrompt': 'Upload a scoresheet photo',
    'coaches.uploadHint': 'JPG, PNG — photo of a handwritten scoresheet',
    'coaches.pasteClipboard': 'Paste from clipboard',
    'coaches.photoLibrary': 'Photo Library',
    'coaches.takePhoto': 'Take a photo',
    'coaches.chooseFile': 'Choose file',
    'coaches.cancel': 'Cancel',
    'coaches.cropHint': 'Crop around the moves table',
    'coaches.example': 'Example',
    'coaches.cropConfirm': 'Confirm',
    'coaches.pasteHint': 'Tap here, then tap "Paste"',
    'coaches.replaceImage': 'New scoresheet',
    'coaches.analyzing': 'Analyzing scoresheet...',
    'coaches.reanalyze': 'Re-analyze',
    'coaches.consensus': 'Consensus',
    'coaches.individualReads': 'See Individual Reads',
    'coaches.results': 'Results',
    'coaches.models': 'models',
    'coaches.voteInfo': 'Vote info',
    'coaches.voteCandidate': 'Move',
    'coaches.voteVotes': 'Votes',
    'coaches.voteIllegals': 'Illegals after',
    'coaches.voteItselfIllegal': 'itself illegal',
    'coaches.voteAllIllegal': 'All options are illegal — please edit this move manually',
    'coaches.analyze': 'Analyze',
    'coaches.groundTruth': 'Ground Truth',
    'coaches.read': 'Read',
    'coaches.startingPosition': 'Starting position',
    'coaches.illegalMove': 'Illegal move',
    'coaches.illegal': 'Illegal',
    'coaches.illegalMovesTitle': 'Fix illegal moves first',
    'coaches.illegalMovesDesc': 'Some moves are marked as illegal.\nPlease correct them before exporting.',
    'coaches.legalMove': 'Legal',
    'coaches.variation': 'Variation',
    'coaches.variationMoves': 'move',
    'coaches.variationMovesPlural': 'moves',
    'coaches.backToMainLine': 'Go back to main line',
    'coaches.moveWhite': 'White',
    'coaches.moveBlack': 'Black',
    'coaches.move': 'Move',
    'coaches.rereading': 'Re-reading from edit...',
    'coaches.rereadFromEdit': 'Re-read from edit',
    'coaches.saving': 'saving...',
    'coaches.accuracy': 'accuracy',
    'coaches.editMove': 'Edit',
    'coaches.showOnBoard': 'Show on board',
    'coaches.save': 'Save',
    'coaches.revertToConsensus': 'Revert to consensus',
    'coaches.analyzeAzure': 'Analyzing with Azure DI...',
    'coaches.selectPiece': 'Select a piece',
    'coaches.navDiagram': 'Diagram → FEN',
    'coaches.diagram.uploadPrompt': 'Upload a chess diagram',
    'coaches.diagram.uploadHint': 'JPG, PNG — screenshot or photo of a chess position',
    'coaches.diagram.analyze': 'Extract FEN',
    'coaches.diagram.analyzing': 'Analyzing diagram...',
    'coaches.navMistakes': 'Mistake Finder',
    'coaches.mistakes.uploadPrompt': 'Upload a PGN file',
    'coaches.mistakes.uploadHint': '.pgn or .txt — must contain clock annotations [%clk]',
    'coaches.mistakes.findButton': 'Find mistakes',
    'coaches.mistakes.noClockData': 'No clock data found in this PGN. Moves need [%clk h:mm:ss] annotations.',
    'coaches.mistakes.movesWithClock': 'moves with clock data',
    'coaches.mistakes.noMistakes': 'No time-management mistakes found!',
    'coaches.mistakes.mistakeFound': 'time-management mistake found',
    'coaches.mistakes.mistakesFound': 'time-management mistakes found',
    'coaches.mistakes.ofClock': 'of clock spent',
    'coaches.mistakes.clockBefore': 'Clock before',
    'coaches.mistakes.timeSpent': 'Time spent',
    'coaches.mistakes.clockAfter': 'Clock after',
    'coaches.mistakes.analyzeAnother': 'Analyze another game',
    'coaches.mistakes.categoryTime': 'Time Management',
    'coaches.mistakes.categoryTbd': 'To Be Determined',
    'coaches.mistakes.a1.line1': 'Underthinking',
    'coaches.mistakes.a1.line2': 'a critical moment',
    'coaches.mistakes.a2.line1': 'Over-calculating',
    'coaches.mistakes.a2.line2': 'equal alternatives',
    'coaches.mistakes.b1.line1': 'Over-extending',
    'coaches.mistakes.b1.line2': 'a winning position',
    'coaches.mistakes.comingSoon': 'Coming soon',
    'coaches.navAbout': 'About',
    'coaches.about.description': 'Tools for chess coaches: digitize scoresheets, analyze diagrams, and review time management from your over-the-board games.',
    'coaches.about.credits': 'Credits & Licenses',
    'coaches.about.chesscomApi': 'Player profiles and game data',
    'coaches.about.gemini': 'Scoresheet and diagram recognition',
    'coaches.mistakes.selectAnalysis': 'Select an analysis',

    // Lichess integration
    'coaches.lichess.openChesscom': 'Open in Chess.com Analysis',
    'coaches.chesscom.syncToLibrary': 'Sync to Chess.com Library',
    'coaches.chesscom.copiedToLibrary': 'PGN copied! Paste it in your Library',
    'coaches.lichess.sendToStudy': 'Send to Lichess Study',
    'coaches.lichess.usernamePrompt': 'Enter your Lichess username',
    'coaches.lichess.usernameHint': 'This is needed to list your studies',
    'coaches.lichess.save': 'Save',
    'coaches.lichess.cancel': 'Cancel',
    'coaches.lichess.loading': 'Loading studies...',
    'coaches.lichess.noStudies': 'No studies found',
    'coaches.lichess.selectStudy': 'Select a study',
    'coaches.lichess.changeUser': 'Change',
    'coaches.lichess.importing': 'Importing...',
    'coaches.lichess.imported': 'PGN imported!',
    'coaches.lichess.openStudy': 'Open study on Lichess',
    'coaches.lichess.close': 'Close',

    // Students panel — scheduling
    'coaches.students.title': 'My Students',
    'coaches.students.empty': 'No students yet. Add your first student to get started.',
    'coaches.students.addStudent': 'Add Student',
    'coaches.students.editStudent': 'Edit',
    'coaches.students.deleteStudent': 'Delete',
    'coaches.students.deleteConfirm': 'Delete this student and all their lessons?',
    'coaches.students.name': 'Name',
    'coaches.students.timezone': 'Timezone',
    'coaches.students.city': 'City',
    'coaches.students.currency': 'Currency',
    'coaches.students.recurringSlot': 'Recurring lesson slot (optional)',
    'coaches.students.recurringLabel': 'Recurring lesson:',
    'coaches.students.noRecurring': 'No recurring slot',
    'coaches.students.save': 'Save',
    'coaches.students.cancel': 'Cancel',
    'coaches.students.search': 'Search students...',
    'coaches.students.scheduleLesson': 'Schedule',
    'coaches.students.scheduleLessonFull': 'Schedule a lesson',
    'coaches.students.reschedule': 'Reschedule',
    'coaches.students.when': 'When',
    'coaches.students.duration': 'Duration',
    'coaches.students.minutes': 'min',
    'coaches.students.scheduled': 'Scheduled',
    'coaches.students.completedStatus': 'Completed',
    'coaches.students.cancelledStatus': 'Cancelled',
    'coaches.students.rescheduledStatus': 'Rescheduled',
    'coaches.students.dstAlert': 'Daylight saving time change coming',
    'coaches.student.upcoming': 'Upcoming',
    'coaches.student.history': 'Past',
    'coaches.students.deleteStudentFull': 'Delete student',
    'coaches.student.noLessons': 'No lessons yet. Schedule one to get started.',
    'coaches.calendar.title': 'My Calendar',
    'coaches.calendar.noLessons': 'No lessons this week. Schedule one from My Students.',
    'coaches.calendar.detectTitle': 'Are you in...',
    'coaches.calendar.confirm': 'Yes, confirm',
    'coaches.calendar.changeCity': 'No, change city',
    'coaches.calendar.setupTitle': 'Set your city',
    'coaches.calendar.setupDesc': 'So we can display lesson times in your timezone.',
    'coaches.calendar.myCity': 'My city',
    // Payments panel
    'coaches.payments.title': 'Payments',
    'coaches.payments.allPaid': 'All lessons are paid. You\'re all caught up!',
    'coaches.payments.lessonUnpaid': 'lesson unpaid',
    'coaches.payments.lessonsUnpaid': 'lessons unpaid',
    'coaches.payments.markPaid': 'Mark paid',
    // Shared
    'coaches.sectionAdmin': 'Admin',
    'coaches.sectionLessons': 'My Lessons',
    'coaches.sectionAITools': 'AI Tools',
    'coaches.sectionEmpty': 'Coming soon',
    'coaches.previous': 'Previous',
    'coaches.status.done': 'done',
    'coaches.status.loading': 'reading...',
    'coaches.status.consensusDone': 'Consensus done',
    'coaches.status.consensusComputing': 'Consensus computing...',
    'coaches.navAdmin': 'Admin',
    // Admin panel
    'coaches.admin.user1': 'user',
    'coaches.admin.users': 'users',
    'coaches.admin.ignoreSelf': 'Ignore myself',
    'coaches.admin.dailyTimeSpent': 'Daily Time Spent (minutes)',
    'coaches.admin.time': 'Time',
    'coaches.admin.failedLoad': 'Failed to load users',
    'coaches.admin.user': 'User',
    'coaches.admin.joined': 'Joined',
    'coaches.admin.lastActive': 'Last Active',
    'coaches.admin.sessions': 'Sessions',

    // Tax Calculator
    'taxCalc.title': 'Tax Calculator',
    'taxCalc.subtitle': 'CTO (31.4% on unrealized gains) vs Holding (IS 15% + flat tax 31.4%)',
    'taxCalc.parameters': 'Simulation Parameters',
    'taxCalc.years': 'Investment period (years)',
    'taxCalc.growthRate': 'Annual growth rate',
    'taxCalc.initialValue': 'Initial portfolio value (€)',
    'taxCalc.chartTitle': 'Portfolio Value Over Time',
    'taxCalc.tableTitle': 'Year-by-Year Breakdown',
    'taxCalc.yearCol': 'Year',
    'taxCalc.verdict': 'Final Comparison (Net in Pocket)',
    'taxCalc.totalTaxPaid': 'Total tax paid',
    'taxCalc.differenceLabel': 'Difference',

    // Common
    'common.loading': 'Loading...',
    'common.error': 'Error',
    'common.signInRequired': 'Sign In Required',
    'common.signInMessage': 'Please sign in to view your portfolio.',
  },
  fr: {
    // Portfolio
    'portfolio.title': 'Mon Portefeuille',
    'portfolio.subtitle': 'Suivez vos transactions et performances d\'investissement',
    'portfolio.editButton': 'Modifier les transactions',
    'portfolio.privateMode': 'Mode privé',
    'portfolio.totalValue': 'Valeur Actuelle (EUR)',
    'portfolio.costBasis': 'Capital Investi (EUR)',
    'portfolio.totalGain': 'Gain Total',

    // Accounts
    'accounts.title': 'Comptes d\'Investissement',
    'accounts.addAccount': 'Ajouter un compte',
    'accounts.accountType': 'Type de compte',
    'accounts.bank': 'Banque / Courtier',
    'accounts.selectType': 'Sélectionner...',
    'accounts.selectBank': 'Sélectionner...',
    'accounts.create': 'Créer',
    'accounts.cancel': 'Annuler',
    'accounts.noAccounts': 'Aucun compte. Créez un compte pour suivre les frais.',
    'accounts.type': 'Type',
    'accounts.tax': 'impôt',
    'accounts.fees': 'Frais',

    // Transactions
    'transactions.title': 'Historique des Transactions',
    'transactions.addTransaction': 'Ajouter des transactions manuellement',
    'transactions.importRevolut': 'Importer directement depuis Revolut',
    'transactions.close': 'Fermer',
    'transactions.allStocks': 'Toutes les actions',
    'transactions.searchStocks': 'Rechercher...',
    'transactions.buy': 'Achat',
    'transactions.sell': 'Vente',
    'transactions.quantity': 'Quantité',
    'transactions.year': 'Année',
    'transactions.month': 'Mois',
    'transactions.day': 'Jour',
    'transactions.noAccount': 'Aucun compte',
    'transactions.add': 'Ajouter',
    'transactions.done': 'Terminé',
    'transactions.priceNote': 'Le prix sera récupéré automatiquement depuis les données de marché.',
    'transactions.selectAccount': 'Sélectionnez un compte pour suivre les frais.',
    'transactions.noTransactions': 'Aucune transaction. Ajoutez votre première transaction.',
    'transactions.shares': 'actions',

    // Holdings
    'holdings.title': 'Positions Actuelles',
    'holdings.stock': 'Action',
    'holdings.shares': 'Actions',
    'holdings.price': 'Prix/action',
    'holdings.value': 'Valeur (EUR)',
    'holdings.weight': 'Poids',
    'holdings.gain': 'Gain',
    'holdings.held': 'Détenu',

    // Performance
    'performance.title': 'Performance du Portefeuille',
    'performance.cagr': 'Taux de Croissance Annuel Composé (TCAC)',
    'performance.cagrFull': 'Taux de Croissance Annuel Composé',
    'performance.cagrTooltip': 'Le taux de rendement annualisé, en supposant que les profits sont réinvestis. Montre à quel taux votre investissement croîtrait par an si la croissance était constante.',
    'performance.simpleReturn': 'Rendement Simple (RS)',
    'performance.simpleReturnTooltip': 'Pourcentage total de gain ou perte sur votre investissement, calculé comme (Valeur Actuelle - Investi) / Investi.',
    'performance.twr': 'Rendement Pondéré par le Temps (RPT)',
    'performance.twrFull': 'Rendement Pondéré par le Temps',
    'performance.twrTooltip': 'Mesure la performance des investissements en excluant l\'impact des dépôts et retraits. Idéal pour comparer les gestionnaires de portefeuille.',
    'performance.mwr': 'Rendement Pondéré par l\'Argent (RPA)',
    'performance.mwrFull': 'Rendement Pondéré par l\'Argent',
    'performance.mwrTooltip': 'Mesure votre rendement réel en tenant compte du timing et du montant de vos dépôts/retraits. Sensible au moment où vous ajoutez ou retirez de l\'argent.',
    'performance.irr': 'Taux de Rendement Interne (TRI)',
    'performance.irrFull': 'Taux de Rendement Interne',
    'performance.irrTooltip': 'Le taux annualisé qui rend la valeur actuelle nette de tous les flux de trésorerie égale à zéro. Même calcul que le RPA.',
    'performance.metricsInfoTitle': 'À propos des métriques de performance',
    'performance.metricsInfoText': 'Le Rendement Simple et le TCAC ne tiennent pas compte des flux de trésorerie intermédiaires (dépôts/retraits). Pour les portefeuilles avec plusieurs transactions, le TRI et le TRM fournissent des mesures de performance plus précises.',
    'performance.advancedMetrics': 'Métriques de Performance Avancées',
    'performance.allTime': 'Cumul',
    'performance.annualized': 'Annualisé',
    'performance.srCagrExample': 'Vous investissez 1 000€ au début de l\'année 0.\nAprès 1 an, vous ajoutez 500€.\nAprès 2 ans, votre portefeuille vaut 1 815€.\n\nRendement Simple = (1815 - 1500) / 1500 = +21%\nTCAC = (1815 / 1500)^(1/2) - 1 = +10% par an\n\nNote : Ces métriques ignorent QUAND vous avez ajouté les 500€. Elles comparent uniquement le total investi vs la valeur finale.',
    'performance.twrMwrExample': 'En janvier, vous investissez 10 000€.\nEn juin, la valeur est de 11 000€.\nVous ajoutez alors 5 000€.\nEn décembre, la valeur totale est de 17 000€.\n\nRPT = (11000/10000) × (17000/16000) - 1 = +16.9%\n→ Mesure la performance pure en chaînant les rendements des sous-périodes.\n\nRPA = le taux r où : -10000 + (-5000)/(1+r)^0.5 + 17000/(1+r)^1 = 0 → r = +11.5%\n→ Votre rendement réel, tenant compte du moment où vous avez ajouté de l\'argent.\n\nNote : Le TRI est simplement la version annualisée du RPA.',
    'performance.perYear': '(par an)',
    'performance.showExample': 'Voir exemple',
    'performance.year': 'an',
    'performance.years': 'ans',
    'performance.month': 'mois',
    'performance.months': 'mois',
    'performance.since': 'Depuis le',
    'performance.totalReturn': 'Gains du portefeuille',
    'performance.benchmark.qqq': 'Indice: QQQ (Nasdaq-100)',
    'performance.benchmark.sp500': 'Indice: S&P 500',
    'performance.portfolio': 'Portefeuille',
    'performance.invested': 'Capital investi',

    // Chess
    'chess.rapid': 'Rapide',
    'chess.bullet': 'Bullet',
    'chess.myData': 'Mes Données',
    'chess.noData': 'Aucune donnée disponible',
    'chess.notEnoughGames': 'Seulement {count} {games} en {timeClass} — pas assez pour cette analyse. Jouez davantage pour débloquer cette vue !',
    'chess.searchPrompt': 'Recherchez un joueur via la barre latérale pour voir ses statistiques.',
    'chess.eloTitle': 'Classement Elo & Parties Jouées',
    'chess.dailyVolumeTitle': 'Combien de parties jouer par jour ?',
    'chess.winRate': 'Taux de Victoire',
    'chess.winRateFormula': 'Taux de victoire = (Taux de victoires + 0.5 x Taux de nulles)',
    'chess.winRateFilter': 'Seuls les volumes avec au moins 10 jours de données sont affichés.',
    'chess.gamesPerDay': 'Parties par jour',
    'chess.gamePerDay': 'Partie par jour',
    'chess.daysOfData': 'jours de données',
    'chess.gameNumberTitle': 'Quelles sont vos meilleures parties ?',
    'chess.gameNumber': 'Numéro de partie',
    'chess.nthGame': 'partie de la journée',
    'chess.nthGames': 'parties de la journée',
    'chess.bestResults': 'Meilleurs résultats',
    'chess.worstResults': 'Pires résultats',
    'chess.situation': 'Situation',
    'chess.games': 'parties',
    'chess.loadingCached': 'Chargement...',
    'chess.fetchingGamesFrom': 'Récupération de vos parties de {month}...',
    'chess.fetchingGames': 'Récupération de vos parties...',
    'chess.aiTagline': 'Votre assistant d\'échecs IA',
    'chess.analyzedGames': '{count} partie{plural}{username} analysée{plural}.',
    'chess.after1Win': 'Après 1 victoire',
    'chess.afterNWins': 'Après {n} victoires',
    'chess.after1Loss': 'Après 1 défaite',
    'chess.afterNLosses': 'Après {n} défaites',
    'chess.insufficientData': 'Données insuffisantes',
    'chess.analysisLoading': 'Analyse en cours...',
    'chess.keepPlayingWhileWinning': 'Continuez à jouer tant que vous gagnez.',
    'chess.keepPlayingUpTo': "Continuez à jouer jusqu'à {n} victoires d'affilée.",
    'chess.stopAfter1Loss': 'Arrêtez de jouer après 1 défaite.',
    'chess.stopAfterNLosses': 'Arrêtez de jouer après {n} défaites consécutives.',
    'chess.todaysData': "Données du jour",
    'chess.currentSituation': 'Situation actuelle',
    'chess.gamesPlayed': 'Parties jouées',
    'chess.currentStreak': 'Série en cours',
    'chess.predictedWinRate': 'Taux de victoire prédit',
    'chess.win': 'Victoire',
    'chess.wins': 'Victoires',
    'chess.loss': 'Défaite',
    'chess.losses': 'Défaites',
    'chess.fromDailyVolume': 'du volume quotidien',
    'chess.fromStreak': 'de la série',
    'chess.welcomeTitle': 'Votre assistant échecs IA',
    'chess.welcomeBack': 'Bienvenue, {name} !',
    'chess.welcome': 'Bienvenue !',
    'chess.welcomeSubtitle': 'Explorez ces outils d\'analyse pour améliorer votre jeu :',
    'chess.usernamePrompt': 'Quel est votre nom d\'utilisateur Chess.com ?',
    'chess.usernamePlaceholder': 'Entrez votre nom d\'utilisateur chess.com',
    'chess.fetchData': 'Récupérer',
    'chess.recentSearches': 'Recherches récentes',
    'chess.loginTitle': 'Améliorons votre classement aux échecs !',
    'chess.loginSubtitle1': 'Analysez vos parties Chess.com.',
    'chess.loginSubtitle2': 'Obtenez des insights personnalisés pour progresser.',
    'chess.eloDescription': 'Suivez votre progression Elo et vos parties jouées.',
    'chess.todayTitle': 'Taux de victoire prédit de votre prochaine partie',
    'chess.bestGamesTitle': 'Meilleures Parties',
    'chess.bestGamesCardTitle': 'Êtes-vous meilleur à votre 1ère, 3ème ou 5ème partie du jour ?',
    'chess.streaksCardTitle': 'Devriez-vous continuer à jouer après une défaite ?',
    'chess.breaksCardTitle': 'Devriez-vous faire des pauses entre vos parties ?',
    'chess.breakGap': 'Durée de la pause',
    'chess.breakBetweenGames': 'entre les parties',
    'chess.breakRegression': 'Régression linéaire',
    'chess.onboardingInstruction': 'Entrez votre nom d\'utilisateur Chess.com pour obtenir votre analyse personnalisée.',
    'chess.onboardingDescription': 'LUMNA est un outil d\'analyse IA qui vous indique quand et comment jouer pour progresser plus vite aux échecs, en se basant sur votre historique complet de parties.',
    'chess.navHome': 'Accueil',
    'chess.navElo': 'Elo',
    'chess.navToday': 'Aujourd\'hui',
    'chess.navDailyVolume': 'Volume quotidien',
    'chess.navBestGames': 'Meilleures parties',
    'chess.navStreaks': 'Séries',
    'chess.navWhenToPlay': 'Quand jouer',
    'chess.navBreaks': 'Pauses',
    'chess.whenToPlayTitle': 'Quand devriez-vous jouer ?',
    'chess.bestHoursTitle': 'Quand devriez-vous jouer dans la journée ?',
    'chess.bestDaysTitle': 'Quand devriez-vous jouer dans la semaine ?',
    'chess.heatmapTitle': 'Vue combinée',
    'chess.logout': 'Se déconnecter',
    'chess.continue': 'Continuer',
    'chess.selectLanguage': 'Choisissez votre langue',
    'chess.explore': 'Cliquez pour explorer',
    'chess.fetchingData': 'Vos données sont en cours de chargement...',
    'chess.ob.slide0': "Bienvenue sur LUMNA. Nous analysons vos parties d'échecs pour identifier des tendances dans votre jeu, ce qui vous aide à gagner, et ce qui vous freine.",
    'chess.ob.slide1': "Nous analysons votre volume de jeu, votre fréquence, vos pauses entre les parties, et bien plus encore. En compilant tout votre historique Chess.com, nous dressons un portrait complet de vos habitudes de jeu.",
    'chess.ob.slide2': 'Avant de continuer, quel format de temps préférez-vous ?',
    'chess.ob.currentElo': 'Votre elo actuel en {timeClass} est',
    'chess.ob.unrated': "Vous n'avez pas encore de classement en {timeClass}. Fixez-vous un objectif.",
    'chess.ob.goalPrompt': 'Quel est votre objectif elo pour les 3 prochains mois ?',
    'chess.ob.noRating': 'Jouez des parties en {timeClass} sur Chess.com pour suivre votre progression.',
    'chess.ob.conclusion': "C'est parti. Voyons ce que vos parties révèlent.",
    'chess.ob.next': 'Suivant',
    'chess.ob.letsGo': "C'est parti",
    'chess.ob.almostReady': 'Presque prêt...',
    'chess.ob.processing': 'Traitement de {month}...',
    'chess.navGoal': 'Votre Objectif',
    'chess.navFide': 'Classement FIDE',
    'chess.fide.title': 'Votre Classement FIDE',
    'chess.fide.link': 'Liez votre profil FIDE',
    'chess.fide.enterFideId': 'Entrez votre ID FIDE',
    'chess.fide.notRated': 'N/C',
    'chess.fide.unrated': 'Non classé',
    'chess.fide.save': 'Enregistrer',
    'chess.fide.updateId': 'Modifier l\'ID FIDE',
    'chess.fide.leaderboard': 'Classement',
    'chess.fide.addFriend': 'Ajouter un ami',
    'chess.fide.removeFriend': 'Supprimer',
    'chess.fide.enterFriendId': 'Entrez l\'ID FIDE',
    'chess.fide.add': 'Ajouter',
    'chess.fide.invalidFideId': 'ID FIDE invalide — veuillez réessayer',
    'chess.fide.name': 'Nom',
    'chess.fide.elo': 'Elo',
    'chess.fide.renameLeaderboard': 'Renommer le classement',
    'chess.fide.rank': '#',
    'chess.goalCard.title': 'Votre Objectif',
    'chess.goalCard.updateGoal': 'Modifier l\'objectif',
    'chess.goalCard.setGoal': 'Fixer un objectif',
    'chess.goalCard.setGoalPrompt': 'Fixez un objectif elo pour suivre votre progression.',
    'chess.goalCard.goal': 'Objectif',
    'chess.goalCard.actual': 'Réel',
    'chess.goalCard.save': 'Enregistrer',
    'chess.goalCard.cancel': 'Annuler',
    'chess.goalCard.months': 'dans {n} mois',
    'chess.goalCard.monthsPlural': 'dans {n} mois',
    'chess.goalCard.timeline': 'Durée',

    // Coaches
    'coaches.title': 'Suite IA pour entra\u00EEneurs d\'\u00E9checs',
    'coaches.navHome': 'Accueil',
    'coaches.navCalendar': 'Mon calendrier',
    'coaches.navStudents': 'Mes élèves',
    'coaches.navPayments': 'Paiements',
    'coaches.navScoresheets': 'Feuille de partie → PGN',
    'coaches.onboardingInstruction': 'Connectez-vous pour commencer',
    'coaches.onboardingDescription': 'Gérez vos élèves, numérisez des feuilles de partie, analysez des diagrammes et examinez la gestion du temps — le tout en un seul endroit.',
    'coaches.uploadPrompt': 'Importer une photo de feuille de partie',
    'coaches.uploadHint': 'JPG, PNG — photo d\'une feuille de partie manuscrite',
    'coaches.pasteClipboard': 'Coller depuis le presse-papiers',
    'coaches.photoLibrary': 'Photothèque',
    'coaches.takePhoto': 'Prendre une photo',
    'coaches.chooseFile': 'Choisir le fichier',
    'coaches.cancel': 'Annuler',
    'coaches.cropHint': 'Recadrez autour du tableau des coups',
    'coaches.example': 'Exemple',
    'coaches.cropConfirm': 'Confirmer',
    'coaches.pasteHint': 'Appuyez ici, puis « Coller »',
    'coaches.replaceImage': 'Nouvelle feuille',
    'coaches.analyzing': 'Analyse en cours...',
    'coaches.reanalyze': 'Ré-analyser',
    'coaches.consensus': 'Consensus',
    'coaches.individualReads': 'Voir les lectures individuelles',
    'coaches.results': 'Résultats',
    'coaches.models': 'modèles',
    'coaches.voteInfo': 'Détails du vote',
    'coaches.voteCandidate': 'Coup',
    'coaches.voteVotes': 'Votes',
    'coaches.voteIllegals': 'Illégaux après',
    'coaches.voteItselfIllegal': 'lui-même illégal',
    'coaches.voteAllIllegal': 'Toutes les options sont illégales — veuillez corriger manuellement',
    'coaches.analyze': 'Analyser',
    'coaches.groundTruth': 'Référence',
    'coaches.read': 'Lecture',
    'coaches.startingPosition': 'Position de départ',
    'coaches.illegalMove': 'Coup illégal',
    'coaches.illegal': 'Illégal',
    'coaches.illegalMovesTitle': 'Corrigez les coups illégaux',
    'coaches.illegalMovesDesc': 'Certains coups sont marqués comme illégaux.\nVeuillez les corriger avant d\'exporter.',
    'coaches.legalMove': 'Légal',
    'coaches.variation': 'Variante',
    'coaches.variationMoves': 'coup',
    'coaches.variationMovesPlural': 'coups',
    'coaches.backToMainLine': 'Revenir à la ligne principale',
    'coaches.moveWhite': 'Blancs',
    'coaches.moveBlack': 'Noirs',
    'coaches.move': 'Coup',
    'coaches.rereading': 'Relecture en cours...',
    'coaches.rereadFromEdit': 'Relire à partir de la correction',
    'coaches.saving': 'enregistrement...',
    'coaches.accuracy': 'précision',
    'coaches.editMove': 'Modifier',
    'coaches.showOnBoard': 'Voir sur l\'échiquier',
    'coaches.save': 'Enregistrer',
    'coaches.revertToConsensus': 'Revenir au consensus',
    'coaches.analyzeAzure': 'Analyse Azure DI...',
    'coaches.selectPiece': 'Sélectionnez une pièce',
    'coaches.navDiagram': 'Diagramme → FEN',
    'coaches.diagram.uploadPrompt': 'Importer un diagramme d\'échecs',
    'coaches.diagram.uploadHint': 'JPG, PNG — capture d\'écran ou photo d\'une position',
    'coaches.diagram.analyze': 'Extraire le FEN',
    'coaches.diagram.analyzing': 'Analyse du diagramme...',
    'coaches.navMistakes': 'Détecteur d\'erreurs',
    'coaches.mistakes.uploadPrompt': 'Importer un fichier PGN',
    'coaches.mistakes.uploadHint': '.pgn ou .txt — doit contenir des annotations d\'horloge [%clk]',
    'coaches.mistakes.findButton': 'Trouver les erreurs',
    'coaches.mistakes.noClockData': 'Aucune donnée d\'horloge trouvée dans ce PGN. Les coups doivent avoir des annotations [%clk h:mm:ss].',
    'coaches.mistakes.movesWithClock': 'coups avec données d\'horloge',
    'coaches.mistakes.noMistakes': 'Aucune erreur de gestion du temps trouvée !',
    'coaches.mistakes.mistakeFound': 'erreur de gestion du temps trouvée',
    'coaches.mistakes.mistakesFound': 'erreurs de gestion du temps trouvées',
    'coaches.mistakes.ofClock': 'du temps utilisé',
    'coaches.mistakes.clockBefore': 'Horloge avant',
    'coaches.mistakes.timeSpent': 'Temps passé',
    'coaches.mistakes.clockAfter': 'Horloge après',
    'coaches.mistakes.analyzeAnother': 'Analyser une autre partie',
    'coaches.mistakes.categoryTime': 'Gestion du temps',
    'coaches.mistakes.categoryTbd': 'À déterminer',
    'coaches.mistakes.a1.line1': 'Sous-réfléchir',
    'coaches.mistakes.a1.line2': 'un moment critique',
    'coaches.mistakes.a2.line1': 'Sur-calculer',
    'coaches.mistakes.a2.line2': 'des alternatives égales',
    'coaches.mistakes.b1.line1': 'Sur-jouer',
    'coaches.mistakes.b1.line2': 'une position gagnante',
    'coaches.mistakes.comingSoon': 'Bientôt disponible',
    'coaches.navAbout': 'À propos',
    'coaches.about.description': 'Outils pour entraîneurs d\'échecs : numériser des feuilles de partie, analyser des diagrammes et examiner la gestion du temps de vos parties en présentiel.',
    'coaches.about.credits': 'Crédits & Licences',
    'coaches.about.chesscomApi': 'Profils de joueurs et données de parties',
    'coaches.about.gemini': 'Reconnaissance de feuilles de partie et diagrammes',
    'coaches.mistakes.selectAnalysis': 'Sélectionnez une analyse',

    // Lichess integration
    'coaches.lichess.openChesscom': 'Ouvrir dans l\'analyse Chess.com',
    'coaches.chesscom.syncToLibrary': 'Sync vers la Bibliothèque Chess.com',
    'coaches.chesscom.copiedToLibrary': 'PGN copié ! Collez-le dans votre Bibliothèque',
    'coaches.lichess.sendToStudy': 'Envoyer vers une étude Lichess',
    'coaches.lichess.usernamePrompt': 'Entrez votre pseudo Lichess',
    'coaches.lichess.usernameHint': 'Nécessaire pour lister vos études',
    'coaches.lichess.save': 'Enregistrer',
    'coaches.lichess.cancel': 'Annuler',
    'coaches.lichess.loading': 'Chargement des études...',
    'coaches.lichess.noStudies': 'Aucune étude trouvée',
    'coaches.lichess.selectStudy': 'Choisir une étude',
    'coaches.lichess.changeUser': 'Changer',
    'coaches.lichess.importing': 'Import en cours...',
    'coaches.lichess.imported': 'PGN importé !',
    'coaches.lichess.openStudy': 'Ouvrir l\'étude sur Lichess',
    'coaches.lichess.close': 'Fermer',

    // Students panel — scheduling
    'coaches.students.title': 'Mes élèves',
    'coaches.students.empty': 'Aucun élève pour le moment. Ajoutez votre premier élève pour commencer.',
    'coaches.students.addStudent': 'Ajouter un élève',
    'coaches.students.editStudent': 'Modifier',
    'coaches.students.deleteStudent': 'Supprimer',
    'coaches.students.deleteConfirm': 'Supprimer cet élève et tous ses cours ?',
    'coaches.students.name': 'Nom',
    'coaches.students.timezone': 'Fuseau horaire',
    'coaches.students.city': 'Ville',
    'coaches.students.currency': 'Devise',
    'coaches.students.recurringSlot': 'Créneau de cours récurrent (optionnel)',
    'coaches.students.recurringLabel': 'Cours récurrent :',
    'coaches.students.noRecurring': 'Pas de créneau récurrent',
    'coaches.students.save': 'Enregistrer',
    'coaches.students.cancel': 'Annuler',
    'coaches.students.search': 'Rechercher des élèves...',
    'coaches.students.scheduleLesson': 'Planifier',
    'coaches.students.scheduleLessonFull': 'Planifier un cours',
    'coaches.students.reschedule': 'Reprogrammer',
    'coaches.students.when': 'Quand',
    'coaches.students.duration': 'Durée',
    'coaches.students.minutes': 'min',
    'coaches.students.scheduled': 'Planifié',
    'coaches.students.completedStatus': 'Terminé',
    'coaches.students.cancelledStatus': 'Annulé',
    'coaches.students.rescheduledStatus': 'Reporté',
    'coaches.students.dstAlert': 'Changement d\'heure (heure d\'été) à venir',
    'coaches.student.upcoming': 'À venir',
    'coaches.student.history': 'Passés',
    'coaches.students.deleteStudentFull': 'Supprimer l\'élève',
    'coaches.student.noLessons': 'Aucun cours pour le moment. Planifiez-en un pour commencer.',
    'coaches.calendar.title': 'Mon calendrier',
    'coaches.calendar.noLessons': 'Aucun cours cette semaine. Planifiez-en un depuis Mes élèves.',
    'coaches.calendar.detectTitle': 'Vous êtes à...',
    'coaches.calendar.confirm': 'Oui, confirmer',
    'coaches.calendar.changeCity': 'Non, changer de ville',
    'coaches.calendar.setupTitle': 'Indiquez votre ville',
    'coaches.calendar.setupDesc': 'Pour afficher les heures de cours dans votre fuseau horaire.',
    'coaches.calendar.myCity': 'Ma ville',
    // Payments panel
    'coaches.payments.title': 'Paiements',
    'coaches.payments.allPaid': 'Tous les cours sont payés. Rien en attente !',
    'coaches.payments.lessonUnpaid': 'cours non payé',
    'coaches.payments.lessonsUnpaid': 'cours non payés',
    'coaches.payments.markPaid': 'Marquer payé',
    // Shared
    'coaches.sectionAdmin': 'Administratif',
    'coaches.sectionLessons': 'Mes cours',
    'coaches.sectionAITools': 'Outils IA',
    'coaches.sectionEmpty': 'Bientôt disponible',
    'coaches.previous': 'Précédent',
    'coaches.status.done': 'terminé',
    'coaches.status.loading': 'lecture...',
    'coaches.status.consensusDone': 'Consensus terminé',
    'coaches.status.consensusComputing': 'Consensus en cours...',
    'coaches.navAdmin': 'Admin',
    // Admin panel
    'coaches.admin.user1': 'utilisateur',
    'coaches.admin.users': 'utilisateurs',
    'coaches.admin.ignoreSelf': 'M\'exclure',
    'coaches.admin.dailyTimeSpent': 'Temps passé par jour (minutes)',
    'coaches.admin.time': 'Temps',
    'coaches.admin.failedLoad': 'Erreur de chargement des utilisateurs',
    'coaches.admin.user': 'Utilisateur',
    'coaches.admin.joined': 'Inscrit',
    'coaches.admin.lastActive': 'Dernière activité',
    'coaches.admin.sessions': 'Sessions',

    // Tax Calculator
    'taxCalc.title': 'Simulateur Fiscal',
    'taxCalc.subtitle': 'CTO (31.4% sur gains latents) vs Holding (IS 15% + PFU 31.4%)',
    'taxCalc.parameters': 'Paramètres de simulation',
    'taxCalc.years': 'Durée d\'investissement (années)',
    'taxCalc.growthRate': 'Taux de croissance annuel',
    'taxCalc.initialValue': 'Valeur initiale du portefeuille (€)',
    'taxCalc.chartTitle': 'Valeur du portefeuille dans le temps',
    'taxCalc.tableTitle': 'Détail année par année',
    'taxCalc.yearCol': 'Année',
    'taxCalc.verdict': 'Comparaison finale (Net en poche)',
    'taxCalc.totalTaxPaid': 'Impôts totaux payés',
    'taxCalc.differenceLabel': 'Différence',

    // Common
    'common.loading': 'Chargement...',
    'common.error': 'Erreur',
    'common.signInRequired': 'Connexion Requise',
    'common.signInMessage': 'Veuillez vous connecter pour voir votre portefeuille.',
  },
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    // Check URL param first (used when transferring between browsers)
    try {
      const params = new URLSearchParams(window.location.search);
      const urlLang = params.get('lang');
      if (urlLang === 'en' || urlLang === 'fr') {
        localStorage.setItem('language', urlLang);
        const url = new URL(window.location.href);
        url.searchParams.delete('lang');
        window.history.replaceState({}, '', url.pathname + url.search + url.hash);
        return urlLang;
      }
    } catch {}
    const saved = localStorage.getItem('language');
    if (saved) return saved as Language;
    const browserLang = navigator.language || navigator.languages?.[0] || '';
    return browserLang.startsWith('fr') ? 'fr' : 'en';
  });

  // Record language to backend for analytics (called when user changes language)
  const recordLanguage = (lang: Language) => {
    axios.post('/api/language', { language: lang }).catch(() => {});
  };

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('language', lang);
    recordLanguage(lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  const tAll = (key: string) => ({
    en: translations.en[key] || key,
    fr: translations.fr[key] || key,
  });

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t, tAll }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
